// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cosmos/upgrade/v1beta1/query.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/protobuf/types/known/anypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// QueryCurrentPlanRequest is the request type for the Query/CurrentPlan RPC
// method.
type QueryCurrentPlanRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryCurrentPlanRequest) Reset()         { *m = QueryCurrentPlanRequest{} }
func (m *QueryCurrentPlanRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCurrentPlanRequest) ProtoMessage()    {}
func (*QueryCurrentPlanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a334d07ad8374f0, []int{0}
}

func (m *QueryCurrentPlanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryCurrentPlanRequest.Unmarshal(m, b)
}
func (m *QueryCurrentPlanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryCurrentPlanRequest.Marshal(b, m, deterministic)
}
func (m *QueryCurrentPlanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCurrentPlanRequest.Merge(m, src)
}
func (m *QueryCurrentPlanRequest) XXX_Size() int {
	return xxx_messageInfo_QueryCurrentPlanRequest.Size(m)
}
func (m *QueryCurrentPlanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCurrentPlanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCurrentPlanRequest proto.InternalMessageInfo

// QueryCurrentPlanResponse is the response type for the Query/CurrentPlan RPC
// method.
type QueryCurrentPlanResponse struct {
	// plan is the current upgrade plan.
	Plan                 *Plan    `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryCurrentPlanResponse) Reset()         { *m = QueryCurrentPlanResponse{} }
func (m *QueryCurrentPlanResponse) String() string { return proto.CompactTextString(m) }
func (*QueryCurrentPlanResponse) ProtoMessage()    {}
func (*QueryCurrentPlanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a334d07ad8374f0, []int{1}
}

func (m *QueryCurrentPlanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryCurrentPlanResponse.Unmarshal(m, b)
}
func (m *QueryCurrentPlanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryCurrentPlanResponse.Marshal(b, m, deterministic)
}
func (m *QueryCurrentPlanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCurrentPlanResponse.Merge(m, src)
}
func (m *QueryCurrentPlanResponse) XXX_Size() int {
	return xxx_messageInfo_QueryCurrentPlanResponse.Size(m)
}
func (m *QueryCurrentPlanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCurrentPlanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCurrentPlanResponse proto.InternalMessageInfo

func (m *QueryCurrentPlanResponse) GetPlan() *Plan {
	if m != nil {
		return m.Plan
	}
	return nil
}

// QueryCurrentPlanRequest is the request type for the Query/AppliedPlan RPC
// method.
type QueryAppliedPlanRequest struct {
	// name is the name of the applied plan to query for.
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryAppliedPlanRequest) Reset()         { *m = QueryAppliedPlanRequest{} }
func (m *QueryAppliedPlanRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAppliedPlanRequest) ProtoMessage()    {}
func (*QueryAppliedPlanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a334d07ad8374f0, []int{2}
}

func (m *QueryAppliedPlanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryAppliedPlanRequest.Unmarshal(m, b)
}
func (m *QueryAppliedPlanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryAppliedPlanRequest.Marshal(b, m, deterministic)
}
func (m *QueryAppliedPlanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAppliedPlanRequest.Merge(m, src)
}
func (m *QueryAppliedPlanRequest) XXX_Size() int {
	return xxx_messageInfo_QueryAppliedPlanRequest.Size(m)
}
func (m *QueryAppliedPlanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAppliedPlanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAppliedPlanRequest proto.InternalMessageInfo

func (m *QueryAppliedPlanRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// QueryAppliedPlanResponse is the response type for the Query/AppliedPlan RPC
// method.
type QueryAppliedPlanResponse struct {
	// height is the block height at which the plan was applied.
	Height               int64    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryAppliedPlanResponse) Reset()         { *m = QueryAppliedPlanResponse{} }
func (m *QueryAppliedPlanResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAppliedPlanResponse) ProtoMessage()    {}
func (*QueryAppliedPlanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a334d07ad8374f0, []int{3}
}

func (m *QueryAppliedPlanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryAppliedPlanResponse.Unmarshal(m, b)
}
func (m *QueryAppliedPlanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryAppliedPlanResponse.Marshal(b, m, deterministic)
}
func (m *QueryAppliedPlanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAppliedPlanResponse.Merge(m, src)
}
func (m *QueryAppliedPlanResponse) XXX_Size() int {
	return xxx_messageInfo_QueryAppliedPlanResponse.Size(m)
}
func (m *QueryAppliedPlanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAppliedPlanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAppliedPlanResponse proto.InternalMessageInfo

func (m *QueryAppliedPlanResponse) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

// QueryUpgradedConsensusStateRequest is the request type for the Query/UpgradedConsensusState
// RPC method.
//
// Deprecated: Do not use.
type QueryUpgradedConsensusStateRequest struct {
	// last height of the current chain must be sent in request
	// as this is the height under which next consensus state is stored
	LastHeight           int64    `protobuf:"varint,1,opt,name=last_height,json=lastHeight,proto3" json:"last_height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryUpgradedConsensusStateRequest) Reset()         { *m = QueryUpgradedConsensusStateRequest{} }
func (m *QueryUpgradedConsensusStateRequest) String() string { return proto.CompactTextString(m) }
func (*QueryUpgradedConsensusStateRequest) ProtoMessage()    {}
func (*QueryUpgradedConsensusStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a334d07ad8374f0, []int{4}
}

func (m *QueryUpgradedConsensusStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryUpgradedConsensusStateRequest.Unmarshal(m, b)
}
func (m *QueryUpgradedConsensusStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryUpgradedConsensusStateRequest.Marshal(b, m, deterministic)
}
func (m *QueryUpgradedConsensusStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUpgradedConsensusStateRequest.Merge(m, src)
}
func (m *QueryUpgradedConsensusStateRequest) XXX_Size() int {
	return xxx_messageInfo_QueryUpgradedConsensusStateRequest.Size(m)
}
func (m *QueryUpgradedConsensusStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUpgradedConsensusStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUpgradedConsensusStateRequest proto.InternalMessageInfo

func (m *QueryUpgradedConsensusStateRequest) GetLastHeight() int64 {
	if m != nil {
		return m.LastHeight
	}
	return 0
}

// QueryUpgradedConsensusStateResponse is the response type for the Query/UpgradedConsensusState
// RPC method.
//
// Deprecated: Do not use.
type QueryUpgradedConsensusStateResponse struct {
	// Since: cosmos-sdk 0.43
	UpgradedConsensusState []byte   `protobuf:"bytes,2,opt,name=upgraded_consensus_state,json=upgradedConsensusState,proto3" json:"upgraded_consensus_state,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *QueryUpgradedConsensusStateResponse) Reset()         { *m = QueryUpgradedConsensusStateResponse{} }
func (m *QueryUpgradedConsensusStateResponse) String() string { return proto.CompactTextString(m) }
func (*QueryUpgradedConsensusStateResponse) ProtoMessage()    {}
func (*QueryUpgradedConsensusStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a334d07ad8374f0, []int{5}
}

func (m *QueryUpgradedConsensusStateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryUpgradedConsensusStateResponse.Unmarshal(m, b)
}
func (m *QueryUpgradedConsensusStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryUpgradedConsensusStateResponse.Marshal(b, m, deterministic)
}
func (m *QueryUpgradedConsensusStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUpgradedConsensusStateResponse.Merge(m, src)
}
func (m *QueryUpgradedConsensusStateResponse) XXX_Size() int {
	return xxx_messageInfo_QueryUpgradedConsensusStateResponse.Size(m)
}
func (m *QueryUpgradedConsensusStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUpgradedConsensusStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUpgradedConsensusStateResponse proto.InternalMessageInfo

func (m *QueryUpgradedConsensusStateResponse) GetUpgradedConsensusState() []byte {
	if m != nil {
		return m.UpgradedConsensusState
	}
	return nil
}

// QueryModuleVersionsRequest is the request type for the Query/ModuleVersions
// RPC method.
//
// Since: cosmos-sdk 0.43
type QueryModuleVersionsRequest struct {
	// module_name is a field to query a specific module
	// consensus version from state. Leaving this empty will
	// fetch the full list of module versions from state
	ModuleName           string   `protobuf:"bytes,1,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryModuleVersionsRequest) Reset()         { *m = QueryModuleVersionsRequest{} }
func (m *QueryModuleVersionsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryModuleVersionsRequest) ProtoMessage()    {}
func (*QueryModuleVersionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a334d07ad8374f0, []int{6}
}

func (m *QueryModuleVersionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryModuleVersionsRequest.Unmarshal(m, b)
}
func (m *QueryModuleVersionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryModuleVersionsRequest.Marshal(b, m, deterministic)
}
func (m *QueryModuleVersionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryModuleVersionsRequest.Merge(m, src)
}
func (m *QueryModuleVersionsRequest) XXX_Size() int {
	return xxx_messageInfo_QueryModuleVersionsRequest.Size(m)
}
func (m *QueryModuleVersionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryModuleVersionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryModuleVersionsRequest proto.InternalMessageInfo

func (m *QueryModuleVersionsRequest) GetModuleName() string {
	if m != nil {
		return m.ModuleName
	}
	return ""
}

// QueryModuleVersionsResponse is the response type for the Query/ModuleVersions
// RPC method.
//
// Since: cosmos-sdk 0.43
type QueryModuleVersionsResponse struct {
	// module_versions is a list of module names with their consensus versions.
	ModuleVersions       []*ModuleVersion `protobuf:"bytes,1,rep,name=module_versions,json=moduleVersions,proto3" json:"module_versions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *QueryModuleVersionsResponse) Reset()         { *m = QueryModuleVersionsResponse{} }
func (m *QueryModuleVersionsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryModuleVersionsResponse) ProtoMessage()    {}
func (*QueryModuleVersionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a334d07ad8374f0, []int{7}
}

func (m *QueryModuleVersionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryModuleVersionsResponse.Unmarshal(m, b)
}
func (m *QueryModuleVersionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryModuleVersionsResponse.Marshal(b, m, deterministic)
}
func (m *QueryModuleVersionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryModuleVersionsResponse.Merge(m, src)
}
func (m *QueryModuleVersionsResponse) XXX_Size() int {
	return xxx_messageInfo_QueryModuleVersionsResponse.Size(m)
}
func (m *QueryModuleVersionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryModuleVersionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryModuleVersionsResponse proto.InternalMessageInfo

func (m *QueryModuleVersionsResponse) GetModuleVersions() []*ModuleVersion {
	if m != nil {
		return m.ModuleVersions
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryCurrentPlanRequest)(nil), "cosmos.upgrade.v1beta1.QueryCurrentPlanRequest")
	proto.RegisterType((*QueryCurrentPlanResponse)(nil), "cosmos.upgrade.v1beta1.QueryCurrentPlanResponse")
	proto.RegisterType((*QueryAppliedPlanRequest)(nil), "cosmos.upgrade.v1beta1.QueryAppliedPlanRequest")
	proto.RegisterType((*QueryAppliedPlanResponse)(nil), "cosmos.upgrade.v1beta1.QueryAppliedPlanResponse")
	proto.RegisterType((*QueryUpgradedConsensusStateRequest)(nil), "cosmos.upgrade.v1beta1.QueryUpgradedConsensusStateRequest")
	proto.RegisterType((*QueryUpgradedConsensusStateResponse)(nil), "cosmos.upgrade.v1beta1.QueryUpgradedConsensusStateResponse")
	proto.RegisterType((*QueryModuleVersionsRequest)(nil), "cosmos.upgrade.v1beta1.QueryModuleVersionsRequest")
	proto.RegisterType((*QueryModuleVersionsResponse)(nil), "cosmos.upgrade.v1beta1.QueryModuleVersionsResponse")
}

func init() { proto.RegisterFile("cosmos/upgrade/v1beta1/query.proto", fileDescriptor_4a334d07ad8374f0) }

var fileDescriptor_4a334d07ad8374f0 = []byte{
	// 558 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcf, 0x6f, 0xd3, 0x30,
	0x18, 0x95, 0xbb, 0x1f, 0x82, 0xaf, 0x68, 0x20, 0x1f, 0x4a, 0x16, 0x26, 0x51, 0x99, 0x01, 0x45,
	0xac, 0xf1, 0xd6, 0x5e, 0xd0, 0x10, 0x08, 0xd8, 0x85, 0x21, 0x98, 0xa0, 0x08, 0x0e, 0x5c, 0x2a,
	0xb7, 0x31, 0x6d, 0x44, 0x62, 0x67, 0xb1, 0x33, 0x31, 0x4d, 0xbb, 0x70, 0xe2, 0xce, 0x9d, 0x1b,
	0x17, 0xfe, 0x1d, 0xae, 0x3b, 0xf2, 0x87, 0xa0, 0x38, 0x2e, 0x4a, 0x69, 0x92, 0x01, 0xa7, 0x36,
	0xfe, 0xde, 0xfb, 0xde, 0xfb, 0xec, 0x67, 0x03, 0x19, 0x4b, 0x15, 0x49, 0x45, 0xd3, 0x78, 0x92,
	0x30, 0x9f, 0xd3, 0xa3, 0x9d, 0x11, 0xd7, 0x6c, 0x87, 0x1e, 0xa6, 0x3c, 0x39, 0xf6, 0xe2, 0x44,
	0x6a, 0x89, 0x5b, 0x39, 0xc6, 0xb3, 0x18, 0xcf, 0x62, 0xdc, 0xf5, 0x89, 0x94, 0x93, 0x90, 0x53,
	0x83, 0x1a, 0xa5, 0xef, 0x29, 0x13, 0x96, 0xe2, 0x6e, 0xd8, 0x12, 0x8b, 0x03, 0xca, 0x84, 0x90,
	0x9a, 0xe9, 0x40, 0x0a, 0x65, 0xab, 0x9b, 0x15, 0xa2, 0x33, 0x01, 0x83, 0x22, 0xeb, 0x70, 0xf5,
	0x55, 0xe6, 0x62, 0x2f, 0x4d, 0x12, 0x2e, 0xf4, 0xcb, 0x90, 0x89, 0x01, 0x3f, 0x4c, 0xb9, 0xd2,
	0xe4, 0x39, 0x38, 0x8b, 0x25, 0x15, 0x4b, 0xa1, 0x38, 0xde, 0x86, 0xe5, 0x38, 0x64, 0xc2, 0x41,
	0x6d, 0xd4, 0x69, 0xf6, 0x36, 0xbc, 0x72, 0xf3, 0x9e, 0xe1, 0x18, 0x24, 0xe9, 0x5a, 0xa1, 0xc7,
	0x71, 0x1c, 0x06, 0xdc, 0x2f, 0x08, 0x61, 0x0c, 0xcb, 0x82, 0x45, 0xdc, 0x34, 0xbb, 0x38, 0x30,
	0xff, 0x49, 0xcf, 0x8a, 0xcf, 0xc1, 0xad, 0x78, 0x0b, 0x56, 0xa7, 0x3c, 0x98, 0x4c, 0xb5, 0x61,
	0x2c, 0x0d, 0xec, 0x17, 0xd9, 0x07, 0x62, 0x38, 0x6f, 0x72, 0x17, 0xfe, 0x5e, 0x86, 0x16, 0x2a,
	0x55, 0xaf, 0x35, 0xd3, 0x7c, 0xa6, 0x76, 0x1d, 0x9a, 0x21, 0x53, 0x7a, 0x38, 0xd7, 0x02, 0xb2,
	0xa5, 0xa7, 0x66, 0x65, 0xb7, 0xe1, 0x20, 0x12, 0xc0, 0x8d, 0xda, 0x56, 0xd6, 0xc9, 0x3d, 0x70,
	0xec, 0xc8, 0xfe, 0x70, 0x3c, 0x83, 0x0c, 0x55, 0x86, 0x71, 0x1a, 0x6d, 0xd4, 0xb9, 0x34, 0x68,
	0xa5, 0xa5, 0x1d, 0x32, 0x91, 0x67, 0xcb, 0x17, 0xd0, 0x95, 0x06, 0x79, 0x00, 0xae, 0x91, 0x7a,
	0x21, 0xfd, 0x34, 0xe4, 0x6f, 0x79, 0xa2, 0xb2, 0x43, 0x2c, 0xb8, 0x8d, 0x4c, 0x61, 0x58, 0xd8,
	0x22, 0xc8, 0x97, 0x0e, 0xb2, 0x8d, 0x8a, 0xe0, 0x5a, 0x29, 0xdd, 0x3a, 0x3c, 0x80, 0xcb, 0x96,
	0x7f, 0x64, 0x4b, 0x0e, 0x6a, 0x2f, 0x75, 0x9a, 0xbd, 0x9b, 0x55, 0x67, 0x36, 0xd7, 0x68, 0xb0,
	0x16, 0xcd, 0xf5, 0xed, 0x9d, 0xad, 0xc0, 0x8a, 0xd1, 0xc3, 0x5f, 0x11, 0x34, 0x0b, 0xd1, 0xc0,
	0xb4, 0xaa, 0x61, 0x45, 0xbe, 0xdc, 0xed, 0xbf, 0x27, 0xe4, 0xc3, 0x90, 0xad, 0x4f, 0x3f, 0x7e,
	0x7e, 0x69, 0xdc, 0xc2, 0x9b, 0xb4, 0x22, 0xdb, 0xe3, 0x9c, 0x34, 0xcc, 0x12, 0x87, 0xbf, 0x21,
	0x68, 0x16, 0xe2, 0x73, 0x8e, 0xc1, 0xc5, 0x5c, 0x9e, 0x63, 0xb0, 0x24, 0x99, 0xa4, 0x6f, 0x0c,
	0x76, 0xf1, 0xdd, 0x2a, 0x83, 0x2c, 0x27, 0x19, 0x83, 0xf4, 0x24, 0x3b, 0xd2, 0x53, 0x7c, 0x86,
	0xa0, 0x55, 0x9e, 0x33, 0xbc, 0x5b, 0xeb, 0xa0, 0x36, 0xe7, 0xee, 0xfd, 0xff, 0xe2, 0xda, 0x41,
	0xf6, 0xcd, 0x20, 0x8f, 0xf0, 0x43, 0x5a, 0xff, 0x8a, 0x2c, 0xc4, 0x9e, 0x9e, 0x14, 0x2e, 0xd7,
	0xe9, 0xe7, 0x06, 0xc2, 0xdf, 0x11, 0xac, 0xcd, 0x87, 0x13, 0xf7, 0x6a, 0xad, 0x95, 0x5e, 0x04,
	0xb7, 0xff, 0x4f, 0x1c, 0x3b, 0x06, 0x35, 0x63, 0xdc, 0xc1, 0xb7, 0xab, 0xc6, 0xf8, 0xe3, 0x6e,
	0x3c, 0xf1, 0xde, 0x6d, 0x4d, 0x02, 0x3d, 0x4d, 0x47, 0xde, 0x58, 0x46, 0x33, 0x52, 0xfe, 0xd3,
	0x55, 0xfe, 0x07, 0xfa, 0xf1, 0x77, 0x07, 0x7d, 0x1c, 0x73, 0x35, 0x5a, 0x35, 0xaf, 0x68, 0xff,
	0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3d, 0xb3, 0x17, 0x48, 0xe2, 0x05, 0x00, 0x00,
}
