// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cosmos/authz/v1beta1/query.proto

package authz

import (
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// QueryGrantsRequest is the request type for the Query/Grants RPC method.
type QueryGrantsRequest struct {
	Granter string `protobuf:"bytes,1,opt,name=granter,proto3" json:"granter,omitempty"`
	Grantee string `protobuf:"bytes,2,opt,name=grantee,proto3" json:"grantee,omitempty"`
	// Optional, msg_type_url, when set, will query only grants matching given msg type.
	MsgTypeUrl string `protobuf:"bytes,3,opt,name=msg_type_url,json=msgTypeUrl,proto3" json:"msg_type_url,omitempty"`
	// pagination defines an pagination for the request.
	Pagination           *query.PageRequest `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *QueryGrantsRequest) Reset()         { *m = QueryGrantsRequest{} }
func (m *QueryGrantsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGrantsRequest) ProtoMessage()    {}
func (*QueryGrantsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_376d714ffdeb1545, []int{0}
}

func (m *QueryGrantsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryGrantsRequest.Unmarshal(m, b)
}
func (m *QueryGrantsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryGrantsRequest.Marshal(b, m, deterministic)
}
func (m *QueryGrantsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGrantsRequest.Merge(m, src)
}
func (m *QueryGrantsRequest) XXX_Size() int {
	return xxx_messageInfo_QueryGrantsRequest.Size(m)
}
func (m *QueryGrantsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGrantsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGrantsRequest proto.InternalMessageInfo

func (m *QueryGrantsRequest) GetGranter() string {
	if m != nil {
		return m.Granter
	}
	return ""
}

func (m *QueryGrantsRequest) GetGrantee() string {
	if m != nil {
		return m.Grantee
	}
	return ""
}

func (m *QueryGrantsRequest) GetMsgTypeUrl() string {
	if m != nil {
		return m.MsgTypeUrl
	}
	return ""
}

func (m *QueryGrantsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryGrantsResponse is the response type for the Query/Authorizations RPC method.
type QueryGrantsResponse struct {
	// authorizations is a list of grants granted for grantee by granter.
	Grants []*Grant `protobuf:"bytes,1,rep,name=grants,proto3" json:"grants,omitempty"`
	// pagination defines an pagination for the response.
	Pagination           *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *QueryGrantsResponse) Reset()         { *m = QueryGrantsResponse{} }
func (m *QueryGrantsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGrantsResponse) ProtoMessage()    {}
func (*QueryGrantsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_376d714ffdeb1545, []int{1}
}

func (m *QueryGrantsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryGrantsResponse.Unmarshal(m, b)
}
func (m *QueryGrantsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryGrantsResponse.Marshal(b, m, deterministic)
}
func (m *QueryGrantsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGrantsResponse.Merge(m, src)
}
func (m *QueryGrantsResponse) XXX_Size() int {
	return xxx_messageInfo_QueryGrantsResponse.Size(m)
}
func (m *QueryGrantsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGrantsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGrantsResponse proto.InternalMessageInfo

func (m *QueryGrantsResponse) GetGrants() []*Grant {
	if m != nil {
		return m.Grants
	}
	return nil
}

func (m *QueryGrantsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGrantsRequest)(nil), "cosmos.authz.v1beta1.QueryGrantsRequest")
	proto.RegisterType((*QueryGrantsResponse)(nil), "cosmos.authz.v1beta1.QueryGrantsResponse")
}

func init() { proto.RegisterFile("cosmos/authz/v1beta1/query.proto", fileDescriptor_376d714ffdeb1545) }

var fileDescriptor_376d714ffdeb1545 = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x4e, 0xc2, 0x30,
	0x18, 0xc7, 0x53, 0x50, 0x8c, 0xc5, 0x53, 0xf5, 0xb0, 0x20, 0x31, 0x0b, 0x21, 0x38, 0x4d, 0x6c,
	0x03, 0xbc, 0x81, 0x07, 0xb9, 0xea, 0xa2, 0x17, 0x2f, 0xa4, 0xc3, 0x2f, 0x65, 0x91, 0xad, 0x63,
	0xed, 0x8c, 0x78, 0xd4, 0xb3, 0x27, 0xde, 0xc4, 0x57, 0xf1, 0x15, 0x7c, 0x10, 0x43, 0x5b, 0x64,
	0xc4, 0x25, 0x7a, 0x5a, 0xb6, 0xef, 0xf7, 0x7d, 0xdf, 0xaf, 0xff, 0x15, 0xfb, 0x13, 0xa9, 0x12,
	0xa9, 0x18, 0x2f, 0xf4, 0xf4, 0x85, 0x3d, 0xf5, 0x23, 0xd0, 0xbc, 0xcf, 0xe6, 0x05, 0xe4, 0x0b,
	0x9a, 0xe5, 0x52, 0x4b, 0x72, 0x64, 0x09, 0x6a, 0x08, 0xea, 0x88, 0x56, 0x5b, 0x48, 0x29, 0x66,
	0xc0, 0x78, 0x16, 0x33, 0x9e, 0xa6, 0x52, 0x73, 0x1d, 0xcb, 0x54, 0xd9, 0x9e, 0xd6, 0xb9, 0x9b,
	0x1a, 0x71, 0x05, 0x76, 0xd8, 0xcf, 0xe8, 0x8c, 0x8b, 0x38, 0x35, 0xb0, 0x63, 0xab, 0x0d, 0xec,
	0x36, 0x43, 0x74, 0x3e, 0x10, 0x26, 0x37, 0xab, 0x21, 0xa3, 0x9c, 0xa7, 0x5a, 0x85, 0x30, 0x2f,
	0x40, 0x69, 0xe2, 0xe1, 0x3d, 0xb1, 0xfa, 0x00, 0xb9, 0x87, 0x7c, 0x14, 0xec, 0x87, 0xeb, 0xd7,
	0x4d, 0x05, 0xbc, 0x5a, 0xb9, 0x02, 0xc4, 0xc7, 0x07, 0x89, 0x12, 0x63, 0xbd, 0xc8, 0x60, 0x5c,
	0xe4, 0x33, 0xaf, 0x6e, 0xca, 0x38, 0x51, 0xe2, 0x76, 0x91, 0xc1, 0x5d, 0x3e, 0x23, 0x57, 0x18,
	0x6f, 0x14, 0xbd, 0x1d, 0x1f, 0x05, 0xcd, 0x41, 0x8f, 0xba, 0x0c, 0x56, 0xe7, 0xa1, 0x36, 0x1c,
	0x27, 0x4a, 0xaf, 0xb9, 0x00, 0x67, 0x14, 0x96, 0x3a, 0x3b, 0x4b, 0x84, 0x0f, 0xb7, 0xa4, 0x55,
	0x26, 0x53, 0x05, 0x64, 0x88, 0x1b, 0x46, 0x46, 0x79, 0xc8, 0xaf, 0x07, 0xcd, 0xc1, 0x31, 0xad,
	0xca, 0x97, 0x9a, 0xae, 0xd0, 0xa1, 0x64, 0xb4, 0x25, 0x55, 0x33, 0x52, 0xa7, 0x7f, 0x4a, 0xd9,
	0x8d, 0x65, 0xab, 0xc1, 0x3b, 0xc2, 0xbb, 0xc6, 0x8a, 0xbc, 0x21, 0xdc, 0xb0, 0x6a, 0x24, 0xa8,
	0x56, 0xf8, 0x1d, 0x79, 0xeb, 0xec, 0x1f, 0xa4, 0xdd, 0xda, 0xe9, 0xbe, 0x7e, 0x7e, 0x2d, 0x6b,
	0x27, 0xa4, 0xcd, 0x2a, 0xff, 0xaf, 0x3d, 0xd8, 0x65, 0xef, 0xbe, 0x2b, 0x62, 0x3d, 0x2d, 0x22,
	0x3a, 0x91, 0xc9, 0x9a, 0xb4, 0x8f, 0x0b, 0xf5, 0xf0, 0xc8, 0x9e, 0x6d, 0x5b, 0xd4, 0x30, 0x37,
	0x61, 0xf8, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x97, 0xcf, 0x0b, 0x67, 0xaf, 0x02, 0x00, 0x00,
}
