// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kira/slashing/v1beta1/query.proto

package types

import (
	fmt "fmt"
	types "github.com/KiraCore/sekai/x/staking/types"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is the request type for the Query/Params RPC method
type QueryParamsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e241c76ab2d5716, []int{0}
}

func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryParamsRequest.Unmarshal(m, b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return xxx_messageInfo_QueryParamsRequest.Size(m)
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is the response type for the Query/Params RPC method
type QueryParamsResponse struct {
	Params               *Params  `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e241c76ab2d5716, []int{1}
}

func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryParamsResponse.Unmarshal(m, b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return xxx_messageInfo_QueryParamsResponse.Size(m)
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() *Params {
	if m != nil {
		return m.Params
	}
	return nil
}

type IdentityRecord struct {
	Id                   uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Infos                map[string]string      `protobuf:"bytes,3,rep,name=infos,proto3" json:"infos,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Date                 *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	Verifiers            []string               `protobuf:"bytes,5,rep,name=verifiers,proto3" json:"verifiers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *IdentityRecord) Reset()         { *m = IdentityRecord{} }
func (m *IdentityRecord) String() string { return proto.CompactTextString(m) }
func (*IdentityRecord) ProtoMessage()    {}
func (*IdentityRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e241c76ab2d5716, []int{2}
}

func (m *IdentityRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdentityRecord.Unmarshal(m, b)
}
func (m *IdentityRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdentityRecord.Marshal(b, m, deterministic)
}
func (m *IdentityRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdentityRecord.Merge(m, src)
}
func (m *IdentityRecord) XXX_Size() int {
	return xxx_messageInfo_IdentityRecord.Size(m)
}
func (m *IdentityRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_IdentityRecord.DiscardUnknown(m)
}

var xxx_messageInfo_IdentityRecord proto.InternalMessageInfo

func (m *IdentityRecord) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *IdentityRecord) GetInfos() map[string]string {
	if m != nil {
		return m.Infos
	}
	return nil
}

func (m *IdentityRecord) GetDate() *timestamppb.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *IdentityRecord) GetVerifiers() []string {
	if m != nil {
		return m.Verifiers
	}
	return nil
}

// QuerySigningInfoRequest is the request type for the Query/SigningInfo RPC
// method
type QuerySigningInfoRequest struct {
	// cons_address is the address to query signing info of
	ConsAddress string `protobuf:"bytes,1,opt,name=cons_address,json=consAddress,proto3" json:"cons_address,omitempty"`
	// include_validators is the flag to include validators info while querying signing info
	IncludeValidator     bool     `protobuf:"varint,2,opt,name=include_validator,json=includeValidator,proto3" json:"include_validator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuerySigningInfoRequest) Reset()         { *m = QuerySigningInfoRequest{} }
func (m *QuerySigningInfoRequest) String() string { return proto.CompactTextString(m) }
func (*QuerySigningInfoRequest) ProtoMessage()    {}
func (*QuerySigningInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e241c76ab2d5716, []int{3}
}

func (m *QuerySigningInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuerySigningInfoRequest.Unmarshal(m, b)
}
func (m *QuerySigningInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuerySigningInfoRequest.Marshal(b, m, deterministic)
}
func (m *QuerySigningInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySigningInfoRequest.Merge(m, src)
}
func (m *QuerySigningInfoRequest) XXX_Size() int {
	return xxx_messageInfo_QuerySigningInfoRequest.Size(m)
}
func (m *QuerySigningInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySigningInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySigningInfoRequest proto.InternalMessageInfo

func (m *QuerySigningInfoRequest) GetConsAddress() string {
	if m != nil {
		return m.ConsAddress
	}
	return ""
}

func (m *QuerySigningInfoRequest) GetIncludeValidator() bool {
	if m != nil {
		return m.IncludeValidator
	}
	return false
}

// QuerySigningInfoResponse is the response type for the Query/SigningInfo RPC
// method
type QuerySigningInfoResponse struct {
	// val_signing_info is the signing info of requested val cons address
	ValSigningInfo *ValidatorSigningInfo `protobuf:"bytes,1,opt,name=val_signing_info,json=valSigningInfo,proto3" json:"val_signing_info,omitempty"`
	// validator is the main info saved on native validator object
	Validator            *types.QueryValidator `protobuf:"bytes,2,opt,name=validator,proto3" json:"validator,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *QuerySigningInfoResponse) Reset()         { *m = QuerySigningInfoResponse{} }
func (m *QuerySigningInfoResponse) String() string { return proto.CompactTextString(m) }
func (*QuerySigningInfoResponse) ProtoMessage()    {}
func (*QuerySigningInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e241c76ab2d5716, []int{4}
}

func (m *QuerySigningInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuerySigningInfoResponse.Unmarshal(m, b)
}
func (m *QuerySigningInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuerySigningInfoResponse.Marshal(b, m, deterministic)
}
func (m *QuerySigningInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySigningInfoResponse.Merge(m, src)
}
func (m *QuerySigningInfoResponse) XXX_Size() int {
	return xxx_messageInfo_QuerySigningInfoResponse.Size(m)
}
func (m *QuerySigningInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySigningInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySigningInfoResponse proto.InternalMessageInfo

func (m *QuerySigningInfoResponse) GetValSigningInfo() *ValidatorSigningInfo {
	if m != nil {
		return m.ValSigningInfo
	}
	return nil
}

func (m *QuerySigningInfoResponse) GetValidator() *types.QueryValidator {
	if m != nil {
		return m.Validator
	}
	return nil
}

// QuerySigningInfosRequest is the request type for the Query/SigningInfos RPC
// method
type QuerySigningInfosRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// include_validators is the flag to include validators info while querying signing info
	IncludeValidator     bool     `protobuf:"varint,2,opt,name=include_validator,json=includeValidator,proto3" json:"include_validator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuerySigningInfosRequest) Reset()         { *m = QuerySigningInfosRequest{} }
func (m *QuerySigningInfosRequest) String() string { return proto.CompactTextString(m) }
func (*QuerySigningInfosRequest) ProtoMessage()    {}
func (*QuerySigningInfosRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e241c76ab2d5716, []int{5}
}

func (m *QuerySigningInfosRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuerySigningInfosRequest.Unmarshal(m, b)
}
func (m *QuerySigningInfosRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuerySigningInfosRequest.Marshal(b, m, deterministic)
}
func (m *QuerySigningInfosRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySigningInfosRequest.Merge(m, src)
}
func (m *QuerySigningInfosRequest) XXX_Size() int {
	return xxx_messageInfo_QuerySigningInfosRequest.Size(m)
}
func (m *QuerySigningInfosRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySigningInfosRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySigningInfosRequest proto.InternalMessageInfo

func (m *QuerySigningInfosRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func (m *QuerySigningInfosRequest) GetIncludeValidator() bool {
	if m != nil {
		return m.IncludeValidator
	}
	return false
}

// QuerySigningInfosResponse is the response type for the Query/SigningInfos RPC
// method
type QuerySigningInfosResponse struct {
	// info is the signing info of all validators
	Info []*ValidatorSigningInfo `protobuf:"bytes,1,rep,name=info,proto3" json:"info,omitempty"`
	// validator is the main info saved on native validator object
	Validators           []*types.QueryValidator `protobuf:"bytes,2,rep,name=validators,proto3" json:"validators,omitempty"`
	Pagination           *query.PageResponse     `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *QuerySigningInfosResponse) Reset()         { *m = QuerySigningInfosResponse{} }
func (m *QuerySigningInfosResponse) String() string { return proto.CompactTextString(m) }
func (*QuerySigningInfosResponse) ProtoMessage()    {}
func (*QuerySigningInfosResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e241c76ab2d5716, []int{6}
}

func (m *QuerySigningInfosResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuerySigningInfosResponse.Unmarshal(m, b)
}
func (m *QuerySigningInfosResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuerySigningInfosResponse.Marshal(b, m, deterministic)
}
func (m *QuerySigningInfosResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySigningInfosResponse.Merge(m, src)
}
func (m *QuerySigningInfosResponse) XXX_Size() int {
	return xxx_messageInfo_QuerySigningInfosResponse.Size(m)
}
func (m *QuerySigningInfosResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySigningInfosResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySigningInfosResponse proto.InternalMessageInfo

func (m *QuerySigningInfosResponse) GetInfo() []*ValidatorSigningInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *QuerySigningInfosResponse) GetValidators() []*types.QueryValidator {
	if m != nil {
		return m.Validators
	}
	return nil
}

func (m *QuerySigningInfosResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "kira.slashing.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "kira.slashing.QueryParamsResponse")
	proto.RegisterType((*IdentityRecord)(nil), "kira.slashing.IdentityRecord")
	proto.RegisterMapType((map[string]string)(nil), "kira.slashing.IdentityRecord.InfosEntry")
	proto.RegisterType((*QuerySigningInfoRequest)(nil), "kira.slashing.QuerySigningInfoRequest")
	proto.RegisterType((*QuerySigningInfoResponse)(nil), "kira.slashing.QuerySigningInfoResponse")
	proto.RegisterType((*QuerySigningInfosRequest)(nil), "kira.slashing.QuerySigningInfosRequest")
	proto.RegisterType((*QuerySigningInfosResponse)(nil), "kira.slashing.QuerySigningInfosResponse")
}

func init() { proto.RegisterFile("kira/slashing/v1beta1/query.proto", fileDescriptor_7e241c76ab2d5716) }

var fileDescriptor_7e241c76ab2d5716 = []byte{
	// 770 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcd, 0x6e, 0xd3, 0x4a,
	0x14, 0xbe, 0xce, 0x4f, 0xd5, 0x9c, 0xf4, 0x56, 0xbd, 0x73, 0x7b, 0x75, 0x4d, 0x54, 0x94, 0xd6,
	0x94, 0x36, 0x2a, 0xc5, 0x56, 0x53, 0x2a, 0x85, 0x22, 0x10, 0x04, 0xb1, 0x28, 0x6c, 0x8a, 0x8b,
	0x58, 0xb0, 0x89, 0x26, 0xf1, 0xd4, 0x1d, 0x25, 0xf1, 0xa4, 0x9e, 0x89, 0x45, 0x84, 0x90, 0x50,
	0x5f, 0x00, 0x24, 0x96, 0x6c, 0x90, 0x78, 0x00, 0xc4, 0x5b, 0x20, 0xb6, 0xec, 0xcb, 0x86, 0x05,
	0x8f, 0x80, 0xba, 0x42, 0x9e, 0x99, 0x24, 0x4e, 0x1b, 0x48, 0xbb, 0x4a, 0x7c, 0xe6, 0x3b, 0xdf,
	0xf9, 0xe6, 0x3b, 0x67, 0x0e, 0x2c, 0x35, 0x69, 0x88, 0x1d, 0xde, 0xc2, 0xfc, 0x80, 0x06, 0xbe,
	0x13, 0x6d, 0xd4, 0x89, 0xc0, 0x1b, 0xce, 0x61, 0x97, 0x84, 0x3d, 0xbb, 0x13, 0x32, 0xc1, 0xd0,
	0xdf, 0x31, 0xc4, 0xee, 0x43, 0x0a, 0xf3, 0x3e, 0xf3, 0x99, 0x3c, 0x71, 0xe2, 0x7f, 0x0a, 0x54,
	0x58, 0xf0, 0x19, 0xf3, 0x5b, 0xc4, 0xc1, 0x1d, 0xea, 0xe0, 0x20, 0x60, 0x02, 0x0b, 0xca, 0x02,
	0xae, 0x4f, 0x8b, 0xfa, 0x54, 0x7e, 0xd5, 0xbb, 0xfb, 0x8e, 0xa0, 0x6d, 0xc2, 0x05, 0x6e, 0x77,
	0x34, 0x60, 0xad, 0xc1, 0x78, 0x9b, 0x71, 0xa7, 0x8e, 0x39, 0x51, 0xc5, 0x07, 0x52, 0x3a, 0xd8,
	0xa7, 0x81, 0x64, 0xd3, 0xd8, 0xe5, 0xf1, 0x92, 0xfb, 0x01, 0x8d, 0x32, 0x15, 0x4a, 0xe0, 0x66,
	0x0c, 0x4a, 0xdc, 0xc7, 0x9a, 0x07, 0xf4, 0x38, 0xfe, 0xdc, 0xc5, 0x21, 0x6e, 0x73, 0x97, 0x1c,
	0x76, 0x09, 0x17, 0xd6, 0x43, 0xf8, 0x77, 0x24, 0xca, 0x3b, 0x2c, 0xe0, 0x04, 0x6d, 0xc2, 0x54,
	0x47, 0x46, 0x4c, 0x63, 0xd1, 0x28, 0xe5, 0xcb, 0xff, 0xd9, 0x23, 0x6e, 0xd8, 0x0a, 0x5e, 0xcd,
	0x7c, 0x3e, 0x2e, 0xfe, 0xe5, 0x6a, 0xa8, 0xf5, 0xd3, 0x80, 0xd9, 0x1d, 0x8f, 0x04, 0x82, 0x8a,
	0x9e, 0x4b, 0x1a, 0x2c, 0xf4, 0xd0, 0x2c, 0xa4, 0xa8, 0x27, 0x39, 0x32, 0x6e, 0x8a, 0x7a, 0xe8,
	0x0e, 0x64, 0x69, 0xb0, 0xcf, 0xb8, 0x99, 0x5e, 0x4c, 0x97, 0xf2, 0xe5, 0xd2, 0x29, 0xda, 0xd1,
	0x6c, 0x7b, 0x27, 0x86, 0x3e, 0x08, 0x44, 0xd8, 0x73, 0x55, 0x1a, 0xaa, 0x40, 0xc6, 0xc3, 0x82,
	0x98, 0x19, 0xa9, 0xaa, 0x60, 0x2b, 0x83, 0xed, 0xbe, 0xc1, 0xf6, 0x93, 0xbe, 0xc1, 0xd5, 0xe9,
	0x58, 0xda, 0x9b, 0x6f, 0x45, 0xc3, 0x95, 0x19, 0x68, 0x01, 0x72, 0x11, 0x09, 0xe9, 0x3e, 0x25,
	0x21, 0x37, 0xb3, 0x8b, 0xe9, 0x52, 0xce, 0x1d, 0x06, 0x0a, 0x15, 0x80, 0x61, 0x31, 0x34, 0x07,
	0xe9, 0x26, 0xe9, 0x49, 0xd9, 0x39, 0x37, 0xfe, 0x8b, 0xe6, 0x21, 0x1b, 0xe1, 0x56, 0x97, 0x98,
	0x29, 0x19, 0x53, 0x1f, 0xdb, 0xa9, 0x8a, 0xb1, 0x9d, 0xf9, 0xf1, 0xbe, 0x68, 0x58, 0x14, 0xfe,
	0x97, 0x36, 0xee, 0x51, 0x3f, 0xa0, 0x81, 0x1f, 0x73, 0x69, 0x87, 0xd1, 0x12, 0xcc, 0x34, 0x58,
	0xc0, 0x6b, 0xd8, 0xf3, 0x42, 0xc2, 0xb9, 0x66, 0xcd, 0xc7, 0xb1, 0x7b, 0x2a, 0x84, 0xae, 0xc1,
	0x3f, 0x34, 0x68, 0xb4, 0xba, 0x1e, 0xa9, 0x45, 0xb8, 0x45, 0x3d, 0x2c, 0x58, 0x28, 0x2b, 0x4d,
	0xbb, 0x73, 0xfa, 0xe0, 0x69, 0x3f, 0x6e, 0x7d, 0x32, 0xc0, 0x3c, 0x5b, 0x4b, 0xf7, 0x6d, 0x0f,
	0xe6, 0x22, 0xdc, 0xaa, 0x71, 0x75, 0x54, 0x8b, 0x4d, 0xd3, 0x1d, 0xbc, 0x72, 0xca, 0xea, 0x01,
	0x61, 0x82, 0x46, 0xf7, 0x73, 0x36, 0xc2, 0xad, 0x44, 0x14, 0xdd, 0x85, 0xdc, 0xa8, 0xac, 0x7c,
	0x79, 0x41, 0xb3, 0xa9, 0x39, 0xb3, 0xa5, 0x9e, 0x01, 0xa3, 0xa6, 0x19, 0x26, 0x59, 0x5f, 0xc6,
	0x68, 0xee, 0x8f, 0x20, 0x7a, 0x65, 0x00, 0x0c, 0xa7, 0x5d, 0xcb, 0x5d, 0xb1, 0xd5, 0xd3, 0xb0,
	0xe3, 0xa7, 0x61, 0xab, 0x39, 0xd6, 0x23, 0x6f, 0xef, 0x62, 0x9f, 0xe8, 0xe4, 0x6a, 0xe5, 0xe4,
	0xb8, 0x78, 0xc3, 0xa7, 0xe2, 0xa0, 0x5b, 0xb7, 0x1b, 0xac, 0xed, 0xe8, 0x07, 0xa5, 0x7e, 0xae,
	0x73, 0xaf, 0xe9, 0x88, 0x5e, 0x87, 0x70, 0xfd, 0x12, 0x12, 0x99, 0x6e, 0xa2, 0xe6, 0xc5, 0x1a,
	0xf0, 0x21, 0x05, 0x97, 0xc6, 0x5c, 0x46, 0x77, 0xe0, 0x36, 0x64, 0xb4, 0xeb, 0xe9, 0x8b, 0xb9,
	0x2e, 0xd3, 0x50, 0x15, 0x60, 0xa0, 0x80, 0x9b, 0x29, 0x49, 0x72, 0x1e, 0xb3, 0x13, 0x59, 0xe8,
	0x68, 0xd4, 0xd0, 0xb4, 0x34, 0x74, 0x75, 0xa2, 0xa1, 0xea, 0x02, 0xd5, 0x9b, 0x27, 0xc7, 0xc5,
	0xad, 0x0b, 0x3a, 0xaa, 0x52, 0x93, 0x96, 0x96, 0x3f, 0xa6, 0x21, 0x2b, 0x95, 0xa2, 0x08, 0xa6,
	0xd4, 0xba, 0x40, 0x4b, 0xa7, 0xdc, 0x38, 0xbb, 0x8f, 0x0a, 0xd6, 0x9f, 0x20, 0xaa, 0x8c, 0x75,
	0xf5, 0xe8, 0xeb, 0xf7, 0xb7, 0xa9, 0x22, 0xba, 0xec, 0x8c, 0x5f, 0x89, 0x6a, 0x1d, 0xa1, 0x77,
	0x06, 0xe4, 0x93, 0x63, 0xbc, 0x32, 0x8e, 0xfa, 0xec, 0x83, 0x2d, 0xac, 0x4e, 0xc4, 0x69, 0x1d,
	0xb7, 0xa4, 0x8e, 0x2d, 0xb4, 0xf9, 0x1b, 0x1d, 0xc9, 0x57, 0xc8, 0x9d, 0x17, 0xc9, 0x2d, 0xf0,
	0x12, 0xbd, 0x36, 0x60, 0x26, 0x39, 0x40, 0x68, 0x52, 0xd9, 0x81, 0x45, 0xa5, 0xc9, 0x40, 0x2d,
	0x70, 0x5d, 0x0a, 0x5c, 0x41, 0xcb, 0xe7, 0x11, 0x58, 0x5d, 0x7f, 0xb6, 0x96, 0x68, 0xfb, 0x23,
	0x1a, 0xe2, 0xfb, 0x2c, 0x24, 0x0e, 0x27, 0x4d, 0x4c, 0x9d, 0xe7, 0xc3, 0x6c, 0xd9, 0xfe, 0xfa,
	0x94, 0xdc, 0xb9, 0x9b, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x3f, 0xf7, 0xe2, 0x66, 0x4a, 0x07,
	0x00, 0x00,
}
