// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kira/slashing/v1beta1/tx.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// MsgActivate defines the Msg/Activate request type
type MsgActivate struct {
	ValidatorAddr        string   `protobuf:"bytes,1,opt,name=validator_addr,json=validatorAddr,proto3" json:"validator_addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgActivate) Reset()         { *m = MsgActivate{} }
func (m *MsgActivate) String() string { return proto.CompactTextString(m) }
func (*MsgActivate) ProtoMessage()    {}
func (*MsgActivate) Descriptor() ([]byte, []int) {
	return fileDescriptor_195ed35d11349041, []int{0}
}

func (m *MsgActivate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgActivate.Unmarshal(m, b)
}
func (m *MsgActivate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgActivate.Marshal(b, m, deterministic)
}
func (m *MsgActivate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgActivate.Merge(m, src)
}
func (m *MsgActivate) XXX_Size() int {
	return xxx_messageInfo_MsgActivate.Size(m)
}
func (m *MsgActivate) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgActivate.DiscardUnknown(m)
}

var xxx_messageInfo_MsgActivate proto.InternalMessageInfo

func (m *MsgActivate) GetValidatorAddr() string {
	if m != nil {
		return m.ValidatorAddr
	}
	return ""
}

// MsgActivateResponse defines the Msg/Activate response type
type MsgActivateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgActivateResponse) Reset()         { *m = MsgActivateResponse{} }
func (m *MsgActivateResponse) String() string { return proto.CompactTextString(m) }
func (*MsgActivateResponse) ProtoMessage()    {}
func (*MsgActivateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_195ed35d11349041, []int{1}
}

func (m *MsgActivateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgActivateResponse.Unmarshal(m, b)
}
func (m *MsgActivateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgActivateResponse.Marshal(b, m, deterministic)
}
func (m *MsgActivateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgActivateResponse.Merge(m, src)
}
func (m *MsgActivateResponse) XXX_Size() int {
	return xxx_messageInfo_MsgActivateResponse.Size(m)
}
func (m *MsgActivateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgActivateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgActivateResponse proto.InternalMessageInfo

// MsgPause defines the Msg/Pause request type
type MsgPause struct {
	ValidatorAddr        string   `protobuf:"bytes,1,opt,name=validator_addr,json=validatorAddr,proto3" json:"validator_addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgPause) Reset()         { *m = MsgPause{} }
func (m *MsgPause) String() string { return proto.CompactTextString(m) }
func (*MsgPause) ProtoMessage()    {}
func (*MsgPause) Descriptor() ([]byte, []int) {
	return fileDescriptor_195ed35d11349041, []int{2}
}

func (m *MsgPause) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgPause.Unmarshal(m, b)
}
func (m *MsgPause) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgPause.Marshal(b, m, deterministic)
}
func (m *MsgPause) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPause.Merge(m, src)
}
func (m *MsgPause) XXX_Size() int {
	return xxx_messageInfo_MsgPause.Size(m)
}
func (m *MsgPause) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPause.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPause proto.InternalMessageInfo

func (m *MsgPause) GetValidatorAddr() string {
	if m != nil {
		return m.ValidatorAddr
	}
	return ""
}

// MsgUnpauseResponse defines the Msg/Unpause response type
type MsgPauseResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgPauseResponse) Reset()         { *m = MsgPauseResponse{} }
func (m *MsgPauseResponse) String() string { return proto.CompactTextString(m) }
func (*MsgPauseResponse) ProtoMessage()    {}
func (*MsgPauseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_195ed35d11349041, []int{3}
}

func (m *MsgPauseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgPauseResponse.Unmarshal(m, b)
}
func (m *MsgPauseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgPauseResponse.Marshal(b, m, deterministic)
}
func (m *MsgPauseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPauseResponse.Merge(m, src)
}
func (m *MsgPauseResponse) XXX_Size() int {
	return xxx_messageInfo_MsgPauseResponse.Size(m)
}
func (m *MsgPauseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPauseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPauseResponse proto.InternalMessageInfo

// MsgUnpause defines the Msg/Unpause request type
type MsgUnpause struct {
	ValidatorAddr        string   `protobuf:"bytes,1,opt,name=validator_addr,json=validatorAddr,proto3" json:"validator_addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgUnpause) Reset()         { *m = MsgUnpause{} }
func (m *MsgUnpause) String() string { return proto.CompactTextString(m) }
func (*MsgUnpause) ProtoMessage()    {}
func (*MsgUnpause) Descriptor() ([]byte, []int) {
	return fileDescriptor_195ed35d11349041, []int{4}
}

func (m *MsgUnpause) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgUnpause.Unmarshal(m, b)
}
func (m *MsgUnpause) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgUnpause.Marshal(b, m, deterministic)
}
func (m *MsgUnpause) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUnpause.Merge(m, src)
}
func (m *MsgUnpause) XXX_Size() int {
	return xxx_messageInfo_MsgUnpause.Size(m)
}
func (m *MsgUnpause) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUnpause.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUnpause proto.InternalMessageInfo

func (m *MsgUnpause) GetValidatorAddr() string {
	if m != nil {
		return m.ValidatorAddr
	}
	return ""
}

// MsgUnpauseResponse defines the Msg/Unpause response type
type MsgUnpauseResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgUnpauseResponse) Reset()         { *m = MsgUnpauseResponse{} }
func (m *MsgUnpauseResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUnpauseResponse) ProtoMessage()    {}
func (*MsgUnpauseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_195ed35d11349041, []int{5}
}

func (m *MsgUnpauseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgUnpauseResponse.Unmarshal(m, b)
}
func (m *MsgUnpauseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgUnpauseResponse.Marshal(b, m, deterministic)
}
func (m *MsgUnpauseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUnpauseResponse.Merge(m, src)
}
func (m *MsgUnpauseResponse) XXX_Size() int {
	return xxx_messageInfo_MsgUnpauseResponse.Size(m)
}
func (m *MsgUnpauseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUnpauseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUnpauseResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgActivate)(nil), "kira.slashing.MsgActivate")
	proto.RegisterType((*MsgActivateResponse)(nil), "kira.slashing.MsgActivateResponse")
	proto.RegisterType((*MsgPause)(nil), "kira.slashing.MsgPause")
	proto.RegisterType((*MsgPauseResponse)(nil), "kira.slashing.MsgPauseResponse")
	proto.RegisterType((*MsgUnpause)(nil), "kira.slashing.MsgUnpause")
	proto.RegisterType((*MsgUnpauseResponse)(nil), "kira.slashing.MsgUnpauseResponse")
}

func init() { proto.RegisterFile("kira/slashing/v1beta1/tx.proto", fileDescriptor_195ed35d11349041) }

var fileDescriptor_195ed35d11349041 = []byte{
	// 337 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xcb, 0xce, 0x2c, 0x4a,
	0xd4, 0x2f, 0xce, 0x49, 0x2c, 0xce, 0xc8, 0xcc, 0x4b, 0xd7, 0x2f, 0x33, 0x4c, 0x4a, 0x2d, 0x49,
	0x34, 0xd4, 0x2f, 0xa9, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x05, 0xc9, 0xeb, 0xc1,
	0xe4, 0xa5, 0x44, 0xd2, 0xf3, 0xd3, 0xf3, 0xc1, 0x32, 0xfa, 0x20, 0x16, 0x44, 0x91, 0x94, 0x0a,
	0x76, 0x43, 0x0a, 0x8a, 0xf2, 0x0b, 0xf2, 0x8b, 0x13, 0x73, 0x20, 0xaa, 0x94, 0x62, 0xb9, 0xb8,
	0x7d, 0x8b, 0xd3, 0x1d, 0x93, 0x4b, 0x32, 0xcb, 0x12, 0x4b, 0x52, 0x85, 0x5c, 0xb8, 0xf8, 0xca,
	0x12, 0x73, 0x32, 0x53, 0x12, 0x4b, 0xf2, 0x8b, 0xe2, 0x13, 0x53, 0x52, 0x8a, 0x24, 0x18, 0x15,
	0x18, 0x35, 0x38, 0x9d, 0x64, 0x5f, 0xdd, 0x93, 0x67, 0x07, 0xf1, 0x53, 0x8b, 0x8b, 0x3f, 0xdd,
	0x93, 0xe7, 0xab, 0x4c, 0xcc, 0xcd, 0xb1, 0x52, 0x82, 0x0a, 0x28, 0x05, 0xf1, 0xc2, 0x35, 0x39,
	0xa6, 0xa4, 0x14, 0x59, 0x71, 0x74, 0x2c, 0x90, 0x67, 0x98, 0xb1, 0x40, 0x9e, 0x51, 0x49, 0x94,
	0x4b, 0x18, 0xc9, 0xf8, 0xa0, 0xd4, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0xa5, 0x28, 0x2e, 0x0e,
	0xdf, 0xe2, 0xf4, 0x80, 0xc4, 0xd2, 0x62, 0xea, 0x5b, 0x29, 0xc4, 0x25, 0x00, 0x33, 0x1b, 0x6e,
	0x5f, 0x0c, 0x17, 0x97, 0x6f, 0x71, 0x7a, 0x68, 0x5e, 0x01, 0x4d, 0x6c, 0x14, 0xe1, 0x12, 0x42,
	0x98, 0x0e, 0xb3, 0xd3, 0xe8, 0x2e, 0x23, 0x17, 0xb3, 0x6f, 0x71, 0xba, 0x90, 0x17, 0x17, 0x07,
	0x3c, 0x78, 0xa5, 0xf4, 0x50, 0x62, 0x4e, 0x0f, 0x29, 0x6c, 0xa4, 0x94, 0x70, 0xcb, 0xc1, 0xcc,
	0x14, 0x72, 0xe4, 0x62, 0x85, 0x04, 0x9a, 0x38, 0xa6, 0x62, 0xb0, 0x84, 0x94, 0x3c, 0x0e, 0x09,
	0xb8, 0x11, 0xee, 0x5c, 0xec, 0xb0, 0x70, 0x90, 0xc4, 0x54, 0x0b, 0x95, 0x92, 0x52, 0xc4, 0x29,
	0x05, 0x33, 0xc8, 0xc9, 0x60, 0xc5, 0x23, 0x39, 0xc6, 0x28, 0xad, 0xf4, 0xcc, 0x92, 0x8c, 0xd2,
	0x24, 0xbd, 0xe4, 0xfc, 0x5c, 0x7d, 0xef, 0xcc, 0xa2, 0x44, 0xe7, 0xfc, 0xa2, 0x54, 0xfd, 0xe2,
	0xd4, 0xec, 0xc4, 0x4c, 0xfd, 0x0a, 0x44, 0xe2, 0x2b, 0xa9, 0x2c, 0x48, 0x2d, 0x4e, 0x62, 0x03,
	0x27, 0x39, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x84, 0x77, 0x01, 0x44, 0xdf, 0x02, 0x00,
	0x00,
}
