// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kira/evidence/genesis.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	anypb "google.golang.org/protobuf/types/known/anypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the evidence module's genesis state.
type GenesisState struct {
	// evidence defines all the evidence at genesis.
	Evidence             []*anypb.Any `protobuf:"bytes,1,rep,name=evidence,proto3" json:"evidence,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ee03e15c4c5f0b7, []int{0}
}

func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenesisState.Unmarshal(m, b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return xxx_messageInfo_GenesisState.Size(m)
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetEvidence() []*anypb.Any {
	if m != nil {
		return m.Evidence
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "kira.evidence.GenesisState")
}

func init() { proto.RegisterFile("kira/evidence/genesis.proto", fileDescriptor_7ee03e15c4c5f0b7) }

var fileDescriptor_7ee03e15c4c5f0b7 = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xce, 0xce, 0x2c, 0x4a,
	0xd4, 0x4f, 0x2d, 0xcb, 0x4c, 0x49, 0xcd, 0x4b, 0x4e, 0xd5, 0x4f, 0x4f, 0xcd, 0x4b, 0x2d, 0xce,
	0x2c, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x05, 0x49, 0xea, 0xc1, 0x24, 0xa5, 0x24,
	0xd3, 0xf3, 0xf3, 0xd3, 0x73, 0x52, 0xf5, 0xc1, 0x92, 0x49, 0xa5, 0x69, 0xfa, 0x89, 0x79, 0x95,
	0x10, 0x95, 0x4a, 0x0e, 0x5c, 0x3c, 0xee, 0x10, 0xad, 0xc1, 0x25, 0x89, 0x25, 0xa9, 0x42, 0x06,
	0x5c, 0x1c, 0x30, 0x6d, 0x12, 0x8c, 0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0x22, 0x7a, 0x10, 0xdd, 0x7a,
	0x30, 0xdd, 0x7a, 0x8e, 0x79, 0x95, 0x41, 0x70, 0x55, 0x4e, 0x3a, 0x51, 0x5a, 0xe9, 0x99, 0x25,
	0x19, 0xa5, 0x49, 0x7a, 0xc9, 0xf9, 0xb9, 0xfa, 0xde, 0x99, 0x45, 0x89, 0xce, 0xf9, 0x45, 0xa9,
	0xfa, 0xc5, 0xa9, 0xd9, 0x89, 0x99, 0xfa, 0x15, 0x08, 0x17, 0x96, 0x54, 0x16, 0xa4, 0x16, 0x27,
	0xb1, 0x81, 0x4d, 0x31, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xf0, 0x6f, 0xfa, 0xd4, 0xbf, 0x00,
	0x00, 0x00,
}
