// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kira/evidence/tx.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/regen-network/cosmos-proto"
	anypb "google.golang.org/protobuf/types/known/anypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// MsgSubmitEvidence represents a message that supports submitting arbitrary
// Evidence of misbehavior such as equivocation or counterfactual signing.
type MsgSubmitEvidence struct {
	Submitter            string     `protobuf:"bytes,1,opt,name=submitter,proto3" json:"submitter,omitempty"`
	Evidence             *anypb.Any `protobuf:"bytes,2,opt,name=evidence,proto3" json:"evidence,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MsgSubmitEvidence) Reset()         { *m = MsgSubmitEvidence{} }
func (m *MsgSubmitEvidence) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitEvidence) ProtoMessage()    {}
func (*MsgSubmitEvidence) Descriptor() ([]byte, []int) {
	return fileDescriptor_198fe1e2e4821e46, []int{0}
}

func (m *MsgSubmitEvidence) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgSubmitEvidence.Unmarshal(m, b)
}
func (m *MsgSubmitEvidence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgSubmitEvidence.Marshal(b, m, deterministic)
}
func (m *MsgSubmitEvidence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitEvidence.Merge(m, src)
}
func (m *MsgSubmitEvidence) XXX_Size() int {
	return xxx_messageInfo_MsgSubmitEvidence.Size(m)
}
func (m *MsgSubmitEvidence) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitEvidence.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitEvidence proto.InternalMessageInfo

func (m *MsgSubmitEvidence) GetSubmitter() string {
	if m != nil {
		return m.Submitter
	}
	return ""
}

func (m *MsgSubmitEvidence) GetEvidence() *anypb.Any {
	if m != nil {
		return m.Evidence
	}
	return nil
}

// MsgSubmitEvidenceResponse defines the Msg/SubmitEvidence response type.
type MsgSubmitEvidenceResponse struct {
	// hash defines the hash of the evidence.
	Hash                 []byte   `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgSubmitEvidenceResponse) Reset()         { *m = MsgSubmitEvidenceResponse{} }
func (m *MsgSubmitEvidenceResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitEvidenceResponse) ProtoMessage()    {}
func (*MsgSubmitEvidenceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_198fe1e2e4821e46, []int{1}
}

func (m *MsgSubmitEvidenceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgSubmitEvidenceResponse.Unmarshal(m, b)
}
func (m *MsgSubmitEvidenceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgSubmitEvidenceResponse.Marshal(b, m, deterministic)
}
func (m *MsgSubmitEvidenceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitEvidenceResponse.Merge(m, src)
}
func (m *MsgSubmitEvidenceResponse) XXX_Size() int {
	return xxx_messageInfo_MsgSubmitEvidenceResponse.Size(m)
}
func (m *MsgSubmitEvidenceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitEvidenceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitEvidenceResponse proto.InternalMessageInfo

func (m *MsgSubmitEvidenceResponse) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func init() {
	proto.RegisterType((*MsgSubmitEvidence)(nil), "kira.evidence.MsgSubmitEvidence")
	proto.RegisterType((*MsgSubmitEvidenceResponse)(nil), "kira.evidence.MsgSubmitEvidenceResponse")
}

func init() { proto.RegisterFile("kira/evidence/tx.proto", fileDescriptor_198fe1e2e4821e46) }

var fileDescriptor_198fe1e2e4821e46 = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcb, 0xce, 0x2c, 0x4a,
	0xd4, 0x4f, 0x2d, 0xcb, 0x4c, 0x49, 0xcd, 0x4b, 0x4e, 0xd5, 0x2f, 0xa9, 0xd0, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0xe2, 0x05, 0x89, 0xeb, 0xc1, 0xc4, 0xa5, 0x44, 0xd2, 0xf3, 0xd3, 0xf3, 0xc1,
	0x32, 0xfa, 0x20, 0x16, 0x44, 0x91, 0x94, 0x64, 0x7a, 0x7e, 0x7e, 0x7a, 0x4e, 0xaa, 0x3e, 0x98,
	0x97, 0x54, 0x9a, 0xa6, 0x9f, 0x98, 0x57, 0x09, 0x93, 0x4a, 0xce, 0x2f, 0xce, 0xcd, 0x2f, 0x8e,
	0x87, 0xe8, 0x81, 0x70, 0x20, 0x52, 0x4a, 0xd5, 0x5c, 0x82, 0xbe, 0xc5, 0xe9, 0xc1, 0xa5, 0x49,
	0xb9, 0x99, 0x25, 0xae, 0x50, 0x0b, 0x84, 0x64, 0xb8, 0x38, 0x8b, 0xc1, 0x22, 0x25, 0xa9, 0x45,
	0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x08, 0x01, 0x21, 0x3b, 0x2e, 0x0e, 0x98, 0x53, 0x24,
	0x98, 0x14, 0x18, 0x35, 0xb8, 0x8d, 0x44, 0xf4, 0x20, 0x76, 0xeb, 0xc1, 0xec, 0xd6, 0x73, 0xcc,
	0xab, 0x74, 0xe2, 0x39, 0xb5, 0x45, 0x97, 0x03, 0x66, 0x66, 0x10, 0x5c, 0x8f, 0x15, 0x47, 0xc7,
	0x02, 0x79, 0x86, 0x17, 0x0b, 0xe4, 0x19, 0x94, 0xf4, 0xb9, 0x24, 0x31, 0x2c, 0x0f, 0x4a, 0x2d,
	0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0x12, 0xe2, 0x62, 0xc9, 0x48, 0x2c, 0xce, 0x90, 0x60, 0x51,
	0x60, 0xd4, 0xe0, 0x09, 0x02, 0xb3, 0x8d, 0x92, 0xb9, 0x98, 0x7d, 0x8b, 0xd3, 0x85, 0x62, 0xb8,
	0xf8, 0xd0, 0x5c, 0xac, 0xa0, 0x87, 0x12, 0x44, 0x7a, 0x18, 0xc6, 0x4a, 0x69, 0x10, 0x52, 0x01,
	0xb3, 0xd8, 0xc9, 0x60, 0xc5, 0x23, 0x39, 0xc6, 0x28, 0xad, 0xf4, 0xcc, 0x92, 0x8c, 0xd2, 0x24,
	0xbd, 0xe4, 0xfc, 0x5c, 0x7d, 0xef, 0xcc, 0xa2, 0x44, 0xe7, 0xfc, 0xa2, 0x54, 0xfd, 0xe2, 0xd4,
	0xec, 0xc4, 0x4c, 0xfd, 0x0a, 0xa4, 0x28, 0xaa, 0x2c, 0x48, 0x2d, 0x4e, 0x62, 0x03, 0xfb, 0xdb,
	0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x65, 0x23, 0x18, 0x80, 0xc0, 0x01, 0x00, 0x00,
}
