// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cosmos/slashing/v1beta1/query.proto

package types

import (
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is the request type for the Query/Params RPC method
type QueryParamsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_791b11d41a861ed0, []int{0}
}

func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryParamsRequest.Unmarshal(m, b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return xxx_messageInfo_QueryParamsRequest.Size(m)
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is the response type for the Query/Params RPC method
type QueryParamsResponse struct {
	Params               *Params  `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_791b11d41a861ed0, []int{1}
}

func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryParamsResponse.Unmarshal(m, b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return xxx_messageInfo_QueryParamsResponse.Size(m)
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() *Params {
	if m != nil {
		return m.Params
	}
	return nil
}

// QuerySigningInfoRequest is the request type for the Query/SigningInfo RPC
// method
type QuerySigningInfoRequest struct {
	// cons_address is the address to query signing info of
	ConsAddress          string   `protobuf:"bytes,1,opt,name=cons_address,json=consAddress,proto3" json:"cons_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuerySigningInfoRequest) Reset()         { *m = QuerySigningInfoRequest{} }
func (m *QuerySigningInfoRequest) String() string { return proto.CompactTextString(m) }
func (*QuerySigningInfoRequest) ProtoMessage()    {}
func (*QuerySigningInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_791b11d41a861ed0, []int{2}
}

func (m *QuerySigningInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuerySigningInfoRequest.Unmarshal(m, b)
}
func (m *QuerySigningInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuerySigningInfoRequest.Marshal(b, m, deterministic)
}
func (m *QuerySigningInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySigningInfoRequest.Merge(m, src)
}
func (m *QuerySigningInfoRequest) XXX_Size() int {
	return xxx_messageInfo_QuerySigningInfoRequest.Size(m)
}
func (m *QuerySigningInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySigningInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySigningInfoRequest proto.InternalMessageInfo

func (m *QuerySigningInfoRequest) GetConsAddress() string {
	if m != nil {
		return m.ConsAddress
	}
	return ""
}

// QuerySigningInfoResponse is the response type for the Query/SigningInfo RPC
// method
type QuerySigningInfoResponse struct {
	// val_signing_info is the signing info of requested val cons address
	ValSigningInfo       *ValidatorSigningInfo `protobuf:"bytes,1,opt,name=val_signing_info,json=valSigningInfo,proto3" json:"val_signing_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *QuerySigningInfoResponse) Reset()         { *m = QuerySigningInfoResponse{} }
func (m *QuerySigningInfoResponse) String() string { return proto.CompactTextString(m) }
func (*QuerySigningInfoResponse) ProtoMessage()    {}
func (*QuerySigningInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_791b11d41a861ed0, []int{3}
}

func (m *QuerySigningInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuerySigningInfoResponse.Unmarshal(m, b)
}
func (m *QuerySigningInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuerySigningInfoResponse.Marshal(b, m, deterministic)
}
func (m *QuerySigningInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySigningInfoResponse.Merge(m, src)
}
func (m *QuerySigningInfoResponse) XXX_Size() int {
	return xxx_messageInfo_QuerySigningInfoResponse.Size(m)
}
func (m *QuerySigningInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySigningInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySigningInfoResponse proto.InternalMessageInfo

func (m *QuerySigningInfoResponse) GetValSigningInfo() *ValidatorSigningInfo {
	if m != nil {
		return m.ValSigningInfo
	}
	return nil
}

// QuerySigningInfosRequest is the request type for the Query/SigningInfos RPC
// method
type QuerySigningInfosRequest struct {
	Pagination           *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *QuerySigningInfosRequest) Reset()         { *m = QuerySigningInfosRequest{} }
func (m *QuerySigningInfosRequest) String() string { return proto.CompactTextString(m) }
func (*QuerySigningInfosRequest) ProtoMessage()    {}
func (*QuerySigningInfosRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_791b11d41a861ed0, []int{4}
}

func (m *QuerySigningInfosRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuerySigningInfosRequest.Unmarshal(m, b)
}
func (m *QuerySigningInfosRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuerySigningInfosRequest.Marshal(b, m, deterministic)
}
func (m *QuerySigningInfosRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySigningInfosRequest.Merge(m, src)
}
func (m *QuerySigningInfosRequest) XXX_Size() int {
	return xxx_messageInfo_QuerySigningInfosRequest.Size(m)
}
func (m *QuerySigningInfosRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySigningInfosRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySigningInfosRequest proto.InternalMessageInfo

func (m *QuerySigningInfosRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QuerySigningInfosResponse is the response type for the Query/SigningInfos RPC
// method
type QuerySigningInfosResponse struct {
	// info is the signing info of all validators
	Info                 []*ValidatorSigningInfo `protobuf:"bytes,1,rep,name=info,proto3" json:"info,omitempty"`
	Pagination           *query.PageResponse     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *QuerySigningInfosResponse) Reset()         { *m = QuerySigningInfosResponse{} }
func (m *QuerySigningInfosResponse) String() string { return proto.CompactTextString(m) }
func (*QuerySigningInfosResponse) ProtoMessage()    {}
func (*QuerySigningInfosResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_791b11d41a861ed0, []int{5}
}

func (m *QuerySigningInfosResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuerySigningInfosResponse.Unmarshal(m, b)
}
func (m *QuerySigningInfosResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuerySigningInfosResponse.Marshal(b, m, deterministic)
}
func (m *QuerySigningInfosResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySigningInfosResponse.Merge(m, src)
}
func (m *QuerySigningInfosResponse) XXX_Size() int {
	return xxx_messageInfo_QuerySigningInfosResponse.Size(m)
}
func (m *QuerySigningInfosResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySigningInfosResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySigningInfosResponse proto.InternalMessageInfo

func (m *QuerySigningInfosResponse) GetInfo() []*ValidatorSigningInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *QuerySigningInfosResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "cosmos.slashing.v1beta1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "cosmos.slashing.v1beta1.QueryParamsResponse")
	proto.RegisterType((*QuerySigningInfoRequest)(nil), "cosmos.slashing.v1beta1.QuerySigningInfoRequest")
	proto.RegisterType((*QuerySigningInfoResponse)(nil), "cosmos.slashing.v1beta1.QuerySigningInfoResponse")
	proto.RegisterType((*QuerySigningInfosRequest)(nil), "cosmos.slashing.v1beta1.QuerySigningInfosRequest")
	proto.RegisterType((*QuerySigningInfosResponse)(nil), "cosmos.slashing.v1beta1.QuerySigningInfosResponse")
}

func init() {
	proto.RegisterFile("cosmos/slashing/v1beta1/query.proto", fileDescriptor_791b11d41a861ed0)
}

var fileDescriptor_791b11d41a861ed0 = []byte{
	// 498 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xb1, 0x6e, 0x13, 0x41,
	0x10, 0x86, 0xb9, 0x24, 0x58, 0x62, 0x1c, 0x21, 0xb4, 0x44, 0x4a, 0xb0, 0x90, 0x4c, 0x0e, 0xc9,
	0x89, 0x00, 0xdf, 0x62, 0x23, 0x44, 0x43, 0x0a, 0x52, 0x10, 0xd1, 0x81, 0x41, 0x14, 0x48, 0xc8,
	0xda, 0xb3, 0x37, 0x9b, 0x15, 0xe7, 0x9d, 0xcb, 0xcd, 0xd9, 0xc2, 0x42, 0x34, 0xd4, 0x74, 0x3c,
	0x03, 0x25, 0x05, 0x6f, 0x41, 0x4f, 0x4f, 0xc5, 0x13, 0xf0, 0x04, 0xc8, 0xbb, 0x6b, 0xfb, 0xa2,
	0xe3, 0xc0, 0xa1, 0xba, 0xd5, 0xec, 0xfc, 0xf3, 0x7f, 0xb3, 0x33, 0x3a, 0xb8, 0x39, 0x40, 0x1a,
	0x21, 0x71, 0x4a, 0x04, 0x9d, 0x68, 0xa3, 0xf8, 0xa4, 0x13, 0xcb, 0x5c, 0x74, 0xf8, 0xe9, 0x58,
	0x66, 0xd3, 0x28, 0xcd, 0x30, 0x47, 0xb6, 0xed, 0x92, 0xa2, 0x79, 0x52, 0xe4, 0x93, 0x1a, 0xb7,
	0xbc, 0x3a, 0x16, 0x24, 0x9d, 0x62, 0xa1, 0x4f, 0x85, 0xd2, 0x46, 0xe4, 0x1a, 0x8d, 0x2b, 0xd2,
	0xd8, 0x52, 0xa8, 0xd0, 0x1e, 0xf9, 0xec, 0xe4, 0xa3, 0xd7, 0x15, 0xa2, 0x4a, 0x24, 0x17, 0xa9,
	0xe6, 0xc2, 0x18, 0xcc, 0xad, 0x84, 0xfc, 0x6d, 0xab, 0x8a, 0x6e, 0x41, 0x62, 0xf3, 0xc2, 0x2d,
	0x60, 0xcf, 0x66, 0xee, 0x4f, 0x45, 0x26, 0x46, 0xd4, 0x93, 0xa7, 0x63, 0x49, 0x79, 0xf8, 0x02,
	0xae, 0x9e, 0x89, 0x52, 0x8a, 0x86, 0x24, 0x3b, 0x80, 0x5a, 0x6a, 0x23, 0x3b, 0xc1, 0x8d, 0x60,
	0xbf, 0xde, 0x6d, 0x46, 0x15, 0xed, 0x45, 0x4e, 0x78, 0xb8, 0xf1, 0xed, 0x47, 0xf3, 0x42, 0xcf,
	0x8b, 0xc2, 0x87, 0xb0, 0x6d, 0xab, 0x3e, 0xd7, 0xca, 0x68, 0xa3, 0x9e, 0x98, 0x63, 0xf4, 0x86,
	0x6c, 0x17, 0x36, 0x07, 0x68, 0xa8, 0x2f, 0x86, 0xc3, 0x4c, 0x92, 0xab, 0x7f, 0xa9, 0x57, 0x9f,
	0xc5, 0x1e, 0xb9, 0x50, 0x38, 0x85, 0x9d, 0xb2, 0xda, 0x83, 0xbd, 0x86, 0x2b, 0x13, 0x91, 0xf4,
	0xc9, 0x5d, 0xf5, 0xb5, 0x39, 0x46, 0x8f, 0xd8, 0xae, 0x44, 0x7c, 0x29, 0x12, 0x3d, 0x14, 0x39,
	0x66, 0x85, 0x82, 0x1e, 0xf8, 0xf2, 0x44, 0x24, 0x85, 0x68, 0x18, 0x97, 0xad, 0xe7, 0x4f, 0xc5,
	0x1e, 0x03, 0x2c, 0x07, 0xe6, 0x4d, 0x5b, 0x73, 0xd3, 0xd9, 0x74, 0x23, 0xb7, 0x0f, 0xcb, 0x97,
	0x51, 0xd2, 0x6b, 0x7b, 0x05, 0x65, 0xf8, 0x25, 0x80, 0x6b, 0x7f, 0x30, 0xf1, 0x0d, 0x1e, 0xc1,
	0x86, 0x6f, 0x6a, 0xfd, 0x7f, 0x9b, 0xb2, 0x05, 0xd8, 0xd1, 0x19, 0xdc, 0x35, 0x8b, 0xbb, 0xf7,
	0x4f, 0x5c, 0x47, 0x51, 0xe4, 0xed, 0xfe, 0x5a, 0x87, 0x8b, 0x96, 0x97, 0x7d, 0x0c, 0xa0, 0xe6,
	0xe6, 0xcd, 0x6e, 0x57, 0x82, 0x95, 0x97, 0xac, 0x71, 0x67, 0xb5, 0x64, 0xe7, 0x1d, 0xee, 0x7d,
	0xf8, 0xfe, 0xf3, 0xd3, 0xda, 0x2e, 0x6b, 0xf2, 0xaa, 0xcd, 0x76, 0x5b, 0xc6, 0xbe, 0x06, 0x50,
	0x2f, 0x74, 0xcf, 0xee, 0xfe, 0xdd, 0xa6, 0xbc, 0x8c, 0x8d, 0xce, 0x39, 0x14, 0x9e, 0xee, 0xc0,
	0xd2, 0x3d, 0x60, 0xf7, 0x2b, 0xe9, 0x8a, 0xbb, 0x49, 0xfc, 0x5d, 0x71, 0xdb, 0xdf, 0xb3, 0xcf,
	0x01, 0x6c, 0x16, 0xe7, 0xce, 0x56, 0x47, 0x58, 0x3c, 0x67, 0xf7, 0x3c, 0x12, 0x8f, 0x1d, 0x59,
	0xec, 0x7d, 0xd6, 0x5a, 0x0d, 0xfb, 0x90, 0xbf, 0x6a, 0x2b, 0x9d, 0x9f, 0x8c, 0xe3, 0x68, 0x80,
	0xa3, 0xb9, 0xc6, 0x7d, 0xda, 0x34, 0x7c, 0xc3, 0xdf, 0x2e, 0x0b, 0xe4, 0xd3, 0x54, 0x52, 0x5c,
	0xb3, 0x7f, 0x99, 0x7b, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xee, 0x1e, 0xaf, 0xda, 0x2d, 0x05,
	0x00, 0x00,
}
