// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cosmos/params/v1beta1/params.proto

package proposal

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ParameterChangeProposal defines a proposal to change one or more parameters.
type ParameterChangeProposal struct {
	Title                string         `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          string         `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Changes              []*ParamChange `protobuf:"bytes,3,rep,name=changes,proto3" json:"changes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ParameterChangeProposal) Reset()         { *m = ParameterChangeProposal{} }
func (m *ParameterChangeProposal) String() string { return proto.CompactTextString(m) }
func (*ParameterChangeProposal) ProtoMessage()    {}
func (*ParameterChangeProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_53a944ecb0483e4c, []int{0}
}

func (m *ParameterChangeProposal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParameterChangeProposal.Unmarshal(m, b)
}
func (m *ParameterChangeProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParameterChangeProposal.Marshal(b, m, deterministic)
}
func (m *ParameterChangeProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParameterChangeProposal.Merge(m, src)
}
func (m *ParameterChangeProposal) XXX_Size() int {
	return xxx_messageInfo_ParameterChangeProposal.Size(m)
}
func (m *ParameterChangeProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_ParameterChangeProposal.DiscardUnknown(m)
}

var xxx_messageInfo_ParameterChangeProposal proto.InternalMessageInfo

func (m *ParameterChangeProposal) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ParameterChangeProposal) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ParameterChangeProposal) GetChanges() []*ParamChange {
	if m != nil {
		return m.Changes
	}
	return nil
}

// ParamChange defines an individual parameter change, for use in
// ParameterChangeProposal.
type ParamChange struct {
	Subspace             string   `protobuf:"bytes,1,opt,name=subspace,proto3" json:"subspace,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParamChange) Reset()         { *m = ParamChange{} }
func (m *ParamChange) String() string { return proto.CompactTextString(m) }
func (*ParamChange) ProtoMessage()    {}
func (*ParamChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_53a944ecb0483e4c, []int{1}
}

func (m *ParamChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParamChange.Unmarshal(m, b)
}
func (m *ParamChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParamChange.Marshal(b, m, deterministic)
}
func (m *ParamChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParamChange.Merge(m, src)
}
func (m *ParamChange) XXX_Size() int {
	return xxx_messageInfo_ParamChange.Size(m)
}
func (m *ParamChange) XXX_DiscardUnknown() {
	xxx_messageInfo_ParamChange.DiscardUnknown(m)
}

var xxx_messageInfo_ParamChange proto.InternalMessageInfo

func (m *ParamChange) GetSubspace() string {
	if m != nil {
		return m.Subspace
	}
	return ""
}

func (m *ParamChange) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ParamChange) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*ParameterChangeProposal)(nil), "cosmos.params.v1beta1.ParameterChangeProposal")
	proto.RegisterType((*ParamChange)(nil), "cosmos.params.v1beta1.ParamChange")
}

func init() { proto.RegisterFile("cosmos/params/v1beta1/params.proto", fileDescriptor_53a944ecb0483e4c) }

var fileDescriptor_53a944ecb0483e4c = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4a, 0xce, 0x2f, 0xce,
	0xcd, 0x2f, 0xd6, 0x2f, 0x48, 0x2c, 0x4a, 0xcc, 0x2d, 0xd6, 0x2f, 0x33, 0x4c, 0x4a, 0x2d, 0x49,
	0x34, 0x84, 0x72, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x44, 0x21, 0x6a, 0xf4, 0xa0, 0x82,
	0x50, 0x35, 0x52, 0x22, 0xe9, 0xf9, 0xe9, 0xf9, 0x60, 0x15, 0xfa, 0x20, 0x16, 0x44, 0xb1, 0xd2,
	0x7c, 0x46, 0x2e, 0xf1, 0x00, 0x90, 0xc2, 0xd4, 0x92, 0xd4, 0x22, 0xe7, 0x8c, 0xc4, 0xbc, 0xf4,
	0xd4, 0x80, 0xa2, 0xfc, 0x82, 0xfc, 0xe2, 0xc4, 0x1c, 0x21, 0x11, 0x2e, 0xd6, 0x92, 0xcc, 0x92,
	0x9c, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x08, 0x47, 0x48, 0x81, 0x8b, 0x3b, 0x25,
	0xb5, 0x38, 0xb9, 0x28, 0xb3, 0xa0, 0x24, 0x33, 0x3f, 0x4f, 0x82, 0x09, 0x2c, 0x87, 0x2c, 0x24,
	0xe4, 0xc4, 0xc5, 0x9e, 0x0c, 0x36, 0xa9, 0x58, 0x82, 0x59, 0x81, 0x59, 0x83, 0xdb, 0x48, 0x49,
	0x0f, 0xab, 0x93, 0xf4, 0xc0, 0x16, 0x43, 0x2c, 0x75, 0x62, 0x39, 0x71, 0x4f, 0x9e, 0x21, 0x08,
	0xa6, 0xd1, 0x8a, 0xa3, 0x63, 0x81, 0x3c, 0xc3, 0x8c, 0x05, 0xf2, 0x0c, 0x4a, 0xe1, 0x5c, 0xdc,
	0x48, 0xea, 0x84, 0xa4, 0xb8, 0x38, 0x8a, 0x4b, 0x93, 0x8a, 0x0b, 0x12, 0x93, 0x61, 0xee, 0x82,
	0xf3, 0x85, 0x04, 0xb8, 0x98, 0xb3, 0x53, 0x2b, 0xa1, 0x4e, 0x02, 0x31, 0x41, 0x5e, 0x28, 0x4b,
	0xcc, 0x29, 0x4d, 0x95, 0x60, 0x86, 0x78, 0x01, 0xcc, 0xb1, 0x62, 0x01, 0x19, 0xec, 0x64, 0xb5,
	0xe2, 0x91, 0x1c, 0x63, 0x94, 0x49, 0x7a, 0x66, 0x49, 0x46, 0x69, 0x92, 0x5e, 0x72, 0x7e, 0xae,
	0x3e, 0x34, 0x70, 0x21, 0x94, 0x6e, 0x71, 0x4a, 0xb6, 0x7e, 0x05, 0x2c, 0xa4, 0x4b, 0x2a, 0x0b,
	0x52, 0x8b, 0xf5, 0x0b, 0xa0, 0x41, 0x93, 0xc4, 0x06, 0x0e, 0x3d, 0x63, 0x40, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x14, 0xa8, 0xe1, 0xcc, 0x90, 0x01, 0x00, 0x00,
}
