// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cosmos/tx/signing/v1beta1/signing.proto

package signing

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/crypto/types"
	proto "github.com/golang/protobuf/proto"
	anypb "google.golang.org/protobuf/types/known/anypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// SignMode represents a signing mode with its own security guarantees.
type SignMode int32

const (
	// SIGN_MODE_UNSPECIFIED specifies an unknown signing mode and will be
	// rejected
	SignMode_SIGN_MODE_UNSPECIFIED SignMode = 0
	// SIGN_MODE_DIRECT specifies a signing mode which uses SignDoc and is
	// verified with raw bytes from Tx
	SignMode_SIGN_MODE_DIRECT SignMode = 1
	// SIGN_MODE_TEXTUAL is a future signing mode that will verify some
	// human-readable textual representation on top of the binary representation
	// from SIGN_MODE_DIRECT
	SignMode_SIGN_MODE_TEXTUAL SignMode = 2
	// SIGN_MODE_LEGACY_AMINO_JSON is a backwards compatibility mode which uses
	// Amino JSON and will be removed in the future
	SignMode_SIGN_MODE_LEGACY_AMINO_JSON SignMode = 127
)

var SignMode_name = map[int32]string{
	0:   "SIGN_MODE_UNSPECIFIED",
	1:   "SIGN_MODE_DIRECT",
	2:   "SIGN_MODE_TEXTUAL",
	127: "SIGN_MODE_LEGACY_AMINO_JSON",
}

var SignMode_value = map[string]int32{
	"SIGN_MODE_UNSPECIFIED":       0,
	"SIGN_MODE_DIRECT":            1,
	"SIGN_MODE_TEXTUAL":           2,
	"SIGN_MODE_LEGACY_AMINO_JSON": 127,
}

func (x SignMode) String() string {
	return proto.EnumName(SignMode_name, int32(x))
}

func (SignMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9a54958ff3d0b1b9, []int{0}
}

// SignatureDescriptors wraps multiple SignatureDescriptor's.
type SignatureDescriptors struct {
	// signatures are the signature descriptors
	Signatures           []*SignatureDescriptor `protobuf:"bytes,1,rep,name=signatures,proto3" json:"signatures,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SignatureDescriptors) Reset()         { *m = SignatureDescriptors{} }
func (m *SignatureDescriptors) String() string { return proto.CompactTextString(m) }
func (*SignatureDescriptors) ProtoMessage()    {}
func (*SignatureDescriptors) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a54958ff3d0b1b9, []int{0}
}

func (m *SignatureDescriptors) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignatureDescriptors.Unmarshal(m, b)
}
func (m *SignatureDescriptors) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignatureDescriptors.Marshal(b, m, deterministic)
}
func (m *SignatureDescriptors) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignatureDescriptors.Merge(m, src)
}
func (m *SignatureDescriptors) XXX_Size() int {
	return xxx_messageInfo_SignatureDescriptors.Size(m)
}
func (m *SignatureDescriptors) XXX_DiscardUnknown() {
	xxx_messageInfo_SignatureDescriptors.DiscardUnknown(m)
}

var xxx_messageInfo_SignatureDescriptors proto.InternalMessageInfo

func (m *SignatureDescriptors) GetSignatures() []*SignatureDescriptor {
	if m != nil {
		return m.Signatures
	}
	return nil
}

// SignatureDescriptor is a convenience type which represents the full data for
// a signature including the public key of the signer, signing modes and the
// signature itself. It is primarily used for coordinating signatures between
// clients.
type SignatureDescriptor struct {
	// public_key is the public key of the signer
	PublicKey *anypb.Any                `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Data      *SignatureDescriptor_Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// sequence is the sequence of the account, which describes the
	// number of committed transactions signed by a given address. It is used to prevent
	// replay attacks.
	Sequence             uint64   `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignatureDescriptor) Reset()         { *m = SignatureDescriptor{} }
func (m *SignatureDescriptor) String() string { return proto.CompactTextString(m) }
func (*SignatureDescriptor) ProtoMessage()    {}
func (*SignatureDescriptor) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a54958ff3d0b1b9, []int{1}
}

func (m *SignatureDescriptor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignatureDescriptor.Unmarshal(m, b)
}
func (m *SignatureDescriptor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignatureDescriptor.Marshal(b, m, deterministic)
}
func (m *SignatureDescriptor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignatureDescriptor.Merge(m, src)
}
func (m *SignatureDescriptor) XXX_Size() int {
	return xxx_messageInfo_SignatureDescriptor.Size(m)
}
func (m *SignatureDescriptor) XXX_DiscardUnknown() {
	xxx_messageInfo_SignatureDescriptor.DiscardUnknown(m)
}

var xxx_messageInfo_SignatureDescriptor proto.InternalMessageInfo

func (m *SignatureDescriptor) GetPublicKey() *anypb.Any {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *SignatureDescriptor) GetData() *SignatureDescriptor_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SignatureDescriptor) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

// Data represents signature data
type SignatureDescriptor_Data struct {
	// sum is the oneof that specifies whether this represents single or multi-signature data
	//
	// Types that are valid to be assigned to Sum:
	//	*SignatureDescriptor_Data_Single_
	//	*SignatureDescriptor_Data_Multi_
	Sum                  isSignatureDescriptor_Data_Sum `protobuf_oneof:"sum"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *SignatureDescriptor_Data) Reset()         { *m = SignatureDescriptor_Data{} }
func (m *SignatureDescriptor_Data) String() string { return proto.CompactTextString(m) }
func (*SignatureDescriptor_Data) ProtoMessage()    {}
func (*SignatureDescriptor_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a54958ff3d0b1b9, []int{1, 0}
}

func (m *SignatureDescriptor_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignatureDescriptor_Data.Unmarshal(m, b)
}
func (m *SignatureDescriptor_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignatureDescriptor_Data.Marshal(b, m, deterministic)
}
func (m *SignatureDescriptor_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignatureDescriptor_Data.Merge(m, src)
}
func (m *SignatureDescriptor_Data) XXX_Size() int {
	return xxx_messageInfo_SignatureDescriptor_Data.Size(m)
}
func (m *SignatureDescriptor_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_SignatureDescriptor_Data.DiscardUnknown(m)
}

var xxx_messageInfo_SignatureDescriptor_Data proto.InternalMessageInfo

type isSignatureDescriptor_Data_Sum interface {
	isSignatureDescriptor_Data_Sum()
}

type SignatureDescriptor_Data_Single_ struct {
	Single *SignatureDescriptor_Data_Single `protobuf:"bytes,1,opt,name=single,proto3,oneof"`
}

type SignatureDescriptor_Data_Multi_ struct {
	Multi *SignatureDescriptor_Data_Multi `protobuf:"bytes,2,opt,name=multi,proto3,oneof"`
}

func (*SignatureDescriptor_Data_Single_) isSignatureDescriptor_Data_Sum() {}

func (*SignatureDescriptor_Data_Multi_) isSignatureDescriptor_Data_Sum() {}

func (m *SignatureDescriptor_Data) GetSum() isSignatureDescriptor_Data_Sum {
	if m != nil {
		return m.Sum
	}
	return nil
}

func (m *SignatureDescriptor_Data) GetSingle() *SignatureDescriptor_Data_Single {
	if x, ok := m.GetSum().(*SignatureDescriptor_Data_Single_); ok {
		return x.Single
	}
	return nil
}

func (m *SignatureDescriptor_Data) GetMulti() *SignatureDescriptor_Data_Multi {
	if x, ok := m.GetSum().(*SignatureDescriptor_Data_Multi_); ok {
		return x.Multi
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SignatureDescriptor_Data) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SignatureDescriptor_Data_Single_)(nil),
		(*SignatureDescriptor_Data_Multi_)(nil),
	}
}

// Single is the signature data for a single signer
type SignatureDescriptor_Data_Single struct {
	// mode is the signing mode of the single signer
	Mode SignMode `protobuf:"varint,1,opt,name=mode,proto3,enum=cosmos.tx.signing.v1beta1.SignMode" json:"mode,omitempty"`
	// signature is the raw signature bytes
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignatureDescriptor_Data_Single) Reset()         { *m = SignatureDescriptor_Data_Single{} }
func (m *SignatureDescriptor_Data_Single) String() string { return proto.CompactTextString(m) }
func (*SignatureDescriptor_Data_Single) ProtoMessage()    {}
func (*SignatureDescriptor_Data_Single) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a54958ff3d0b1b9, []int{1, 0, 0}
}

func (m *SignatureDescriptor_Data_Single) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignatureDescriptor_Data_Single.Unmarshal(m, b)
}
func (m *SignatureDescriptor_Data_Single) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignatureDescriptor_Data_Single.Marshal(b, m, deterministic)
}
func (m *SignatureDescriptor_Data_Single) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignatureDescriptor_Data_Single.Merge(m, src)
}
func (m *SignatureDescriptor_Data_Single) XXX_Size() int {
	return xxx_messageInfo_SignatureDescriptor_Data_Single.Size(m)
}
func (m *SignatureDescriptor_Data_Single) XXX_DiscardUnknown() {
	xxx_messageInfo_SignatureDescriptor_Data_Single.DiscardUnknown(m)
}

var xxx_messageInfo_SignatureDescriptor_Data_Single proto.InternalMessageInfo

func (m *SignatureDescriptor_Data_Single) GetMode() SignMode {
	if m != nil {
		return m.Mode
	}
	return SignMode_SIGN_MODE_UNSPECIFIED
}

func (m *SignatureDescriptor_Data_Single) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

// Multi is the signature data for a multisig public key
type SignatureDescriptor_Data_Multi struct {
	// bitarray specifies which keys within the multisig are signing
	Bitarray *types.CompactBitArray `protobuf:"bytes,1,opt,name=bitarray,proto3" json:"bitarray,omitempty"`
	// signatures is the signatures of the multi-signature
	Signatures           []*SignatureDescriptor_Data `protobuf:"bytes,2,rep,name=signatures,proto3" json:"signatures,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *SignatureDescriptor_Data_Multi) Reset()         { *m = SignatureDescriptor_Data_Multi{} }
func (m *SignatureDescriptor_Data_Multi) String() string { return proto.CompactTextString(m) }
func (*SignatureDescriptor_Data_Multi) ProtoMessage()    {}
func (*SignatureDescriptor_Data_Multi) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a54958ff3d0b1b9, []int{1, 0, 1}
}

func (m *SignatureDescriptor_Data_Multi) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignatureDescriptor_Data_Multi.Unmarshal(m, b)
}
func (m *SignatureDescriptor_Data_Multi) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignatureDescriptor_Data_Multi.Marshal(b, m, deterministic)
}
func (m *SignatureDescriptor_Data_Multi) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignatureDescriptor_Data_Multi.Merge(m, src)
}
func (m *SignatureDescriptor_Data_Multi) XXX_Size() int {
	return xxx_messageInfo_SignatureDescriptor_Data_Multi.Size(m)
}
func (m *SignatureDescriptor_Data_Multi) XXX_DiscardUnknown() {
	xxx_messageInfo_SignatureDescriptor_Data_Multi.DiscardUnknown(m)
}

var xxx_messageInfo_SignatureDescriptor_Data_Multi proto.InternalMessageInfo

func (m *SignatureDescriptor_Data_Multi) GetBitarray() *types.CompactBitArray {
	if m != nil {
		return m.Bitarray
	}
	return nil
}

func (m *SignatureDescriptor_Data_Multi) GetSignatures() []*SignatureDescriptor_Data {
	if m != nil {
		return m.Signatures
	}
	return nil
}

func init() {
	proto.RegisterEnum("cosmos.tx.signing.v1beta1.SignMode", SignMode_name, SignMode_value)
	proto.RegisterType((*SignatureDescriptors)(nil), "cosmos.tx.signing.v1beta1.SignatureDescriptors")
	proto.RegisterType((*SignatureDescriptor)(nil), "cosmos.tx.signing.v1beta1.SignatureDescriptor")
	proto.RegisterType((*SignatureDescriptor_Data)(nil), "cosmos.tx.signing.v1beta1.SignatureDescriptor.Data")
	proto.RegisterType((*SignatureDescriptor_Data_Single)(nil), "cosmos.tx.signing.v1beta1.SignatureDescriptor.Data.Single")
	proto.RegisterType((*SignatureDescriptor_Data_Multi)(nil), "cosmos.tx.signing.v1beta1.SignatureDescriptor.Data.Multi")
}

func init() {
	proto.RegisterFile("cosmos/tx/signing/v1beta1/signing.proto", fileDescriptor_9a54958ff3d0b1b9)
}

var fileDescriptor_9a54958ff3d0b1b9 = []byte{
	// 511 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0xeb, 0x7c, 0x29, 0x9d, 0x22, 0x14, 0x96, 0x54, 0x4a, 0x0c, 0x12, 0x51, 0x39, 0x10,
	0x21, 0x65, 0xad, 0x26, 0x07, 0x04, 0xb7, 0x7c, 0x98, 0x34, 0xb4, 0x49, 0xc0, 0x4e, 0x25, 0xe0,
	0x62, 0xd9, 0xce, 0xd6, 0xac, 0x1a, 0x7b, 0x8d, 0x77, 0x8d, 0xea, 0x13, 0xcf, 0xc3, 0x73, 0xf0,
	0x4c, 0xdc, 0x51, 0xd6, 0xd9, 0x24, 0x48, 0x45, 0x88, 0x9c, 0xac, 0x99, 0xf9, 0xef, 0x6f, 0xfe,
	0xab, 0x19, 0x2f, 0xbc, 0xf0, 0x19, 0x0f, 0x19, 0x37, 0xc4, 0x9d, 0xc1, 0x69, 0x10, 0xd1, 0x28,
	0x30, 0xbe, 0x9d, 0x7b, 0x44, 0xb8, 0xe7, 0x2a, 0xc6, 0x71, 0xc2, 0x04, 0x43, 0xcd, 0x5c, 0x88,
	0xc5, 0x1d, 0x56, 0x85, 0x8d, 0x50, 0xef, 0x6c, 0x18, 0x7e, 0x92, 0xc5, 0x82, 0x19, 0x61, 0xba,
	0x12, 0x94, 0xd3, 0x1d, 0x48, 0x25, 0x72, 0x92, 0xde, 0x0c, 0x18, 0x0b, 0x56, 0xc4, 0x90, 0x91,
	0x97, 0xde, 0x18, 0x6e, 0x94, 0xe5, 0xa5, 0xb3, 0x1b, 0xa8, 0xdb, 0x34, 0x88, 0x5c, 0x91, 0x26,
	0x64, 0x44, 0xb8, 0x9f, 0xd0, 0x58, 0xb0, 0x84, 0xa3, 0x19, 0x00, 0x57, 0x79, 0xde, 0xd0, 0x5a,
	0xc5, 0xf6, 0x49, 0x17, 0xe3, 0xbf, 0x3a, 0xc2, 0xf7, 0x40, 0xac, 0x3d, 0xc2, 0xd9, 0xaf, 0x12,
	0x3c, 0xbe, 0x47, 0x83, 0x7a, 0x00, 0x71, 0xea, 0xad, 0xa8, 0xef, 0xdc, 0x92, 0xac, 0xa1, 0xb5,
	0xb4, 0xf6, 0x49, 0xb7, 0x8e, 0x73, 0xbf, 0x58, 0xf9, 0xc5, 0xfd, 0x28, 0xb3, 0x8e, 0x73, 0xdd,
	0x25, 0xc9, 0xd0, 0x18, 0x4a, 0x4b, 0x57, 0xb8, 0x8d, 0x82, 0x94, 0xf7, 0xfe, 0xcf, 0x16, 0x1e,
	0xb9, 0xc2, 0xb5, 0x24, 0x00, 0xe9, 0x50, 0xe5, 0xe4, 0x6b, 0x4a, 0x22, 0x9f, 0x34, 0x8a, 0x2d,
	0xad, 0x5d, 0xb2, 0xb6, 0xb1, 0xfe, 0xb3, 0x08, 0xa5, 0xb5, 0x14, 0x2d, 0xa0, 0xc2, 0x69, 0x14,
	0xac, 0xc8, 0xc6, 0xde, 0x9b, 0x03, 0xfa, 0x61, 0x5b, 0x12, 0x2e, 0x8e, 0xac, 0x0d, 0x0b, 0x7d,
	0x80, 0xb2, 0x9c, 0xd2, 0xe6, 0x12, 0xaf, 0x0f, 0x81, 0x4e, 0xd7, 0x80, 0x8b, 0x23, 0x2b, 0x27,
	0xe9, 0x0e, 0x54, 0xf2, 0x36, 0xe8, 0x15, 0x94, 0x42, 0xb6, 0xcc, 0x0d, 0x3f, 0xec, 0x3e, 0xff,
	0x07, 0x7b, 0xca, 0x96, 0xc4, 0x92, 0x07, 0xd0, 0x53, 0x38, 0xde, 0x0e, 0x4d, 0x3a, 0x7b, 0x60,
	0xed, 0x12, 0xfa, 0x0f, 0x0d, 0xca, 0xb2, 0x27, 0xba, 0x84, 0xaa, 0x47, 0x85, 0x9b, 0x24, 0xae,
	0x1a, 0x9a, 0xa1, 0x9a, 0xe4, 0x3b, 0x89, 0xb7, 0x2b, 0xa8, 0x3a, 0x0d, 0x59, 0x18, 0xbb, 0xbe,
	0x18, 0x50, 0xd1, 0x5f, 0x1f, 0xb3, 0xb6, 0x00, 0x64, 0xff, 0xb1, 0x6b, 0x05, 0xb9, 0x6b, 0x07,
	0x0d, 0x75, 0x0f, 0x33, 0x28, 0x43, 0x91, 0xa7, 0xe1, 0x4b, 0x0e, 0x55, 0x75, 0x45, 0xd4, 0x84,
	0x53, 0x7b, 0x32, 0x9e, 0x39, 0xd3, 0xf9, 0xc8, 0x74, 0xae, 0x67, 0xf6, 0x7b, 0x73, 0x38, 0x79,
	0x3b, 0x31, 0x47, 0xb5, 0x23, 0x54, 0x87, 0xda, 0xae, 0x34, 0x9a, 0x58, 0xe6, 0x70, 0x51, 0xd3,
	0xd0, 0x29, 0x3c, 0xda, 0x65, 0x17, 0xe6, 0xc7, 0xc5, 0x75, 0xff, 0xaa, 0x56, 0x40, 0xcf, 0xe0,
	0xc9, 0x2e, 0x7d, 0x65, 0x8e, 0xfb, 0xc3, 0x4f, 0x4e, 0x7f, 0x3a, 0x99, 0xcd, 0x9d, 0x77, 0xf6,
	0x7c, 0x56, 0xfb, 0x3e, 0x30, 0x3e, 0x77, 0x02, 0x2a, 0xbe, 0xa4, 0x1e, 0xf6, 0x59, 0x68, 0xa8,
	0x7f, 0x55, 0x7e, 0x3a, 0x7c, 0x79, 0x6b, 0x88, 0x2c, 0x26, 0xfb, 0x0f, 0x80, 0x57, 0x91, 0x9b,
	0xde, 0xfb, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xbe, 0x6a, 0x3b, 0x7e, 0x1c, 0x04, 0x00, 0x00,
}
