// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cosmos/base/snapshots/v1beta1/snapshot.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Snapshot contains Tendermint state sync snapshot info.
type Snapshot struct {
	Height               uint64    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Format               uint32    `protobuf:"varint,2,opt,name=format,proto3" json:"format,omitempty"`
	Chunks               uint32    `protobuf:"varint,3,opt,name=chunks,proto3" json:"chunks,omitempty"`
	Hash                 []byte    `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	Metadata             *Metadata `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Snapshot) Reset()         { *m = Snapshot{} }
func (m *Snapshot) String() string { return proto.CompactTextString(m) }
func (*Snapshot) ProtoMessage()    {}
func (*Snapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd7a3c9b0a19e1ee, []int{0}
}

func (m *Snapshot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Snapshot.Unmarshal(m, b)
}
func (m *Snapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Snapshot.Marshal(b, m, deterministic)
}
func (m *Snapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Snapshot.Merge(m, src)
}
func (m *Snapshot) XXX_Size() int {
	return xxx_messageInfo_Snapshot.Size(m)
}
func (m *Snapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_Snapshot.DiscardUnknown(m)
}

var xxx_messageInfo_Snapshot proto.InternalMessageInfo

func (m *Snapshot) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Snapshot) GetFormat() uint32 {
	if m != nil {
		return m.Format
	}
	return 0
}

func (m *Snapshot) GetChunks() uint32 {
	if m != nil {
		return m.Chunks
	}
	return 0
}

func (m *Snapshot) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Snapshot) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// Metadata contains SDK-specific snapshot metadata.
type Metadata struct {
	ChunkHashes          [][]byte `protobuf:"bytes,1,rep,name=chunk_hashes,json=chunkHashes,proto3" json:"chunk_hashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd7a3c9b0a19e1ee, []int{1}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetChunkHashes() [][]byte {
	if m != nil {
		return m.ChunkHashes
	}
	return nil
}

func init() {
	proto.RegisterType((*Snapshot)(nil), "cosmos.base.snapshots.v1beta1.Snapshot")
	proto.RegisterType((*Metadata)(nil), "cosmos.base.snapshots.v1beta1.Metadata")
}

func init() {
	proto.RegisterFile("cosmos/base/snapshots/v1beta1/snapshot.proto", fileDescriptor_dd7a3c9b0a19e1ee)
}

var fileDescriptor_dd7a3c9b0a19e1ee = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x3f, 0x4e, 0xc3, 0x30,
	0x14, 0xc6, 0x31, 0x0d, 0x55, 0xe4, 0x86, 0xc5, 0x42, 0xc8, 0x42, 0x42, 0x98, 0x2e, 0x78, 0x68,
	0x6d, 0x15, 0x6e, 0xd0, 0x09, 0x06, 0x16, 0xb3, 0xb1, 0x20, 0x27, 0x35, 0x71, 0x55, 0xa5, 0x8e,
	0xfa, 0x1c, 0x24, 0x8e, 0xc5, 0x2d, 0x38, 0x05, 0x67, 0x41, 0xfe, 0x43, 0xc4, 0xd4, 0x29, 0xef,
	0xfb, 0xe5, 0xf7, 0xf4, 0xac, 0x0f, 0x2f, 0x1a, 0x07, 0x9d, 0x03, 0x59, 0x6b, 0x30, 0x12, 0xf6,
	0xba, 0x07, 0xeb, 0x3c, 0xc8, 0x8f, 0x55, 0x6d, 0xbc, 0x5e, 0x8d, 0x44, 0xf4, 0x07, 0xe7, 0x1d,
	0xb9, 0x4e, 0xb6, 0x08, 0xb6, 0x18, 0x6d, 0x91, 0xed, 0xab, 0x8b, 0xd6, 0xb5, 0x2e, 0x9a, 0x32,
	0x4c, 0x69, 0x69, 0xfe, 0x85, 0x70, 0xf9, 0x92, 0x5d, 0x72, 0x89, 0xa7, 0xd6, 0x6c, 0x5b, 0xeb,
	0x29, 0x62, 0x88, 0x17, 0x2a, 0xa7, 0xc0, 0xdf, 0xdd, 0xa1, 0xd3, 0x9e, 0x9e, 0x32, 0xc4, 0xcf,
	0x55, 0x4e, 0x81, 0x37, 0x76, 0xd8, 0xef, 0x80, 0x4e, 0x12, 0x4f, 0x89, 0x10, 0x5c, 0x58, 0x0d,
	0x96, 0x16, 0x0c, 0xf1, 0x4a, 0xc5, 0x99, 0x3c, 0xe1, 0xb2, 0x33, 0x5e, 0x6f, 0xb4, 0xd7, 0xf4,
	0x8c, 0x21, 0x3e, 0xbb, 0xbf, 0x13, 0x47, 0x1f, 0x2c, 0x9e, 0xb3, 0xbe, 0x2e, 0xbe, 0x7f, 0x6e,
	0x4e, 0xd4, 0xb8, 0x3e, 0x5f, 0xe2, 0xf2, 0xef, 0x1f, 0xb9, 0xc5, 0x55, 0x3c, 0xfa, 0x16, 0x8e,
	0x18, 0xa0, 0x88, 0x4d, 0x78, 0xa5, 0x66, 0x91, 0x3d, 0x46, 0xb4, 0x16, 0xaf, 0x8b, 0x76, 0xeb,
	0xed, 0x50, 0x8b, 0xc6, 0x75, 0x32, 0x57, 0x9a, 0x3e, 0x4b, 0xd8, 0xec, 0xfe, 0x15, 0xeb, 0x3f,
	0x7b, 0x03, 0xf5, 0x34, 0x36, 0xf3, 0xf0, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x92, 0x8a, 0x27, 0x36,
	0x7e, 0x01, 0x00, 0x00,
}
