// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cosmos/mint/v1beta1/query.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is the request type for the Query/Params RPC method.
type QueryParamsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a1e393be338aea, []int{0}
}

func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryParamsRequest.Unmarshal(m, b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return xxx_messageInfo_QueryParamsRequest.Size(m)
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is the response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params defines the parameters of the module.
	Params               *Params  `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a1e393be338aea, []int{1}
}

func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryParamsResponse.Unmarshal(m, b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return xxx_messageInfo_QueryParamsResponse.Size(m)
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() *Params {
	if m != nil {
		return m.Params
	}
	return nil
}

// QueryInflationRequest is the request type for the Query/Inflation RPC method.
type QueryInflationRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryInflationRequest) Reset()         { *m = QueryInflationRequest{} }
func (m *QueryInflationRequest) String() string { return proto.CompactTextString(m) }
func (*QueryInflationRequest) ProtoMessage()    {}
func (*QueryInflationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a1e393be338aea, []int{2}
}

func (m *QueryInflationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryInflationRequest.Unmarshal(m, b)
}
func (m *QueryInflationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryInflationRequest.Marshal(b, m, deterministic)
}
func (m *QueryInflationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryInflationRequest.Merge(m, src)
}
func (m *QueryInflationRequest) XXX_Size() int {
	return xxx_messageInfo_QueryInflationRequest.Size(m)
}
func (m *QueryInflationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryInflationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryInflationRequest proto.InternalMessageInfo

// QueryInflationResponse is the response type for the Query/Inflation RPC
// method.
type QueryInflationResponse struct {
	// inflation is the current minting inflation value.
	Inflation            []byte   `protobuf:"bytes,1,opt,name=inflation,proto3" json:"inflation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryInflationResponse) Reset()         { *m = QueryInflationResponse{} }
func (m *QueryInflationResponse) String() string { return proto.CompactTextString(m) }
func (*QueryInflationResponse) ProtoMessage()    {}
func (*QueryInflationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a1e393be338aea, []int{3}
}

func (m *QueryInflationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryInflationResponse.Unmarshal(m, b)
}
func (m *QueryInflationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryInflationResponse.Marshal(b, m, deterministic)
}
func (m *QueryInflationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryInflationResponse.Merge(m, src)
}
func (m *QueryInflationResponse) XXX_Size() int {
	return xxx_messageInfo_QueryInflationResponse.Size(m)
}
func (m *QueryInflationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryInflationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryInflationResponse proto.InternalMessageInfo

func (m *QueryInflationResponse) GetInflation() []byte {
	if m != nil {
		return m.Inflation
	}
	return nil
}

// QueryAnnualProvisionsRequest is the request type for the
// Query/AnnualProvisions RPC method.
type QueryAnnualProvisionsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryAnnualProvisionsRequest) Reset()         { *m = QueryAnnualProvisionsRequest{} }
func (m *QueryAnnualProvisionsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAnnualProvisionsRequest) ProtoMessage()    {}
func (*QueryAnnualProvisionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a1e393be338aea, []int{4}
}

func (m *QueryAnnualProvisionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryAnnualProvisionsRequest.Unmarshal(m, b)
}
func (m *QueryAnnualProvisionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryAnnualProvisionsRequest.Marshal(b, m, deterministic)
}
func (m *QueryAnnualProvisionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAnnualProvisionsRequest.Merge(m, src)
}
func (m *QueryAnnualProvisionsRequest) XXX_Size() int {
	return xxx_messageInfo_QueryAnnualProvisionsRequest.Size(m)
}
func (m *QueryAnnualProvisionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAnnualProvisionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAnnualProvisionsRequest proto.InternalMessageInfo

// QueryAnnualProvisionsResponse is the response type for the
// Query/AnnualProvisions RPC method.
type QueryAnnualProvisionsResponse struct {
	// annual_provisions is the current minting annual provisions value.
	AnnualProvisions     []byte   `protobuf:"bytes,1,opt,name=annual_provisions,json=annualProvisions,proto3" json:"annual_provisions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryAnnualProvisionsResponse) Reset()         { *m = QueryAnnualProvisionsResponse{} }
func (m *QueryAnnualProvisionsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAnnualProvisionsResponse) ProtoMessage()    {}
func (*QueryAnnualProvisionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a1e393be338aea, []int{5}
}

func (m *QueryAnnualProvisionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryAnnualProvisionsResponse.Unmarshal(m, b)
}
func (m *QueryAnnualProvisionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryAnnualProvisionsResponse.Marshal(b, m, deterministic)
}
func (m *QueryAnnualProvisionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAnnualProvisionsResponse.Merge(m, src)
}
func (m *QueryAnnualProvisionsResponse) XXX_Size() int {
	return xxx_messageInfo_QueryAnnualProvisionsResponse.Size(m)
}
func (m *QueryAnnualProvisionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAnnualProvisionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAnnualProvisionsResponse proto.InternalMessageInfo

func (m *QueryAnnualProvisionsResponse) GetAnnualProvisions() []byte {
	if m != nil {
		return m.AnnualProvisions
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "cosmos.mint.v1beta1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "cosmos.mint.v1beta1.QueryParamsResponse")
	proto.RegisterType((*QueryInflationRequest)(nil), "cosmos.mint.v1beta1.QueryInflationRequest")
	proto.RegisterType((*QueryInflationResponse)(nil), "cosmos.mint.v1beta1.QueryInflationResponse")
	proto.RegisterType((*QueryAnnualProvisionsRequest)(nil), "cosmos.mint.v1beta1.QueryAnnualProvisionsRequest")
	proto.RegisterType((*QueryAnnualProvisionsResponse)(nil), "cosmos.mint.v1beta1.QueryAnnualProvisionsResponse")
}

func init() { proto.RegisterFile("cosmos/mint/v1beta1/query.proto", fileDescriptor_d0a1e393be338aea) }

var fileDescriptor_d0a1e393be338aea = []byte{
	// 420 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x3b, 0x6f, 0xdb, 0x30,
	0x18, 0xac, 0xfa, 0x30, 0x60, 0xb6, 0x83, 0x4b, 0xbb, 0x0f, 0xc8, 0x4f, 0xa8, 0x80, 0xeb, 0xd6,
	0x28, 0x09, 0xbb, 0x53, 0xc7, 0x1a, 0x59, 0x02, 0x64, 0x70, 0x3c, 0x26, 0x43, 0x40, 0x3b, 0xb4,
	0x22, 0xc4, 0x22, 0x65, 0x91, 0x32, 0x62, 0x20, 0x43, 0x90, 0x39, 0x5b, 0x7e, 0x45, 0x7e, 0x48,
	0x80, 0xec, 0xd9, 0x32, 0x78, 0xca, 0x0f, 0x09, 0x44, 0xd2, 0x0e, 0x22, 0x4b, 0x79, 0x4d, 0x36,
	0x78, 0xc7, 0xbb, 0xe3, 0x77, 0x9f, 0x40, 0x7d, 0xc4, 0x85, 0xcf, 0x05, 0xf6, 0x3d, 0x26, 0xf1,
	0xac, 0x33, 0xa4, 0x92, 0x74, 0xf0, 0x34, 0xa2, 0xe1, 0x1c, 0x05, 0x21, 0x97, 0x1c, 0x16, 0x35,
	0x01, 0xc5, 0x04, 0x64, 0x08, 0x76, 0xc9, 0xe5, 0x2e, 0x57, 0x38, 0x8e, 0xff, 0x69, 0xaa, 0x5d,
	0x71, 0x39, 0x77, 0x27, 0x14, 0x93, 0xc0, 0xc3, 0x84, 0x31, 0x2e, 0x89, 0xf4, 0x38, 0x13, 0x06,
	0xad, 0xa5, 0x39, 0x29, 0x55, 0x85, 0x3b, 0x25, 0x00, 0xb7, 0x63, 0xdf, 0x3e, 0x09, 0x89, 0x2f,
	0x06, 0x74, 0x1a, 0x51, 0x21, 0x9d, 0x3e, 0x28, 0x3e, 0x38, 0x15, 0x01, 0x67, 0x82, 0xc2, 0x7f,
	0x20, 0x17, 0xa8, 0x93, 0xef, 0x56, 0xc3, 0x6a, 0x7d, 0xec, 0x96, 0x51, 0x4a, 0x4c, 0xa4, 0x2f,
	0xf5, 0xde, 0x5f, 0x2d, 0xea, 0x6f, 0x06, 0xe6, 0x82, 0xf3, 0x0d, 0x7c, 0x51, 0x8a, 0x9b, 0x6c,
	0x3c, 0x51, 0x01, 0x97, 0x56, 0x63, 0xf0, 0x35, 0x09, 0x18, 0xb7, 0x2d, 0x90, 0xf7, 0x96, 0x87,
	0xca, 0xf0, 0x53, 0x0f, 0xc5, 0x9a, 0x37, 0x8b, 0x7a, 0xd3, 0xf5, 0xe4, 0x41, 0x34, 0x44, 0x23,
	0xee, 0x63, 0xf3, 0x40, 0xfd, 0xf3, 0x47, 0xec, 0x1f, 0x62, 0x39, 0x0f, 0xa8, 0x40, 0x1b, 0x74,
	0x34, 0xb8, 0x17, 0x70, 0x6a, 0xa0, 0xa2, 0x7c, 0xfe, 0x33, 0x16, 0x91, 0x49, 0x3f, 0xe4, 0x33,
	0x4f, 0xc4, 0x73, 0x5a, 0xe6, 0x38, 0x06, 0xd5, 0x0c, 0xdc, 0xc4, 0xd9, 0x05, 0x9f, 0x89, 0xc2,
	0xf6, 0x82, 0x15, 0xf8, 0xca, 0x58, 0x05, 0x92, 0x30, 0xe9, 0x5e, 0xbe, 0x03, 0x1f, 0x94, 0x3d,
	0x3c, 0xb1, 0x40, 0x4e, 0x4f, 0x10, 0xfe, 0x4c, 0x1d, 0xef, 0x7a, 0x5d, 0x76, 0xeb, 0x69, 0xa2,
	0x7e, 0x84, 0xf3, 0xe3, 0xf4, 0xfa, 0xf6, 0xfc, 0x6d, 0x15, 0x96, 0x71, 0xda, 0x5e, 0xe8, 0xae,
	0xe0, 0x99, 0x05, 0xf2, 0xab, 0x3a, 0xe0, 0xef, 0x6c, 0xf1, 0x64, 0x99, 0x76, 0xfb, 0x59, 0x5c,
	0x93, 0xa5, 0xa9, 0xb2, 0x34, 0x60, 0x2d, 0x35, 0xcb, 0xaa, 0x39, 0x78, 0x61, 0x81, 0x42, 0xb2,
	0x15, 0xd8, 0xc9, 0x76, 0xca, 0x68, 0xd8, 0xee, 0xbe, 0xe4, 0x8a, 0xc9, 0x88, 0x54, 0xc6, 0x16,
	0x6c, 0xa6, 0x66, 0x5c, 0xdb, 0x87, 0x5e, 0x7b, 0xe7, 0xd7, 0xa3, 0x3b, 0x70, 0xa4, 0x05, 0xd4,
	0x2a, 0x0c, 0x73, 0xea, 0x13, 0xfc, 0x7b, 0x17, 0x00, 0x00, 0xff, 0xff, 0x5b, 0x89, 0x82, 0x04,
	0x0e, 0x04, 0x00, 0x00,
}
