// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kira/gov/allowed_messages.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// defines allowed messages by network status, we only use this for poor network where
// number of validators is less than min_validators network property
type AllowedMessages struct {
	Messages             []string `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllowedMessages) Reset()         { *m = AllowedMessages{} }
func (m *AllowedMessages) String() string { return proto.CompactTextString(m) }
func (*AllowedMessages) ProtoMessage()    {}
func (*AllowedMessages) Descriptor() ([]byte, []int) {
	return fileDescriptor_c40df6bae73197f9, []int{0}
}

func (m *AllowedMessages) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllowedMessages.Unmarshal(m, b)
}
func (m *AllowedMessages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllowedMessages.Marshal(b, m, deterministic)
}
func (m *AllowedMessages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllowedMessages.Merge(m, src)
}
func (m *AllowedMessages) XXX_Size() int {
	return xxx_messageInfo_AllowedMessages.Size(m)
}
func (m *AllowedMessages) XXX_DiscardUnknown() {
	xxx_messageInfo_AllowedMessages.DiscardUnknown(m)
}

var xxx_messageInfo_AllowedMessages proto.InternalMessageInfo

func (m *AllowedMessages) GetMessages() []string {
	if m != nil {
		return m.Messages
	}
	return nil
}

func init() {
	proto.RegisterType((*AllowedMessages)(nil), "kira.gov.AllowedMessages")
}

func init() { proto.RegisterFile("kira/gov/allowed_messages.proto", fileDescriptor_c40df6bae73197f9) }

var fileDescriptor_c40df6bae73197f9 = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xcf, 0xce, 0x2c, 0x4a,
	0xd4, 0x4f, 0xcf, 0x2f, 0xd3, 0x4f, 0xcc, 0xc9, 0xc9, 0x2f, 0x4f, 0x4d, 0x89, 0xcf, 0x4d, 0x2d,
	0x2e, 0x4e, 0x4c, 0x4f, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x29, 0xd0,
	0x4b, 0xcf, 0x2f, 0x93, 0x12, 0x49, 0xcf, 0x4f, 0xcf, 0x07, 0x0b, 0xea, 0x83, 0x58, 0x10, 0x79,
	0x25, 0x5d, 0x2e, 0x7e, 0x47, 0x88, 0x4e, 0x5f, 0xa8, 0x46, 0x21, 0x29, 0x2e, 0x0e, 0x98, 0x21,
	0x12, 0x8c, 0x0a, 0xcc, 0x1a, 0x9c, 0x41, 0x70, 0xbe, 0x93, 0x7a, 0x94, 0x6a, 0x7a, 0x66, 0x49,
	0x46, 0x69, 0x92, 0x5e, 0x72, 0x7e, 0xae, 0xbe, 0x77, 0x66, 0x51, 0xa2, 0x73, 0x7e, 0x51, 0xaa,
	0x7e, 0x71, 0x6a, 0x76, 0x62, 0xa6, 0x7e, 0x05, 0xd8, 0x21, 0x25, 0x95, 0x05, 0xa9, 0xc5, 0x49,
	0x6c, 0x60, 0xe3, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf5, 0x00, 0x06, 0xd4, 0xa1, 0x00,
	0x00, 0x00,
}
