// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kira/gov/identity_registrar.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IdentityRecord struct {
	Id                   uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address              string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Key                  string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value                string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Date                 *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	Verifiers            []string               `protobuf:"bytes,6,rep,name=verifiers,proto3" json:"verifiers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *IdentityRecord) Reset()         { *m = IdentityRecord{} }
func (m *IdentityRecord) String() string { return proto.CompactTextString(m) }
func (*IdentityRecord) ProtoMessage()    {}
func (*IdentityRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf2821c6a2456955, []int{0}
}

func (m *IdentityRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdentityRecord.Unmarshal(m, b)
}
func (m *IdentityRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdentityRecord.Marshal(b, m, deterministic)
}
func (m *IdentityRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdentityRecord.Merge(m, src)
}
func (m *IdentityRecord) XXX_Size() int {
	return xxx_messageInfo_IdentityRecord.Size(m)
}
func (m *IdentityRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_IdentityRecord.DiscardUnknown(m)
}

var xxx_messageInfo_IdentityRecord proto.InternalMessageInfo

func (m *IdentityRecord) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *IdentityRecord) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *IdentityRecord) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *IdentityRecord) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *IdentityRecord) GetDate() *timestamppb.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *IdentityRecord) GetVerifiers() []string {
	if m != nil {
		return m.Verifiers
	}
	return nil
}

type IdentityInfoEntry struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Info                 string   `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdentityInfoEntry) Reset()         { *m = IdentityInfoEntry{} }
func (m *IdentityInfoEntry) String() string { return proto.CompactTextString(m) }
func (*IdentityInfoEntry) ProtoMessage()    {}
func (*IdentityInfoEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf2821c6a2456955, []int{1}
}

func (m *IdentityInfoEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdentityInfoEntry.Unmarshal(m, b)
}
func (m *IdentityInfoEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdentityInfoEntry.Marshal(b, m, deterministic)
}
func (m *IdentityInfoEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdentityInfoEntry.Merge(m, src)
}
func (m *IdentityInfoEntry) XXX_Size() int {
	return xxx_messageInfo_IdentityInfoEntry.Size(m)
}
func (m *IdentityInfoEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_IdentityInfoEntry.DiscardUnknown(m)
}

var xxx_messageInfo_IdentityInfoEntry proto.InternalMessageInfo

func (m *IdentityInfoEntry) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *IdentityInfoEntry) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

type MsgRegisterIdentityRecords struct {
	Address              []byte               `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Infos                []*IdentityInfoEntry `protobuf:"bytes,2,rep,name=infos,proto3" json:"infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MsgRegisterIdentityRecords) Reset()         { *m = MsgRegisterIdentityRecords{} }
func (m *MsgRegisterIdentityRecords) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterIdentityRecords) ProtoMessage()    {}
func (*MsgRegisterIdentityRecords) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf2821c6a2456955, []int{2}
}

func (m *MsgRegisterIdentityRecords) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgRegisterIdentityRecords.Unmarshal(m, b)
}
func (m *MsgRegisterIdentityRecords) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgRegisterIdentityRecords.Marshal(b, m, deterministic)
}
func (m *MsgRegisterIdentityRecords) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterIdentityRecords.Merge(m, src)
}
func (m *MsgRegisterIdentityRecords) XXX_Size() int {
	return xxx_messageInfo_MsgRegisterIdentityRecords.Size(m)
}
func (m *MsgRegisterIdentityRecords) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterIdentityRecords.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterIdentityRecords proto.InternalMessageInfo

func (m *MsgRegisterIdentityRecords) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *MsgRegisterIdentityRecords) GetInfos() []*IdentityInfoEntry {
	if m != nil {
		return m.Infos
	}
	return nil
}

type MsgDeleteIdentityRecords struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Keys                 []string `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgDeleteIdentityRecords) Reset()         { *m = MsgDeleteIdentityRecords{} }
func (m *MsgDeleteIdentityRecords) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteIdentityRecords) ProtoMessage()    {}
func (*MsgDeleteIdentityRecords) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf2821c6a2456955, []int{3}
}

func (m *MsgDeleteIdentityRecords) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgDeleteIdentityRecords.Unmarshal(m, b)
}
func (m *MsgDeleteIdentityRecords) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgDeleteIdentityRecords.Marshal(b, m, deterministic)
}
func (m *MsgDeleteIdentityRecords) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteIdentityRecords.Merge(m, src)
}
func (m *MsgDeleteIdentityRecords) XXX_Size() int {
	return xxx_messageInfo_MsgDeleteIdentityRecords.Size(m)
}
func (m *MsgDeleteIdentityRecords) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteIdentityRecords.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteIdentityRecords proto.InternalMessageInfo

func (m *MsgDeleteIdentityRecords) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *MsgDeleteIdentityRecords) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

type IdentityRecordsVerify struct {
	Id                   uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address              string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Verifier             string                 `protobuf:"bytes,3,opt,name=verifier,proto3" json:"verifier,omitempty"`
	RecordIds            []uint64               `protobuf:"varint,4,rep,packed,name=recordIds,proto3" json:"recordIds,omitempty"`
	Tip                  string                 `protobuf:"bytes,5,opt,name=tip,proto3" json:"tip,omitempty"`
	LastRecordEditDate   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=lastRecordEditDate,proto3" json:"lastRecordEditDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *IdentityRecordsVerify) Reset()         { *m = IdentityRecordsVerify{} }
func (m *IdentityRecordsVerify) String() string { return proto.CompactTextString(m) }
func (*IdentityRecordsVerify) ProtoMessage()    {}
func (*IdentityRecordsVerify) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf2821c6a2456955, []int{4}
}

func (m *IdentityRecordsVerify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdentityRecordsVerify.Unmarshal(m, b)
}
func (m *IdentityRecordsVerify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdentityRecordsVerify.Marshal(b, m, deterministic)
}
func (m *IdentityRecordsVerify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdentityRecordsVerify.Merge(m, src)
}
func (m *IdentityRecordsVerify) XXX_Size() int {
	return xxx_messageInfo_IdentityRecordsVerify.Size(m)
}
func (m *IdentityRecordsVerify) XXX_DiscardUnknown() {
	xxx_messageInfo_IdentityRecordsVerify.DiscardUnknown(m)
}

var xxx_messageInfo_IdentityRecordsVerify proto.InternalMessageInfo

func (m *IdentityRecordsVerify) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *IdentityRecordsVerify) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *IdentityRecordsVerify) GetVerifier() string {
	if m != nil {
		return m.Verifier
	}
	return ""
}

func (m *IdentityRecordsVerify) GetRecordIds() []uint64 {
	if m != nil {
		return m.RecordIds
	}
	return nil
}

func (m *IdentityRecordsVerify) GetTip() string {
	if m != nil {
		return m.Tip
	}
	return ""
}

func (m *IdentityRecordsVerify) GetLastRecordEditDate() *timestamppb.Timestamp {
	if m != nil {
		return m.LastRecordEditDate
	}
	return nil
}

type MsgRequestIdentityRecordsVerify struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Verifier             []byte   `protobuf:"bytes,2,opt,name=verifier,proto3" json:"verifier,omitempty"`
	RecordIds            []uint64 `protobuf:"varint,3,rep,packed,name=recordIds,proto3" json:"recordIds,omitempty"`
	Tip                  string   `protobuf:"bytes,4,opt,name=tip,proto3" json:"tip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgRequestIdentityRecordsVerify) Reset()         { *m = MsgRequestIdentityRecordsVerify{} }
func (m *MsgRequestIdentityRecordsVerify) String() string { return proto.CompactTextString(m) }
func (*MsgRequestIdentityRecordsVerify) ProtoMessage()    {}
func (*MsgRequestIdentityRecordsVerify) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf2821c6a2456955, []int{5}
}

func (m *MsgRequestIdentityRecordsVerify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgRequestIdentityRecordsVerify.Unmarshal(m, b)
}
func (m *MsgRequestIdentityRecordsVerify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgRequestIdentityRecordsVerify.Marshal(b, m, deterministic)
}
func (m *MsgRequestIdentityRecordsVerify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRequestIdentityRecordsVerify.Merge(m, src)
}
func (m *MsgRequestIdentityRecordsVerify) XXX_Size() int {
	return xxx_messageInfo_MsgRequestIdentityRecordsVerify.Size(m)
}
func (m *MsgRequestIdentityRecordsVerify) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRequestIdentityRecordsVerify.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRequestIdentityRecordsVerify proto.InternalMessageInfo

func (m *MsgRequestIdentityRecordsVerify) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *MsgRequestIdentityRecordsVerify) GetVerifier() []byte {
	if m != nil {
		return m.Verifier
	}
	return nil
}

func (m *MsgRequestIdentityRecordsVerify) GetRecordIds() []uint64 {
	if m != nil {
		return m.RecordIds
	}
	return nil
}

func (m *MsgRequestIdentityRecordsVerify) GetTip() string {
	if m != nil {
		return m.Tip
	}
	return ""
}

type MsgHandleIdentityRecordsVerifyRequest struct {
	Verifier             []byte   `protobuf:"bytes,1,opt,name=verifier,proto3" json:"verifier,omitempty"`
	VerifyRequestId      uint64   `protobuf:"varint,2,opt,name=verifyRequestId,proto3" json:"verifyRequestId,omitempty"`
	Yes                  bool     `protobuf:"varint,3,opt,name=yes,proto3" json:"yes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgHandleIdentityRecordsVerifyRequest) Reset()         { *m = MsgHandleIdentityRecordsVerifyRequest{} }
func (m *MsgHandleIdentityRecordsVerifyRequest) String() string { return proto.CompactTextString(m) }
func (*MsgHandleIdentityRecordsVerifyRequest) ProtoMessage()    {}
func (*MsgHandleIdentityRecordsVerifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf2821c6a2456955, []int{6}
}

func (m *MsgHandleIdentityRecordsVerifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgHandleIdentityRecordsVerifyRequest.Unmarshal(m, b)
}
func (m *MsgHandleIdentityRecordsVerifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgHandleIdentityRecordsVerifyRequest.Marshal(b, m, deterministic)
}
func (m *MsgHandleIdentityRecordsVerifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgHandleIdentityRecordsVerifyRequest.Merge(m, src)
}
func (m *MsgHandleIdentityRecordsVerifyRequest) XXX_Size() int {
	return xxx_messageInfo_MsgHandleIdentityRecordsVerifyRequest.Size(m)
}
func (m *MsgHandleIdentityRecordsVerifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgHandleIdentityRecordsVerifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgHandleIdentityRecordsVerifyRequest proto.InternalMessageInfo

func (m *MsgHandleIdentityRecordsVerifyRequest) GetVerifier() []byte {
	if m != nil {
		return m.Verifier
	}
	return nil
}

func (m *MsgHandleIdentityRecordsVerifyRequest) GetVerifyRequestId() uint64 {
	if m != nil {
		return m.VerifyRequestId
	}
	return 0
}

func (m *MsgHandleIdentityRecordsVerifyRequest) GetYes() bool {
	if m != nil {
		return m.Yes
	}
	return false
}

type MsgCancelIdentityRecordsVerifyRequest struct {
	Executor             []byte   `protobuf:"bytes,1,opt,name=executor,proto3" json:"executor,omitempty"`
	VerifyRequestId      uint64   `protobuf:"varint,2,opt,name=verifyRequestId,proto3" json:"verifyRequestId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgCancelIdentityRecordsVerifyRequest) Reset()         { *m = MsgCancelIdentityRecordsVerifyRequest{} }
func (m *MsgCancelIdentityRecordsVerifyRequest) String() string { return proto.CompactTextString(m) }
func (*MsgCancelIdentityRecordsVerifyRequest) ProtoMessage()    {}
func (*MsgCancelIdentityRecordsVerifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf2821c6a2456955, []int{7}
}

func (m *MsgCancelIdentityRecordsVerifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCancelIdentityRecordsVerifyRequest.Unmarshal(m, b)
}
func (m *MsgCancelIdentityRecordsVerifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCancelIdentityRecordsVerifyRequest.Marshal(b, m, deterministic)
}
func (m *MsgCancelIdentityRecordsVerifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCancelIdentityRecordsVerifyRequest.Merge(m, src)
}
func (m *MsgCancelIdentityRecordsVerifyRequest) XXX_Size() int {
	return xxx_messageInfo_MsgCancelIdentityRecordsVerifyRequest.Size(m)
}
func (m *MsgCancelIdentityRecordsVerifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCancelIdentityRecordsVerifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCancelIdentityRecordsVerifyRequest proto.InternalMessageInfo

func (m *MsgCancelIdentityRecordsVerifyRequest) GetExecutor() []byte {
	if m != nil {
		return m.Executor
	}
	return nil
}

func (m *MsgCancelIdentityRecordsVerifyRequest) GetVerifyRequestId() uint64 {
	if m != nil {
		return m.VerifyRequestId
	}
	return 0
}

func init() {
	proto.RegisterType((*IdentityRecord)(nil), "kira.gov.IdentityRecord")
	proto.RegisterType((*IdentityInfoEntry)(nil), "kira.gov.IdentityInfoEntry")
	proto.RegisterType((*MsgRegisterIdentityRecords)(nil), "kira.gov.MsgRegisterIdentityRecords")
	proto.RegisterType((*MsgDeleteIdentityRecords)(nil), "kira.gov.MsgDeleteIdentityRecords")
	proto.RegisterType((*IdentityRecordsVerify)(nil), "kira.gov.IdentityRecordsVerify")
	proto.RegisterType((*MsgRequestIdentityRecordsVerify)(nil), "kira.gov.MsgRequestIdentityRecordsVerify")
	proto.RegisterType((*MsgHandleIdentityRecordsVerifyRequest)(nil), "kira.gov.MsgHandleIdentityRecordsVerifyRequest")
	proto.RegisterType((*MsgCancelIdentityRecordsVerifyRequest)(nil), "kira.gov.MsgCancelIdentityRecordsVerifyRequest")
}

func init() { proto.RegisterFile("kira/gov/identity_registrar.proto", fileDescriptor_cf2821c6a2456955) }

var fileDescriptor_cf2821c6a2456955 = []byte{
	// 627 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0x4f, 0x6b, 0x13, 0x41,
	0x14, 0x77, 0xb3, 0xdb, 0x9a, 0x4c, 0xa5, 0xd5, 0xa1, 0xc2, 0x12, 0x85, 0x8d, 0x0b, 0xa5, 0x7b,
	0xe9, 0x2e, 0xd4, 0x83, 0x7f, 0x6e, 0x4d, 0x5a, 0x30, 0x48, 0x2f, 0x4b, 0xf1, 0x20, 0x88, 0x4e,
	0x77, 0x5e, 0xd6, 0x21, 0x9b, 0x9d, 0x38, 0x33, 0x09, 0xdd, 0x0f, 0x21, 0x78, 0xf0, 0x9b, 0xe8,
	0xc9, 0xab, 0x08, 0x7e, 0x06, 0x0f, 0xf1, 0x3b, 0xf4, 0xe8, 0x49, 0x66, 0x76, 0xd7, 0xb4, 0x35,
	0xc5, 0xb6, 0x50, 0x4f, 0x79, 0xf3, 0x66, 0xde, 0x7b, 0xbf, 0x3f, 0x2f, 0x09, 0x7a, 0x30, 0x64,
	0x82, 0x44, 0x29, 0x9f, 0x46, 0x8c, 0x42, 0xae, 0x98, 0x2a, 0x5e, 0x0b, 0x48, 0x99, 0x54, 0x82,
	0x88, 0x70, 0x2c, 0xb8, 0xe2, 0xb8, 0xa9, 0x9f, 0x84, 0x29, 0x9f, 0xb6, 0xd7, 0x53, 0x9e, 0x72,
	0x93, 0x8c, 0x74, 0x54, 0xde, 0xb7, 0xbd, 0x94, 0xf3, 0x34, 0x83, 0xc8, 0x9c, 0x0e, 0x27, 0x83,
	0x48, 0xb1, 0x11, 0x48, 0x45, 0x46, 0xe3, 0xf2, 0x81, 0xff, 0xc5, 0x42, 0xab, 0xfd, 0xaa, 0x7b,
	0x0c, 0x09, 0x17, 0x14, 0xaf, 0xa2, 0x06, 0xa3, 0xae, 0xd5, 0xb1, 0x02, 0x27, 0x6e, 0x30, 0x8a,
	0x5d, 0x74, 0x93, 0x50, 0x2a, 0x40, 0x4a, 0xb7, 0xd1, 0xb1, 0x82, 0x56, 0x5c, 0x1f, 0xf1, 0x6d,
	0x64, 0x0f, 0xa1, 0x70, 0x6d, 0x93, 0xd5, 0x21, 0x5e, 0x47, 0x4b, 0x53, 0x92, 0x4d, 0xc0, 0x75,
	0x4c, 0xae, 0x3c, 0xe0, 0xc7, 0xc8, 0xa1, 0x44, 0x81, 0xbb, 0xd4, 0xb1, 0x82, 0x95, 0xed, 0x76,
	0x58, 0x82, 0x0a, 0x6b, 0x50, 0xe1, 0x41, 0x0d, 0xaa, 0xdb, 0xfc, 0x3e, 0xf3, 0x6e, 0x7c, 0xf8,
	0xe9, 0x59, 0xb1, 0xa9, 0xc0, 0xf7, 0x51, 0x6b, 0x0a, 0x82, 0x0d, 0x18, 0x08, 0xe9, 0x2e, 0x77,
	0xec, 0xa0, 0x15, 0xcf, 0x13, 0xfe, 0x13, 0x74, 0xa7, 0xc6, 0xde, 0xcf, 0x07, 0x7c, 0x2f, 0x57,
	0xa2, 0xa8, 0x41, 0x59, 0x73, 0x50, 0x18, 0x39, 0x2c, 0x1f, 0xf0, 0x0a, 0xbd, 0x89, 0xfd, 0xcf,
	0x16, 0x6a, 0xef, 0xcb, 0x34, 0x36, 0x7a, 0x82, 0x38, 0x2d, 0x81, 0xc4, 0xaf, 0xe6, 0x9c, 0x75,
	0xa3, 0x5b, 0xdd, 0xde, 0xf1, 0xcc, 0x5b, 0x2d, 0xc8, 0x28, 0x7b, 0xea, 0x57, 0x17, 0xfe, 0xaf,
	0x99, 0xb7, 0x95, 0x32, 0xf5, 0x76, 0x72, 0x18, 0x26, 0x7c, 0x14, 0x25, 0x5c, 0x8e, 0xb8, 0xac,
	0x3e, 0xb6, 0x24, 0x1d, 0x46, 0xaa, 0x18, 0x83, 0x0c, 0x77, 0x92, 0x64, 0xa7, 0xac, 0x98, 0x0b,
	0xf7, 0x08, 0x2d, 0x69, 0x14, 0x5a, 0x50, 0x3b, 0x58, 0xd9, 0xbe, 0x17, 0xd6, 0x36, 0x86, 0x7f,
	0xf1, 0xe9, 0x3a, 0x5a, 0x92, 0xb8, 0x7c, 0xef, 0xbf, 0xb7, 0x90, 0xbb, 0x2f, 0xd3, 0x5d, 0xc8,
	0x40, 0xc1, 0x7f, 0x06, 0x8d, 0x91, 0x33, 0x84, 0xa2, 0xc4, 0xdc, 0x8a, 0x4d, 0xec, 0x7f, 0x6c,
	0xa0, 0xbb, 0x67, 0x60, 0xbc, 0xd0, 0xf6, 0x14, 0x97, 0xd8, 0xa2, 0x36, 0x6a, 0xd6, 0x96, 0x56,
	0xab, 0xf4, 0xe7, 0xac, 0xfd, 0x17, 0xa6, 0x6d, 0x9f, 0x4a, 0xd7, 0xe9, 0xd8, 0x81, 0x13, 0xcf,
	0x13, 0x78, 0x07, 0xd9, 0x8a, 0x8d, 0xcd, 0x5a, 0xb5, 0xba, 0x91, 0xd6, 0xe9, 0xc7, 0xcc, 0xdb,
	0xbc, 0x00, 0xbd, 0x1e, 0x67, 0x79, 0xac, 0x6b, 0xf1, 0x01, 0xc2, 0x19, 0x91, 0xaa, 0xc4, 0xbe,
	0x47, 0x99, 0xda, 0xd5, 0x8b, 0xba, 0x7c, 0x89, 0x45, 0x5d, 0x50, 0xef, 0x7f, 0x6d, 0x20, 0xcf,
	0x6c, 0xd7, 0xbb, 0x09, 0x48, 0xb5, 0x58, 0xa0, 0x6b, 0x76, 0xeb, 0xcd, 0x09, 0x55, 0x1b, 0xa6,
	0xff, 0xee, 0xf1, 0xcc, 0x5b, 0x2b, 0xfb, 0xd7, 0x37, 0x57, 0x18, 0x70, 0x8e, 0x37, 0xf6, 0x39,
	0xde, 0x38, 0x57, 0xf7, 0xc6, 0xff, 0x66, 0xa1, 0x8d, 0x7d, 0x99, 0x3e, 0x23, 0x39, 0xcd, 0x60,
	0xa1, 0x88, 0x95, 0xc0, 0xa7, 0xc8, 0x5a, 0xd7, 0x42, 0x36, 0x40, 0x6b, 0xd3, 0x93, 0x23, 0xfb,
	0xd4, 0xa8, 0xea, 0xc4, 0x67, 0xd3, 0xfa, 0xf7, 0xa7, 0x00, 0x69, 0x36, 0xb9, 0x19, 0xeb, 0xd0,
	0xff, 0x54, 0xf2, 0xe8, 0x91, 0x3c, 0x81, 0xec, 0x5f, 0x3c, 0xe0, 0x08, 0x92, 0x89, 0xe2, 0x0b,
	0x78, 0xd4, 0x37, 0x57, 0xe1, 0x51, 0xd7, 0x5e, 0x9c, 0x47, 0x77, 0xf3, 0xe5, 0xc6, 0x89, 0x21,
	0xcf, 0x99, 0x20, 0x3d, 0x2e, 0x20, 0x92, 0x30, 0x24, 0x2c, 0x3a, 0x32, 0x7f, 0x4b, 0x66, 0xce,
	0xe1, 0xb2, 0xf9, 0x7a, 0x3c, 0xfc, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xae, 0xb9, 0x53, 0x0d, 0xaf,
	0x06, 0x00, 0x00,
}
