// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kira/gov/role.proto

package gov

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreateRole struct {
	Proposer             []byte   `protobuf:"bytes,1,opt,name=proposer,proto3" json:"proposer,omitempty"`
	RoleSid              string   `protobuf:"bytes,2,opt,name=role_sid,json=roleSid,proto3" json:"role_sid,omitempty"`
	RoleDescription      string   `protobuf:"bytes,3,opt,name=role_description,json=roleDescription,proto3" json:"role_description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgCreateRole) Reset()         { *m = MsgCreateRole{} }
func (m *MsgCreateRole) String() string { return proto.CompactTextString(m) }
func (*MsgCreateRole) ProtoMessage()    {}
func (*MsgCreateRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_32fea9d294a1c414, []int{0}
}

func (m *MsgCreateRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCreateRole.Unmarshal(m, b)
}
func (m *MsgCreateRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCreateRole.Marshal(b, m, deterministic)
}
func (m *MsgCreateRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateRole.Merge(m, src)
}
func (m *MsgCreateRole) XXX_Size() int {
	return xxx_messageInfo_MsgCreateRole.Size(m)
}
func (m *MsgCreateRole) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateRole.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateRole proto.InternalMessageInfo

func (m *MsgCreateRole) GetProposer() []byte {
	if m != nil {
		return m.Proposer
	}
	return nil
}

func (m *MsgCreateRole) GetRoleSid() string {
	if m != nil {
		return m.RoleSid
	}
	return ""
}

func (m *MsgCreateRole) GetRoleDescription() string {
	if m != nil {
		return m.RoleDescription
	}
	return ""
}

type MsgAssignRole struct {
	Proposer             []byte   `protobuf:"bytes,1,opt,name=proposer,proto3" json:"proposer,omitempty"`
	Address              []byte   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	RoleId               uint32   `protobuf:"varint,3,opt,name=roleId,proto3" json:"roleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgAssignRole) Reset()         { *m = MsgAssignRole{} }
func (m *MsgAssignRole) String() string { return proto.CompactTextString(m) }
func (*MsgAssignRole) ProtoMessage()    {}
func (*MsgAssignRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_32fea9d294a1c414, []int{1}
}

func (m *MsgAssignRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgAssignRole.Unmarshal(m, b)
}
func (m *MsgAssignRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgAssignRole.Marshal(b, m, deterministic)
}
func (m *MsgAssignRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAssignRole.Merge(m, src)
}
func (m *MsgAssignRole) XXX_Size() int {
	return xxx_messageInfo_MsgAssignRole.Size(m)
}
func (m *MsgAssignRole) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAssignRole.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAssignRole proto.InternalMessageInfo

func (m *MsgAssignRole) GetProposer() []byte {
	if m != nil {
		return m.Proposer
	}
	return nil
}

func (m *MsgAssignRole) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *MsgAssignRole) GetRoleId() uint32 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

type MsgRemoveRole struct {
	Proposer             []byte   `protobuf:"bytes,1,opt,name=proposer,proto3" json:"proposer,omitempty"`
	Address              []byte   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	RoleId               uint32   `protobuf:"varint,3,opt,name=roleId,proto3" json:"roleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgRemoveRole) Reset()         { *m = MsgRemoveRole{} }
func (m *MsgRemoveRole) String() string { return proto.CompactTextString(m) }
func (*MsgRemoveRole) ProtoMessage()    {}
func (*MsgRemoveRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_32fea9d294a1c414, []int{2}
}

func (m *MsgRemoveRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgRemoveRole.Unmarshal(m, b)
}
func (m *MsgRemoveRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgRemoveRole.Marshal(b, m, deterministic)
}
func (m *MsgRemoveRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRemoveRole.Merge(m, src)
}
func (m *MsgRemoveRole) XXX_Size() int {
	return xxx_messageInfo_MsgRemoveRole.Size(m)
}
func (m *MsgRemoveRole) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRemoveRole.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRemoveRole proto.InternalMessageInfo

func (m *MsgRemoveRole) GetProposer() []byte {
	if m != nil {
		return m.Proposer
	}
	return nil
}

func (m *MsgRemoveRole) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *MsgRemoveRole) GetRoleId() uint32 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

type MsgWhitelistRolePermission struct {
	Proposer             []byte   `protobuf:"bytes,1,opt,name=proposer,proto3" json:"proposer,omitempty"`
	RoleIdentifier       string   `protobuf:"bytes,2,opt,name=roleIdentifier,proto3" json:"roleIdentifier,omitempty"`
	Permission           uint32   `protobuf:"varint,3,opt,name=permission,proto3" json:"permission,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgWhitelistRolePermission) Reset()         { *m = MsgWhitelistRolePermission{} }
func (m *MsgWhitelistRolePermission) String() string { return proto.CompactTextString(m) }
func (*MsgWhitelistRolePermission) ProtoMessage()    {}
func (*MsgWhitelistRolePermission) Descriptor() ([]byte, []int) {
	return fileDescriptor_32fea9d294a1c414, []int{3}
}

func (m *MsgWhitelistRolePermission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgWhitelistRolePermission.Unmarshal(m, b)
}
func (m *MsgWhitelistRolePermission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgWhitelistRolePermission.Marshal(b, m, deterministic)
}
func (m *MsgWhitelistRolePermission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWhitelistRolePermission.Merge(m, src)
}
func (m *MsgWhitelistRolePermission) XXX_Size() int {
	return xxx_messageInfo_MsgWhitelistRolePermission.Size(m)
}
func (m *MsgWhitelistRolePermission) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWhitelistRolePermission.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWhitelistRolePermission proto.InternalMessageInfo

func (m *MsgWhitelistRolePermission) GetProposer() []byte {
	if m != nil {
		return m.Proposer
	}
	return nil
}

func (m *MsgWhitelistRolePermission) GetRoleIdentifier() string {
	if m != nil {
		return m.RoleIdentifier
	}
	return ""
}

func (m *MsgWhitelistRolePermission) GetPermission() uint32 {
	if m != nil {
		return m.Permission
	}
	return 0
}

type MsgBlacklistRolePermission struct {
	Proposer             []byte   `protobuf:"bytes,1,opt,name=proposer,proto3" json:"proposer,omitempty"`
	RoleIdentifier       string   `protobuf:"bytes,2,opt,name=roleIdentifier,proto3" json:"roleIdentifier,omitempty"`
	Permission           uint32   `protobuf:"varint,3,opt,name=permission,proto3" json:"permission,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgBlacklistRolePermission) Reset()         { *m = MsgBlacklistRolePermission{} }
func (m *MsgBlacklistRolePermission) String() string { return proto.CompactTextString(m) }
func (*MsgBlacklistRolePermission) ProtoMessage()    {}
func (*MsgBlacklistRolePermission) Descriptor() ([]byte, []int) {
	return fileDescriptor_32fea9d294a1c414, []int{4}
}

func (m *MsgBlacklistRolePermission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgBlacklistRolePermission.Unmarshal(m, b)
}
func (m *MsgBlacklistRolePermission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgBlacklistRolePermission.Marshal(b, m, deterministic)
}
func (m *MsgBlacklistRolePermission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBlacklistRolePermission.Merge(m, src)
}
func (m *MsgBlacklistRolePermission) XXX_Size() int {
	return xxx_messageInfo_MsgBlacklistRolePermission.Size(m)
}
func (m *MsgBlacklistRolePermission) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBlacklistRolePermission.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBlacklistRolePermission proto.InternalMessageInfo

func (m *MsgBlacklistRolePermission) GetProposer() []byte {
	if m != nil {
		return m.Proposer
	}
	return nil
}

func (m *MsgBlacklistRolePermission) GetRoleIdentifier() string {
	if m != nil {
		return m.RoleIdentifier
	}
	return ""
}

func (m *MsgBlacklistRolePermission) GetPermission() uint32 {
	if m != nil {
		return m.Permission
	}
	return 0
}

type MsgRemoveWhitelistRolePermission struct {
	Proposer             []byte   `protobuf:"bytes,1,opt,name=proposer,proto3" json:"proposer,omitempty"`
	RoleIdentifier       string   `protobuf:"bytes,2,opt,name=roleIdentifier,proto3" json:"roleIdentifier,omitempty"`
	Permission           uint32   `protobuf:"varint,3,opt,name=permission,proto3" json:"permission,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgRemoveWhitelistRolePermission) Reset()         { *m = MsgRemoveWhitelistRolePermission{} }
func (m *MsgRemoveWhitelistRolePermission) String() string { return proto.CompactTextString(m) }
func (*MsgRemoveWhitelistRolePermission) ProtoMessage()    {}
func (*MsgRemoveWhitelistRolePermission) Descriptor() ([]byte, []int) {
	return fileDescriptor_32fea9d294a1c414, []int{5}
}

func (m *MsgRemoveWhitelistRolePermission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgRemoveWhitelistRolePermission.Unmarshal(m, b)
}
func (m *MsgRemoveWhitelistRolePermission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgRemoveWhitelistRolePermission.Marshal(b, m, deterministic)
}
func (m *MsgRemoveWhitelistRolePermission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRemoveWhitelistRolePermission.Merge(m, src)
}
func (m *MsgRemoveWhitelistRolePermission) XXX_Size() int {
	return xxx_messageInfo_MsgRemoveWhitelistRolePermission.Size(m)
}
func (m *MsgRemoveWhitelistRolePermission) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRemoveWhitelistRolePermission.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRemoveWhitelistRolePermission proto.InternalMessageInfo

func (m *MsgRemoveWhitelistRolePermission) GetProposer() []byte {
	if m != nil {
		return m.Proposer
	}
	return nil
}

func (m *MsgRemoveWhitelistRolePermission) GetRoleIdentifier() string {
	if m != nil {
		return m.RoleIdentifier
	}
	return ""
}

func (m *MsgRemoveWhitelistRolePermission) GetPermission() uint32 {
	if m != nil {
		return m.Permission
	}
	return 0
}

type MsgRemoveBlacklistRolePermission struct {
	Proposer             []byte   `protobuf:"bytes,1,opt,name=proposer,proto3" json:"proposer,omitempty"`
	RoleIdentifier       string   `protobuf:"bytes,2,opt,name=roleIdentifier,proto3" json:"roleIdentifier,omitempty"`
	Permission           uint32   `protobuf:"varint,3,opt,name=permission,proto3" json:"permission,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgRemoveBlacklistRolePermission) Reset()         { *m = MsgRemoveBlacklistRolePermission{} }
func (m *MsgRemoveBlacklistRolePermission) String() string { return proto.CompactTextString(m) }
func (*MsgRemoveBlacklistRolePermission) ProtoMessage()    {}
func (*MsgRemoveBlacklistRolePermission) Descriptor() ([]byte, []int) {
	return fileDescriptor_32fea9d294a1c414, []int{6}
}

func (m *MsgRemoveBlacklistRolePermission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgRemoveBlacklistRolePermission.Unmarshal(m, b)
}
func (m *MsgRemoveBlacklistRolePermission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgRemoveBlacklistRolePermission.Marshal(b, m, deterministic)
}
func (m *MsgRemoveBlacklistRolePermission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRemoveBlacklistRolePermission.Merge(m, src)
}
func (m *MsgRemoveBlacklistRolePermission) XXX_Size() int {
	return xxx_messageInfo_MsgRemoveBlacklistRolePermission.Size(m)
}
func (m *MsgRemoveBlacklistRolePermission) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRemoveBlacklistRolePermission.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRemoveBlacklistRolePermission proto.InternalMessageInfo

func (m *MsgRemoveBlacklistRolePermission) GetProposer() []byte {
	if m != nil {
		return m.Proposer
	}
	return nil
}

func (m *MsgRemoveBlacklistRolePermission) GetRoleIdentifier() string {
	if m != nil {
		return m.RoleIdentifier
	}
	return ""
}

func (m *MsgRemoveBlacklistRolePermission) GetPermission() uint32 {
	if m != nil {
		return m.Permission
	}
	return 0
}

type Role struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sid                  string   `protobuf:"bytes,2,opt,name=sid,proto3" json:"sid,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_32fea9d294a1c414, []int{7}
}

func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (m *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(m, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Role) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *Role) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgCreateRole)(nil), "kira.gov.MsgCreateRole")
	proto.RegisterType((*MsgAssignRole)(nil), "kira.gov.MsgAssignRole")
	proto.RegisterType((*MsgRemoveRole)(nil), "kira.gov.MsgRemoveRole")
	proto.RegisterType((*MsgWhitelistRolePermission)(nil), "kira.gov.MsgWhitelistRolePermission")
	proto.RegisterType((*MsgBlacklistRolePermission)(nil), "kira.gov.MsgBlacklistRolePermission")
	proto.RegisterType((*MsgRemoveWhitelistRolePermission)(nil), "kira.gov.MsgRemoveWhitelistRolePermission")
	proto.RegisterType((*MsgRemoveBlacklistRolePermission)(nil), "kira.gov.MsgRemoveBlacklistRolePermission")
	proto.RegisterType((*Role)(nil), "kira.gov.Role")
}

func init() {
	proto.RegisterFile("kira/gov/role.proto", fileDescriptor_32fea9d294a1c414)
}

var fileDescriptor_32fea9d294a1c414 = []byte{
	// 410 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x94, 0xb1, 0x6e, 0x13, 0x41,
	0x10, 0x86, 0x75, 0x0e, 0x4a, 0xcc, 0x10, 0x9b, 0x68, 0x41, 0xc8, 0xa4, 0x20, 0x96, 0x0b, 0x14,
	0x0a, 0x7b, 0x85, 0xe8, 0xe8, 0x6c, 0xd3, 0x00, 0xb2, 0x84, 0x8e, 0x02, 0x09, 0x09, 0xa1, 0xcb,
	0xed, 0xb0, 0x19, 0xf9, 0xee, 0xe6, 0xb4, 0xb3, 0x58, 0xe4, 0x7d, 0x78, 0x03, 0x2a, 0x1e, 0x84,
	0x36, 0x0f, 0x41, 0x49, 0x85, 0x76, 0x7d, 0xe7, 0x18, 0xa8, 0x90, 0xa0, 0x70, 0xaa, 0xdb, 0xfd,
	0xe6, 0x34, 0xf7, 0xfd, 0xab, 0xbd, 0x81, 0x3b, 0x4b, 0x72, 0x99, 0xb6, 0xbc, 0xd2, 0x8e, 0x0b,
	0x9c, 0xd4, 0x8e, 0x3d, 0xab, 0x6e, 0x80, 0x13, 0xcb, 0xab, 0xe3, 0xbb, 0x96, 0x2d, 0x47, 0xa8,
	0xc3, 0x6a, 0x5d, 0x1f, 0x7d, 0x4e, 0xa0, 0xb7, 0x10, 0x3b, 0x77, 0x98, 0x79, 0x4c, 0xb9, 0x40,
	0xb5, 0x80, 0x6e, 0xed, 0xb8, 0x66, 0x41, 0x37, 0x48, 0x86, 0xc9, 0xe9, 0xe1, 0xec, 0xf1, 0x8f,
	0xcb, 0x93, 0xb1, 0x25, 0x7f, 0xfe, 0xf1, 0x6c, 0x92, 0x73, 0xa9, 0x73, 0x96, 0x92, 0xa5, 0x79,
	0x8c, 0xc5, 0x2c, 0xb5, 0xbf, 0xa8, 0x51, 0x26, 0xd3, 0x3c, 0x9f, 0x1a, 0xe3, 0x50, 0x24, 0xdd,
	0xb4, 0x50, 0xf7, 0xa1, 0x1b, 0x74, 0xde, 0x0b, 0x99, 0x41, 0x67, 0x98, 0x9c, 0xde, 0x4c, 0x0f,
	0xc2, 0xfe, 0x35, 0x19, 0xf5, 0x08, 0x8e, 0x62, 0xc9, 0xa0, 0xe4, 0x8e, 0x6a, 0x4f, 0x5c, 0x0d,
	0xf6, 0xe2, 0x2b, 0xb7, 0x03, 0x7f, 0x76, 0x85, 0x47, 0xdf, 0xd6, 0x9a, 0x53, 0x11, 0xb2, 0xd5,
	0xff, 0xd0, 0x7c, 0x07, 0x07, 0xd9, 0x1a, 0x46, 0xcb, 0xc3, 0xd9, 0xfc, 0xfb, 0xe5, 0x49, 0xff,
	0x22, 0x2b, 0x8b, 0xa7, 0xa3, 0xa6, 0x30, 0xfa, 0xfb, 0xfe, 0x6d, 0x4f, 0x75, 0x0f, 0xf6, 0x43,
	0xa4, 0xe7, 0x26, 0x06, 0xec, 0xa5, 0xcd, 0xae, 0xcd, 0x95, 0x62, 0xc9, 0x2b, 0xbc, 0x46, 0xb9,
	0xbe, 0x24, 0x70, 0xbc, 0x10, 0xfb, 0xe6, 0x9c, 0x3c, 0x16, 0x24, 0x3e, 0x44, 0x7b, 0x85, 0xae,
	0x24, 0x11, 0xe2, 0xea, 0x5f, 0x87, 0x7c, 0x08, 0xfd, 0xf5, 0x77, 0xb1, 0xf2, 0xf4, 0x81, 0xd0,
	0x35, 0x37, 0xed, 0x37, 0xaa, 0x1e, 0x00, 0xd4, 0x1b, 0x89, 0xc6, 0x78, 0x8b, 0xb4, 0xd6, 0xb3,
	0x22, 0xcb, 0x97, 0xbb, 0x63, 0xfd, 0x35, 0x81, 0xe1, 0xe6, 0x0e, 0xed, 0xd8, 0x89, 0xff, 0xe2,
	0xbe, 0x63, 0xe7, 0xfe, 0x02, 0x6e, 0xc4, 0x3f, 0xb6, 0x0f, 0x1d, 0x32, 0x51, 0xac, 0x97, 0x76,
	0xc8, 0xa8, 0x23, 0xd8, 0xbb, 0x1a, 0x76, 0x61, 0xa9, 0x86, 0x70, 0xeb, 0xcf, 0x19, 0xb7, 0x8d,
	0x66, 0xfa, 0xed, 0x76, 0x9c, 0x97, 0xe4, 0xb2, 0x39, 0x3b, 0xd4, 0x54, 0x79, 0x74, 0x9f, 0x74,
	0x1c, 0xd5, 0x63, 0x8b, 0x95, 0x6e, 0x47, 0xfc, 0xd9, 0x7e, 0x64, 0x4f, 0x7e, 0x06, 0x00, 0x00,
	0xff, 0xff, 0xc9, 0xb5, 0x0c, 0x8e, 0xf5, 0x05, 0x00, 0x00,
}
