// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cosmos/capability/v1beta1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// GenesisOwners defines the capability owners with their corresponding index.
type GenesisOwners struct {
	// index is the index of the capability owner.
	Index uint64 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	// index_owners are the owners at the given index.
	IndexOwners          *CapabilityOwners `protobuf:"bytes,2,opt,name=index_owners,json=indexOwners,proto3" json:"index_owners,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GenesisOwners) Reset()         { *m = GenesisOwners{} }
func (m *GenesisOwners) String() string { return proto.CompactTextString(m) }
func (*GenesisOwners) ProtoMessage()    {}
func (*GenesisOwners) Descriptor() ([]byte, []int) {
	return fileDescriptor_94922dd16a11c23e, []int{0}
}

func (m *GenesisOwners) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenesisOwners.Unmarshal(m, b)
}
func (m *GenesisOwners) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenesisOwners.Marshal(b, m, deterministic)
}
func (m *GenesisOwners) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisOwners.Merge(m, src)
}
func (m *GenesisOwners) XXX_Size() int {
	return xxx_messageInfo_GenesisOwners.Size(m)
}
func (m *GenesisOwners) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisOwners.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisOwners proto.InternalMessageInfo

func (m *GenesisOwners) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *GenesisOwners) GetIndexOwners() *CapabilityOwners {
	if m != nil {
		return m.IndexOwners
	}
	return nil
}

// GenesisState defines the capability module's genesis state.
type GenesisState struct {
	// index is the capability global index.
	Index uint64 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	// owners represents a map from index to owners of the capability index
	// index key is string to allow amino marshalling.
	Owners               []*GenesisOwners `protobuf:"bytes,2,rep,name=owners,proto3" json:"owners,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_94922dd16a11c23e, []int{1}
}

func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenesisState.Unmarshal(m, b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return xxx_messageInfo_GenesisState.Size(m)
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *GenesisState) GetOwners() []*GenesisOwners {
	if m != nil {
		return m.Owners
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisOwners)(nil), "cosmos.capability.v1beta1.GenesisOwners")
	proto.RegisterType((*GenesisState)(nil), "cosmos.capability.v1beta1.GenesisState")
}

func init() {
	proto.RegisterFile("cosmos/capability/v1beta1/genesis.proto", fileDescriptor_94922dd16a11c23e)
}

var fileDescriptor_94922dd16a11c23e = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4f, 0xce, 0x2f, 0xce,
	0xcd, 0x2f, 0xd6, 0x4f, 0x4e, 0x2c, 0x48, 0x4c, 0xca, 0xcc, 0xc9, 0x2c, 0xa9, 0xd4, 0x2f, 0x33,
	0x4c, 0x4a, 0x2d, 0x49, 0x34, 0xd4, 0x4f, 0x4f, 0xcd, 0x4b, 0x2d, 0xce, 0x2c, 0xd6, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0x92, 0x84, 0x28, 0xd4, 0x43, 0x28, 0xd4, 0x83, 0x2a, 0x94, 0x12, 0x49,
	0xcf, 0x4f, 0xcf, 0x07, 0xab, 0xd2, 0x07, 0xb1, 0x20, 0x1a, 0xa4, 0xb4, 0x70, 0x9b, 0x8c, 0x64,
	0x06, 0x58, 0xad, 0xd2, 0x24, 0x46, 0x2e, 0x5e, 0x77, 0x88, 0x75, 0xfe, 0xe5, 0x79, 0xa9, 0x45,
	0xc5, 0x42, 0x22, 0x5c, 0xac, 0x99, 0x79, 0x29, 0xa9, 0x15, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x2c,
	0x41, 0x10, 0x8e, 0x50, 0x36, 0x17, 0x0f, 0x98, 0x11, 0x9f, 0x0f, 0x56, 0x25, 0xc1, 0xa4, 0xc0,
	0xa8, 0xc1, 0x6d, 0xa4, 0xad, 0x87, 0xd3, 0x6d, 0x7a, 0xce, 0x70, 0x21, 0x88, 0xc1, 0x4e, 0xd2,
	0x27, 0xee, 0xc9, 0x33, 0x7c, 0xba, 0x27, 0x2f, 0x5c, 0x99, 0x98, 0x9b, 0x63, 0xa5, 0x84, 0x6c,
	0x9c, 0x52, 0x10, 0x37, 0x98, 0x0b, 0x51, 0xa9, 0x94, 0xc3, 0xc5, 0x03, 0x75, 0x53, 0x70, 0x49,
	0x62, 0x49, 0x2a, 0x0e, 0x27, 0xb9, 0x71, 0xb1, 0xc1, 0x1d, 0xc3, 0xac, 0xc1, 0x6d, 0xa4, 0x81,
	0xc7, 0x31, 0x28, 0x5e, 0x74, 0x62, 0x01, 0xb9, 0x24, 0x08, 0xaa, 0xdb, 0xc9, 0x30, 0x4a, 0x3f,
	0x3d, 0xb3, 0x24, 0xa3, 0x34, 0x49, 0x2f, 0x39, 0x3f, 0x57, 0x1f, 0x16, 0x76, 0x60, 0x4a, 0xb7,
	0x38, 0x25, 0x5b, 0xbf, 0x02, 0x39, 0x20, 0x4b, 0x2a, 0x0b, 0x52, 0x8b, 0x93, 0xd8, 0xc0, 0x81,
	0x67, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x36, 0x63, 0xd4, 0x9c, 0xc4, 0x01, 0x00, 0x00,
}
