// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kira/tokens/alias.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TokenAlias struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon                 string   `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Decimals             uint32   `protobuf:"varint,4,opt,name=decimals,proto3" json:"decimals,omitempty"`
	Denoms               []string `protobuf:"bytes,5,rep,name=denoms,proto3" json:"denoms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenAlias) Reset()         { *m = TokenAlias{} }
func (m *TokenAlias) String() string { return proto.CompactTextString(m) }
func (*TokenAlias) ProtoMessage()    {}
func (*TokenAlias) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5f7b26b3e48e5a6, []int{0}
}

func (m *TokenAlias) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenAlias.Unmarshal(m, b)
}
func (m *TokenAlias) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenAlias.Marshal(b, m, deterministic)
}
func (m *TokenAlias) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenAlias.Merge(m, src)
}
func (m *TokenAlias) XXX_Size() int {
	return xxx_messageInfo_TokenAlias.Size(m)
}
func (m *TokenAlias) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenAlias.DiscardUnknown(m)
}

var xxx_messageInfo_TokenAlias proto.InternalMessageInfo

func (m *TokenAlias) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *TokenAlias) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TokenAlias) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *TokenAlias) GetDecimals() uint32 {
	if m != nil {
		return m.Decimals
	}
	return 0
}

func (m *TokenAlias) GetDenoms() []string {
	if m != nil {
		return m.Denoms
	}
	return nil
}

type MsgUpsertTokenAlias struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon                 string   `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Decimals             uint32   `protobuf:"varint,4,opt,name=decimals,proto3" json:"decimals,omitempty"`
	Denoms               []string `protobuf:"bytes,5,rep,name=denoms,proto3" json:"denoms,omitempty"`
	Proposer             []byte   `protobuf:"bytes,6,opt,name=proposer,proto3" json:"proposer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgUpsertTokenAlias) Reset()         { *m = MsgUpsertTokenAlias{} }
func (m *MsgUpsertTokenAlias) String() string { return proto.CompactTextString(m) }
func (*MsgUpsertTokenAlias) ProtoMessage()    {}
func (*MsgUpsertTokenAlias) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5f7b26b3e48e5a6, []int{1}
}

func (m *MsgUpsertTokenAlias) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgUpsertTokenAlias.Unmarshal(m, b)
}
func (m *MsgUpsertTokenAlias) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgUpsertTokenAlias.Marshal(b, m, deterministic)
}
func (m *MsgUpsertTokenAlias) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpsertTokenAlias.Merge(m, src)
}
func (m *MsgUpsertTokenAlias) XXX_Size() int {
	return xxx_messageInfo_MsgUpsertTokenAlias.Size(m)
}
func (m *MsgUpsertTokenAlias) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpsertTokenAlias.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpsertTokenAlias proto.InternalMessageInfo

func (m *MsgUpsertTokenAlias) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *MsgUpsertTokenAlias) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgUpsertTokenAlias) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *MsgUpsertTokenAlias) GetDecimals() uint32 {
	if m != nil {
		return m.Decimals
	}
	return 0
}

func (m *MsgUpsertTokenAlias) GetDenoms() []string {
	if m != nil {
		return m.Denoms
	}
	return nil
}

func (m *MsgUpsertTokenAlias) GetProposer() []byte {
	if m != nil {
		return m.Proposer
	}
	return nil
}

func init() {
	proto.RegisterType((*TokenAlias)(nil), "kira.tokens.TokenAlias")
	proto.RegisterType((*MsgUpsertTokenAlias)(nil), "kira.tokens.MsgUpsertTokenAlias")
}

func init() { proto.RegisterFile("kira/tokens/alias.proto", fileDescriptor_e5f7b26b3e48e5a6) }

var fileDescriptor_e5f7b26b3e48e5a6 = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x91, 0xbd, 0x4e, 0xc3, 0x30,
	0x10, 0xc7, 0x65, 0x5a, 0xaa, 0x62, 0x40, 0x48, 0x06, 0x81, 0xd5, 0xa5, 0x51, 0xa6, 0x08, 0xa9,
	0xf1, 0xc0, 0xc6, 0x96, 0xc2, 0x86, 0x58, 0x22, 0x58, 0x98, 0x70, 0x1c, 0x2b, 0x58, 0x89, 0x73,
	0x91, 0x2f, 0x48, 0x64, 0xe3, 0x49, 0xfb, 0x02, 0x6c, 0x8c, 0x4c, 0xc8, 0x4e, 0x5b, 0xf1, 0x06,
	0x4c, 0xfe, 0x7f, 0xdc, 0xfd, 0x64, 0xe9, 0xe8, 0x55, 0x6d, 0x9c, 0x14, 0x3d, 0xd4, 0xba, 0x45,
	0x21, 0x1b, 0x23, 0x31, 0xed, 0x1c, 0xf4, 0xc0, 0x8e, 0x7d, 0x91, 0x8e, 0xc5, 0xe2, 0xa2, 0x82,
	0x0a, 0x42, 0x2e, 0xbc, 0x1a, 0x47, 0xe2, 0x4f, 0x42, 0xe9, 0x93, 0x1f, 0xc8, 0xfc, 0x1e, 0xbb,
	0xa4, 0x33, 0x1c, 0x6c, 0x01, 0x0d, 0x27, 0x11, 0x49, 0x8e, 0xf2, 0xad, 0x63, 0x8c, 0x4e, 0x5b,
	0x69, 0x35, 0x3f, 0x08, 0x69, 0xd0, 0x3e, 0x33, 0x0a, 0x5a, 0x3e, 0x19, 0x33, 0xaf, 0xd9, 0x82,
	0xce, 0x4b, 0xad, 0x8c, 0x95, 0x0d, 0xf2, 0x69, 0x44, 0x92, 0xd3, 0x7c, 0xef, 0x3d, 0xbb, 0xd4,
	0x2d, 0x58, 0xe4, 0x87, 0xd1, 0xc4, 0xb3, 0x47, 0x17, 0x7f, 0x11, 0x7a, 0xfe, 0x88, 0xd5, 0x73,
	0x87, 0xda, 0xf5, 0xff, 0xfb, 0x17, 0xf6, 0x4a, 0xe7, 0x9d, 0x83, 0x0e, 0x50, 0x3b, 0x3e, 0x8b,
	0x48, 0x72, 0xb2, 0xbe, 0xff, 0xde, 0x2c, 0xcf, 0x06, 0x69, 0x9b, 0xdb, 0x78, 0xd7, 0xc4, 0x3f,
	0x9b, 0xe5, 0xaa, 0x32, 0xfd, 0xdb, 0x7b, 0x91, 0x2a, 0xb0, 0x42, 0x01, 0x5a, 0xc0, 0xed, 0xb3,
	0xc2, 0xb2, 0x16, 0xfd, 0xd0, 0x69, 0x4c, 0x33, 0xa5, 0xb2, 0xb2, 0x74, 0x1a, 0x31, 0xdf, 0x53,
	0xd7, 0xd7, 0x2f, 0xc9, 0x9f, 0xd5, 0x07, 0xe3, 0xe4, 0x1d, 0x38, 0x2d, 0x50, 0xd7, 0xd2, 0x88,
	0x8f, 0xdd, 0x15, 0x03, 0xa0, 0x98, 0x85, 0x1b, 0xdd, 0xfc, 0x06, 0x00, 0x00, 0xff, 0xff, 0xa8,
	0x7e, 0xa3, 0x9a, 0xe1, 0x01, 0x00, 0x00,
}
