// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kira/tokens/query.proto

package tokens

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AllTokenAliasesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllTokenAliasesRequest) Reset()         { *m = AllTokenAliasesRequest{} }
func (m *AllTokenAliasesRequest) String() string { return proto.CompactTextString(m) }
func (*AllTokenAliasesRequest) ProtoMessage()    {}
func (*AllTokenAliasesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8db6e46fba94960, []int{0}
}

func (m *AllTokenAliasesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllTokenAliasesRequest.Unmarshal(m, b)
}
func (m *AllTokenAliasesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllTokenAliasesRequest.Marshal(b, m, deterministic)
}
func (m *AllTokenAliasesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllTokenAliasesRequest.Merge(m, src)
}
func (m *AllTokenAliasesRequest) XXX_Size() int {
	return xxx_messageInfo_AllTokenAliasesRequest.Size(m)
}
func (m *AllTokenAliasesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AllTokenAliasesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AllTokenAliasesRequest proto.InternalMessageInfo

type AllTokenAliasesResponse struct {
	Data                 []*TokenAlias `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AllTokenAliasesResponse) Reset()         { *m = AllTokenAliasesResponse{} }
func (m *AllTokenAliasesResponse) String() string { return proto.CompactTextString(m) }
func (*AllTokenAliasesResponse) ProtoMessage()    {}
func (*AllTokenAliasesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8db6e46fba94960, []int{1}
}

func (m *AllTokenAliasesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllTokenAliasesResponse.Unmarshal(m, b)
}
func (m *AllTokenAliasesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllTokenAliasesResponse.Marshal(b, m, deterministic)
}
func (m *AllTokenAliasesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllTokenAliasesResponse.Merge(m, src)
}
func (m *AllTokenAliasesResponse) XXX_Size() int {
	return xxx_messageInfo_AllTokenAliasesResponse.Size(m)
}
func (m *AllTokenAliasesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AllTokenAliasesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AllTokenAliasesResponse proto.InternalMessageInfo

func (m *AllTokenAliasesResponse) GetData() []*TokenAlias {
	if m != nil {
		return m.Data
	}
	return nil
}

type AllTokenRatesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllTokenRatesRequest) Reset()         { *m = AllTokenRatesRequest{} }
func (m *AllTokenRatesRequest) String() string { return proto.CompactTextString(m) }
func (*AllTokenRatesRequest) ProtoMessage()    {}
func (*AllTokenRatesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8db6e46fba94960, []int{2}
}

func (m *AllTokenRatesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllTokenRatesRequest.Unmarshal(m, b)
}
func (m *AllTokenRatesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllTokenRatesRequest.Marshal(b, m, deterministic)
}
func (m *AllTokenRatesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllTokenRatesRequest.Merge(m, src)
}
func (m *AllTokenRatesRequest) XXX_Size() int {
	return xxx_messageInfo_AllTokenRatesRequest.Size(m)
}
func (m *AllTokenRatesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AllTokenRatesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AllTokenRatesRequest proto.InternalMessageInfo

type AllTokenRatesResponse struct {
	Data                 []*TokenRate `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AllTokenRatesResponse) Reset()         { *m = AllTokenRatesResponse{} }
func (m *AllTokenRatesResponse) String() string { return proto.CompactTextString(m) }
func (*AllTokenRatesResponse) ProtoMessage()    {}
func (*AllTokenRatesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8db6e46fba94960, []int{3}
}

func (m *AllTokenRatesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllTokenRatesResponse.Unmarshal(m, b)
}
func (m *AllTokenRatesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllTokenRatesResponse.Marshal(b, m, deterministic)
}
func (m *AllTokenRatesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllTokenRatesResponse.Merge(m, src)
}
func (m *AllTokenRatesResponse) XXX_Size() int {
	return xxx_messageInfo_AllTokenRatesResponse.Size(m)
}
func (m *AllTokenRatesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AllTokenRatesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AllTokenRatesResponse proto.InternalMessageInfo

func (m *AllTokenRatesResponse) GetData() []*TokenRate {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*AllTokenAliasesRequest)(nil), "kira.tokens.AllTokenAliasesRequest")
	proto.RegisterType((*AllTokenAliasesResponse)(nil), "kira.tokens.AllTokenAliasesResponse")
	proto.RegisterType((*AllTokenRatesRequest)(nil), "kira.tokens.AllTokenRatesRequest")
	proto.RegisterType((*AllTokenRatesResponse)(nil), "kira.tokens.AllTokenRatesResponse")
}

func init() {
	proto.RegisterFile("kira/tokens/query.proto", fileDescriptor_c8db6e46fba94960)
}

var fileDescriptor_c8db6e46fba94960 = []byte{
	// 412 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x41, 0x4e, 0xe3, 0x30,
	0x14, 0x86, 0x95, 0x76, 0x3a, 0x0b, 0x77, 0x16, 0x23, 0x6b, 0x9a, 0x44, 0xd1, 0x2c, 0x32, 0x19,
	0x16, 0xa8, 0xa8, 0x71, 0x09, 0x12, 0x8b, 0x2e, 0x90, 0x42, 0x25, 0x58, 0xb0, 0x81, 0x08, 0x09,
	0x09, 0x89, 0x85, 0x5b, 0xac, 0xd4, 0x6a, 0xb0, 0x53, 0xdb, 0x05, 0xba, 0xe5, 0x08, 0xe5, 0x26,
	0x1c, 0x80, 0x4b, 0x70, 0x05, 0xae, 0x81, 0x84, 0xe2, 0xa4, 0x6a, 0xda, 0xb4, 0x5d, 0x59, 0x7a,
	0xff, 0xe7, 0xff, 0xfd, 0xf6, 0x7b, 0xc0, 0x1a, 0x53, 0x81, 0x91, 0xe2, 0x63, 0xc2, 0x24, 0x9a,
	0x4c, 0x89, 0x98, 0xf9, 0xa9, 0xe0, 0x8a, 0xc3, 0x66, 0x26, 0xf8, 0xb9, 0xe0, 0xac, 0x50, 0x38,
	0xa1, 0x58, 0xe6, 0x94, 0x63, 0x96, 0x05, 0x81, 0x15, 0x29, 0xea, 0x7f, 0x63, 0xce, 0xe3, 0x84,
	0x20, 0x9c, 0x52, 0x84, 0x19, 0xe3, 0x0a, 0x2b, 0xca, 0xd9, 0xe2, 0x56, 0x7e, 0x0c, 0x3b, 0x31,
	0x61, 0x1d, 0x9e, 0x12, 0x86, 0x53, 0xfa, 0x18, 0x20, 0x9e, 0x6a, 0xa6, 0xca, 0x7b, 0x36, 0x30,
	0xc3, 0x24, 0xb9, 0xce, 0xba, 0x84, 0x59, 0x73, 0x22, 0x23, 0x32, 0x99, 0x12, 0xa9, 0xbc, 0x33,
	0x60, 0x55, 0x14, 0x99, 0x72, 0x26, 0x09, 0x3c, 0x00, 0x3f, 0xee, 0xb1, 0xc2, 0xb6, 0xe1, 0xd6,
	0xf7, 0x9b, 0x81, 0xe5, 0x97, 0xde, 0xe3, 0x2f, 0x2f, 0x44, 0x1a, 0xf2, 0x4c, 0xf0, 0x67, 0xe1,
	0x13, 0x61, 0xb5, 0xf4, 0xef, 0x83, 0xd6, 0x5a, 0xbd, 0x70, 0x6f, 0xaf, 0xb8, 0x9b, 0x55, 0xf7,
	0x0c, 0xcf, 0xcd, 0x83, 0xaf, 0x1a, 0x68, 0x5c, 0x65, 0x5f, 0x0b, 0xdf, 0x0d, 0x00, 0xcf, 0x89,
	0x5a, 0x8b, 0x0c, 0xff, 0xaf, 0x5c, 0xdf, 0xfc, 0x54, 0x67, 0x6f, 0x37, 0x94, 0xe7, 0xf2, 0xee,
	0xe6, 0x61, 0x0f, 0x34, 0xf4, 0x20, 0xa1, 0xa5, 0x9b, 0xba, 0x61, 0x92, 0xb8, 0x9a, 0x75, 0x0b,
	0xd8, 0xb1, 0xb7, 0x08, 0xfe, 0xcb, 0xc7, 0xe7, 0x6b, 0xcd, 0x81, 0xb6, 0x9e, 0x5b, 0x65, 0xe6,
	0x44, 0xc2, 0x37, 0x03, 0xfc, 0x2e, 0x3d, 0x40, 0xff, 0x09, 0xfc, 0xb7, 0x31, 0x59, 0xf9, 0x1f,
	0x1d, 0x6f, 0x17, 0x52, 0x44, 0xbf, 0x99, 0x87, 0xc7, 0x8b, 0xe8, 0xad, 0xf5, 0x84, 0x1a, 0x75,
	0xcc, 0x8d, 0xe5, 0x3c, 0xb6, 0x0d, 0xcd, 0x4a, 0xec, 0x6c, 0x23, 0xe5, 0xa9, 0x9c, 0x87, 0x27,
	0xb0, 0x11, 0xd4, 0x0f, 0xfd, 0x6e, 0xdb, 0x30, 0x44, 0x00, 0x7e, 0xc5, 0xd1, 0x65, 0xbf, 0x13,
	0x63, 0x45, 0x9e, 0xf0, 0x0c, 0x7a, 0x23, 0xa5, 0x52, 0xd9, 0x43, 0x28, 0xa6, 0x6a, 0x34, 0x1d,
	0xf8, 0x43, 0xfe, 0x80, 0x2e, 0xa8, 0xc0, 0x7d, 0x2e, 0x08, 0xa2, 0x4c, 0x11, 0xf1, 0x7c, 0xdb,
	0xdd, 0xae, 0x21, 0xbd, 0xa3, 0xd9, 0x2e, 0x97, 0x5b, 0x0f, 0x7e, 0xea, 0xf2, 0xd1, 0x77, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xbf, 0xac, 0x1b, 0x34, 0x61, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Returns the token alias
	GetAllTokenAliases(ctx context.Context, in *AllTokenAliasesRequest, opts ...grpc.CallOption) (*AllTokenAliasesResponse, error)
	// Returns the token rates
	GetAllTokenRates(ctx context.Context, in *AllTokenRatesRequest, opts ...grpc.CallOption) (*AllTokenRatesResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) GetAllTokenAliases(ctx context.Context, in *AllTokenAliasesRequest, opts ...grpc.CallOption) (*AllTokenAliasesResponse, error) {
	out := new(AllTokenAliasesResponse)
	err := c.cc.Invoke(ctx, "/kira.tokens.Query/GetAllTokenAliases", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetAllTokenRates(ctx context.Context, in *AllTokenRatesRequest, opts ...grpc.CallOption) (*AllTokenRatesResponse, error) {
	out := new(AllTokenRatesResponse)
	err := c.cc.Invoke(ctx, "/kira.tokens.Query/GetAllTokenRates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Returns the token alias
	GetAllTokenAliases(context.Context, *AllTokenAliasesRequest) (*AllTokenAliasesResponse, error)
	// Returns the token rates
	GetAllTokenRates(context.Context, *AllTokenRatesRequest) (*AllTokenRatesResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) GetAllTokenAliases(ctx context.Context, req *AllTokenAliasesRequest) (*AllTokenAliasesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllTokenAliases not implemented")
}
func (*UnimplementedQueryServer) GetAllTokenRates(ctx context.Context, req *AllTokenRatesRequest) (*AllTokenRatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllTokenRates not implemented")
}

func RegisterQueryServer(s *grpc.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_GetAllTokenAliases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllTokenAliasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetAllTokenAliases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kira.tokens.Query/GetAllTokenAliases",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetAllTokenAliases(ctx, req.(*AllTokenAliasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetAllTokenRates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllTokenRatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetAllTokenRates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kira.tokens.Query/GetAllTokenRates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetAllTokenRates(ctx, req.(*AllTokenRatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kira.tokens.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllTokenAliases",
			Handler:    _Query_GetAllTokenAliases_Handler,
		},
		{
			MethodName: "GetAllTokenRates",
			Handler:    _Query_GetAllTokenRates_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kira/tokens/query.proto",
}
