// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cosmos/bank/v1beta1/bank.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/regen-network/cosmos-proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the bank module.
type Params struct {
	SendEnabled          []*SendEnabled `protobuf:"bytes,1,rep,name=send_enabled,json=sendEnabled,proto3" json:"send_enabled,omitempty"`
	DefaultSendEnabled   bool           `protobuf:"varint,2,opt,name=default_send_enabled,json=defaultSendEnabled,proto3" json:"default_send_enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd052eee12edf988, []int{0}
}

func (m *Params) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Params.Unmarshal(m, b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Params.Marshal(b, m, deterministic)
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return xxx_messageInfo_Params.Size(m)
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetSendEnabled() []*SendEnabled {
	if m != nil {
		return m.SendEnabled
	}
	return nil
}

func (m *Params) GetDefaultSendEnabled() bool {
	if m != nil {
		return m.DefaultSendEnabled
	}
	return false
}

// SendEnabled maps coin denom to a send_enabled status (whether a denom is
// sendable).
type SendEnabled struct {
	Denom                string   `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	Enabled              bool     `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendEnabled) Reset()         { *m = SendEnabled{} }
func (m *SendEnabled) String() string { return proto.CompactTextString(m) }
func (*SendEnabled) ProtoMessage()    {}
func (*SendEnabled) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd052eee12edf988, []int{1}
}

func (m *SendEnabled) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEnabled.Unmarshal(m, b)
}
func (m *SendEnabled) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEnabled.Marshal(b, m, deterministic)
}
func (m *SendEnabled) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEnabled.Merge(m, src)
}
func (m *SendEnabled) XXX_Size() int {
	return xxx_messageInfo_SendEnabled.Size(m)
}
func (m *SendEnabled) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEnabled.DiscardUnknown(m)
}

var xxx_messageInfo_SendEnabled proto.InternalMessageInfo

func (m *SendEnabled) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *SendEnabled) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

// Input models transaction input.
type Input struct {
	Address              string        `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Coins                []*types.Coin `protobuf:"bytes,2,rep,name=coins,proto3" json:"coins,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Input) Reset()         { *m = Input{} }
func (m *Input) String() string { return proto.CompactTextString(m) }
func (*Input) ProtoMessage()    {}
func (*Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd052eee12edf988, []int{2}
}

func (m *Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Input.Unmarshal(m, b)
}
func (m *Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Input.Marshal(b, m, deterministic)
}
func (m *Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Input.Merge(m, src)
}
func (m *Input) XXX_Size() int {
	return xxx_messageInfo_Input.Size(m)
}
func (m *Input) XXX_DiscardUnknown() {
	xxx_messageInfo_Input.DiscardUnknown(m)
}

var xxx_messageInfo_Input proto.InternalMessageInfo

func (m *Input) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Input) GetCoins() []*types.Coin {
	if m != nil {
		return m.Coins
	}
	return nil
}

// Output models transaction outputs.
type Output struct {
	Address              string        `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Coins                []*types.Coin `protobuf:"bytes,2,rep,name=coins,proto3" json:"coins,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Output) Reset()         { *m = Output{} }
func (m *Output) String() string { return proto.CompactTextString(m) }
func (*Output) ProtoMessage()    {}
func (*Output) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd052eee12edf988, []int{3}
}

func (m *Output) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Output.Unmarshal(m, b)
}
func (m *Output) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Output.Marshal(b, m, deterministic)
}
func (m *Output) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Output.Merge(m, src)
}
func (m *Output) XXX_Size() int {
	return xxx_messageInfo_Output.Size(m)
}
func (m *Output) XXX_DiscardUnknown() {
	xxx_messageInfo_Output.DiscardUnknown(m)
}

var xxx_messageInfo_Output proto.InternalMessageInfo

func (m *Output) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Output) GetCoins() []*types.Coin {
	if m != nil {
		return m.Coins
	}
	return nil
}

// Supply represents a struct that passively keeps track of the total supply
// amounts in the network.
// This message is deprecated now that supply is indexed by denom.
//
// Deprecated: Do not use.
type Supply struct {
	Total                []*types.Coin `protobuf:"bytes,1,rep,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Supply) Reset()         { *m = Supply{} }
func (m *Supply) String() string { return proto.CompactTextString(m) }
func (*Supply) ProtoMessage()    {}
func (*Supply) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd052eee12edf988, []int{4}
}

func (m *Supply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Supply.Unmarshal(m, b)
}
func (m *Supply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Supply.Marshal(b, m, deterministic)
}
func (m *Supply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Supply.Merge(m, src)
}
func (m *Supply) XXX_Size() int {
	return xxx_messageInfo_Supply.Size(m)
}
func (m *Supply) XXX_DiscardUnknown() {
	xxx_messageInfo_Supply.DiscardUnknown(m)
}

var xxx_messageInfo_Supply proto.InternalMessageInfo

func (m *Supply) GetTotal() []*types.Coin {
	if m != nil {
		return m.Total
	}
	return nil
}

// DenomUnit represents a struct that describes a given
// denomination unit of the basic token.
type DenomUnit struct {
	// denom represents the string name of the given denom unit (e.g uatom).
	Denom string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	// exponent represents power of 10 exponent that one must
	// raise the base_denom to in order to equal the given DenomUnit's denom
	// 1 denom = 1^exponent base_denom
	// (e.g. with a base_denom of uatom, one can create a DenomUnit of 'atom' with
	// exponent = 6, thus: 1 atom = 10^6 uatom).
	Exponent uint32 `protobuf:"varint,2,opt,name=exponent,proto3" json:"exponent,omitempty"`
	// aliases is a list of string aliases for the given denom
	Aliases              []string `protobuf:"bytes,3,rep,name=aliases,proto3" json:"aliases,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DenomUnit) Reset()         { *m = DenomUnit{} }
func (m *DenomUnit) String() string { return proto.CompactTextString(m) }
func (*DenomUnit) ProtoMessage()    {}
func (*DenomUnit) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd052eee12edf988, []int{5}
}

func (m *DenomUnit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DenomUnit.Unmarshal(m, b)
}
func (m *DenomUnit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DenomUnit.Marshal(b, m, deterministic)
}
func (m *DenomUnit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DenomUnit.Merge(m, src)
}
func (m *DenomUnit) XXX_Size() int {
	return xxx_messageInfo_DenomUnit.Size(m)
}
func (m *DenomUnit) XXX_DiscardUnknown() {
	xxx_messageInfo_DenomUnit.DiscardUnknown(m)
}

var xxx_messageInfo_DenomUnit proto.InternalMessageInfo

func (m *DenomUnit) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *DenomUnit) GetExponent() uint32 {
	if m != nil {
		return m.Exponent
	}
	return 0
}

func (m *DenomUnit) GetAliases() []string {
	if m != nil {
		return m.Aliases
	}
	return nil
}

// Metadata represents a struct that describes
// a basic token.
type Metadata struct {
	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// denom_units represents the list of DenomUnit's for a given coin
	DenomUnits []*DenomUnit `protobuf:"bytes,2,rep,name=denom_units,json=denomUnits,proto3" json:"denom_units,omitempty"`
	// base represents the base denom (should be the DenomUnit with exponent = 0).
	Base string `protobuf:"bytes,3,opt,name=base,proto3" json:"base,omitempty"`
	// display indicates the suggested denom that should be
	// displayed in clients.
	Display string `protobuf:"bytes,4,opt,name=display,proto3" json:"display,omitempty"`
	// name defines the name of the token (eg: Cosmos Atom)
	//
	// Since: cosmos-sdk 0.43
	Name string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	// symbol is the token symbol usually shown on exchanges (eg: ATOM). This can
	// be the same as the display.
	//
	// Since: cosmos-sdk 0.43
	Symbol               string   `protobuf:"bytes,6,opt,name=symbol,proto3" json:"symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd052eee12edf988, []int{6}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Metadata) GetDenomUnits() []*DenomUnit {
	if m != nil {
		return m.DenomUnits
	}
	return nil
}

func (m *Metadata) GetBase() string {
	if m != nil {
		return m.Base
	}
	return ""
}

func (m *Metadata) GetDisplay() string {
	if m != nil {
		return m.Display
	}
	return ""
}

func (m *Metadata) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Metadata) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func init() {
	proto.RegisterType((*Params)(nil), "cosmos.bank.v1beta1.Params")
	proto.RegisterType((*SendEnabled)(nil), "cosmos.bank.v1beta1.SendEnabled")
	proto.RegisterType((*Input)(nil), "cosmos.bank.v1beta1.Input")
	proto.RegisterType((*Output)(nil), "cosmos.bank.v1beta1.Output")
	proto.RegisterType((*Supply)(nil), "cosmos.bank.v1beta1.Supply")
	proto.RegisterType((*DenomUnit)(nil), "cosmos.bank.v1beta1.DenomUnit")
	proto.RegisterType((*Metadata)(nil), "cosmos.bank.v1beta1.Metadata")
}

func init() { proto.RegisterFile("cosmos/bank/v1beta1/bank.proto", fileDescriptor_dd052eee12edf988) }

var fileDescriptor_dd052eee12edf988 = []byte{
	// 565 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x54, 0xbf, 0x6f, 0xd3, 0x40,
	0x14, 0xce, 0x35, 0x89, 0x49, 0x2f, 0xb0, 0x1c, 0x11, 0x72, 0x23, 0x51, 0x1b, 0x4b, 0x48, 0x29,
	0x50, 0x27, 0x05, 0x06, 0x94, 0x05, 0x29, 0xfc, 0x52, 0x07, 0x04, 0x72, 0x85, 0x90, 0x60, 0x88,
	0xce, 0xb9, 0x6b, 0xb0, 0x6a, 0xdf, 0x59, 0xb9, 0x73, 0x55, 0xff, 0x07, 0x4c, 0xb0, 0x32, 0x76,
	0x66, 0x85, 0xff, 0x01, 0x66, 0xd8, 0xc3, 0xca, 0xdc, 0xbf, 0x00, 0xdd, 0x8f, 0x24, 0xae, 0x14,
	0x10, 0x03, 0x03, 0x53, 0xde, 0xf7, 0xde, 0xf7, 0xbe, 0xf7, 0xf4, 0xdd, 0x73, 0xe0, 0xf6, 0x84,
	0x8b, 0x8c, 0x8b, 0x7e, 0x8c, 0xd9, 0x51, 0xff, 0x78, 0x2f, 0xa6, 0x12, 0xef, 0x69, 0x10, 0xe6,
	0x33, 0x2e, 0x39, 0xba, 0x6c, 0xea, 0xa1, 0x4e, 0xd9, 0x7a, 0xb7, 0x33, 0xe5, 0x53, 0xae, 0xeb,
	0x7d, 0x15, 0x19, 0x6a, 0x77, 0xcb, 0x50, 0xc7, 0xa6, 0x60, 0xfb, 0x4c, 0x69, 0x35, 0x45, 0xd0,
	0xe5, 0x94, 0x09, 0x4f, 0x98, 0xa9, 0x07, 0xdf, 0x01, 0x74, 0x9e, 0xe3, 0x19, 0xce, 0x04, 0x3a,
	0x84, 0x17, 0x05, 0x65, 0x64, 0x4c, 0x19, 0x8e, 0x53, 0x4a, 0x5c, 0xe0, 0xd7, 0x7b, 0xed, 0xdb,
	0x7e, 0xb8, 0x66, 0x8f, 0xf0, 0x80, 0x32, 0xf2, 0xc8, 0xf0, 0x46, 0xd7, 0xce, 0xe6, 0xde, 0xd5,
	0x12, 0x67, 0xe9, 0x30, 0xa8, 0xf6, 0xdf, 0xe2, 0x59, 0x22, 0x69, 0x96, 0xcb, 0x32, 0x88, 0xda,
	0x62, 0xc5, 0x47, 0xaf, 0x61, 0x87, 0xd0, 0x43, 0x5c, 0xa4, 0x72, 0x7c, 0x6e, 0xde, 0x86, 0x0f,
	0x7a, 0xad, 0xd1, 0xce, 0xd9, 0xdc, 0xbb, 0x6e, 0xd4, 0xd6, 0xb1, 0xaa, 0xaa, 0xc8, 0x12, 0x2a,
	0xcb, 0x0c, 0x1b, 0x1f, 0x4e, 0xbd, 0x5a, 0xf0, 0x04, 0xb6, 0x2b, 0x49, 0xd4, 0x81, 0x4d, 0x42,
	0x19, 0xcf, 0x5c, 0xe0, 0x83, 0xde, 0x66, 0x64, 0x00, 0x72, 0xe1, 0x85, 0x73, 0xa3, 0xa3, 0x05,
	0x1c, 0xb6, 0x94, 0xc8, 0xcf, 0x53, 0x0f, 0x04, 0xef, 0x00, 0x6c, 0xee, 0xb3, 0xbc, 0x90, 0x8a,
	0x8d, 0x09, 0x99, 0x51, 0x21, 0xac, 0xca, 0x02, 0x22, 0x0c, 0x9b, 0xca, 0x50, 0xe1, 0x6e, 0x68,
	0xc3, 0xb6, 0x56, 0x86, 0x09, 0xba, 0x34, 0xec, 0x01, 0x4f, 0xd8, 0x68, 0xf0, 0x75, 0xee, 0xd5,
	0x3e, 0xfe, 0xf0, 0x7a, 0xd3, 0x44, 0xbe, 0x29, 0xe2, 0x70, 0xc2, 0x33, 0xfb, 0x5a, 0xf6, 0x67,
	0x57, 0x90, 0xa3, 0xbe, 0x2c, 0x73, 0x2a, 0x74, 0x83, 0x88, 0x8c, 0xf2, 0xb0, 0xf5, 0xd6, 0x2c,
	0x54, 0x0b, 0xde, 0x03, 0xe8, 0x3c, 0x2b, 0xe4, 0x7f, 0xb4, 0xd1, 0x27, 0x00, 0x9d, 0x83, 0x22,
	0xcf, 0xd3, 0x52, 0xcd, 0x95, 0x5c, 0xe2, 0xd4, 0x9e, 0xce, 0xbf, 0x9d, 0xab, 0x95, 0x87, 0x8f,
	0xed, 0x5c, 0xf0, 0xed, 0xf3, 0xee, 0xbd, 0x1b, 0x7f, 0xec, 0x3e, 0x31, 0x9f, 0x56, 0x4a, 0xa7,
	0x78, 0x52, 0xf6, 0x8f, 0x07, 0x77, 0x07, 0xa1, 0xd9, 0x73, 0xdf, 0x05, 0xc1, 0x4b, 0xb8, 0xf9,
	0x50, 0x5d, 0xc1, 0x0b, 0x96, 0xc8, 0xdf, 0xdc, 0x47, 0x17, 0xb6, 0xe8, 0x49, 0xce, 0x19, 0x65,
	0x52, 0x1f, 0xc8, 0xa5, 0x68, 0x89, 0xb5, 0xf7, 0x69, 0x82, 0x05, 0x15, 0x6e, 0xdd, 0xaf, 0x6b,
	0xef, 0x0d, 0x0c, 0xbe, 0x00, 0xd8, 0x7a, 0x4a, 0x25, 0x26, 0x58, 0x62, 0xe4, 0xc3, 0x36, 0xa1,
	0x62, 0x32, 0x4b, 0x72, 0x99, 0x70, 0x66, 0xe5, 0xab, 0x29, 0x74, 0x5f, 0x31, 0x18, 0xcf, 0xc6,
	0x05, 0x4b, 0xe4, 0xe2, 0xc1, 0xb6, 0xd7, 0x7e, 0x73, 0xcb, 0x7d, 0x23, 0x48, 0x16, 0xa1, 0x40,
	0x08, 0x36, 0x94, 0xbd, 0x6e, 0x5d, 0x6b, 0xeb, 0x58, 0x6d, 0x47, 0x12, 0x91, 0xa7, 0xb8, 0x74,
	0x1b, 0xe6, 0x32, 0x2c, 0x54, 0x6c, 0x86, 0x33, 0xea, 0x36, 0x0d, 0x5b, 0xc5, 0xe8, 0x0a, 0x74,
	0x44, 0x99, 0xc5, 0x3c, 0x75, 0x1d, 0x9d, 0xb5, 0x68, 0x74, 0xf3, 0xd5, 0xce, 0xdf, 0xf8, 0xab,
	0x1f, 0x29, 0x76, 0xf4, 0xdf, 0xc9, 0x9d, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe9, 0xe0, 0xc0,
	0xd5, 0xd6, 0x04, 0x00, 0x00,
}
