// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cosmos/bank/v1beta1/query.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// QueryBalanceRequest is the request type for the Query/Balance RPC method.
type QueryBalanceRequest struct {
	// address is the address to query balances for.
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// denom is the coin denom to query balances for.
	Denom                string   `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryBalanceRequest) Reset()         { *m = QueryBalanceRequest{} }
func (m *QueryBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*QueryBalanceRequest) ProtoMessage()    {}
func (*QueryBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c6fc1939682df13, []int{0}
}

func (m *QueryBalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryBalanceRequest.Unmarshal(m, b)
}
func (m *QueryBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryBalanceRequest.Marshal(b, m, deterministic)
}
func (m *QueryBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBalanceRequest.Merge(m, src)
}
func (m *QueryBalanceRequest) XXX_Size() int {
	return xxx_messageInfo_QueryBalanceRequest.Size(m)
}
func (m *QueryBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBalanceRequest proto.InternalMessageInfo

func (m *QueryBalanceRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *QueryBalanceRequest) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

// QueryBalanceResponse is the response type for the Query/Balance RPC method.
type QueryBalanceResponse struct {
	// balance is the balance of the coin.
	Balance              *types.Coin `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *QueryBalanceResponse) Reset()         { *m = QueryBalanceResponse{} }
func (m *QueryBalanceResponse) String() string { return proto.CompactTextString(m) }
func (*QueryBalanceResponse) ProtoMessage()    {}
func (*QueryBalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c6fc1939682df13, []int{1}
}

func (m *QueryBalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryBalanceResponse.Unmarshal(m, b)
}
func (m *QueryBalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryBalanceResponse.Marshal(b, m, deterministic)
}
func (m *QueryBalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBalanceResponse.Merge(m, src)
}
func (m *QueryBalanceResponse) XXX_Size() int {
	return xxx_messageInfo_QueryBalanceResponse.Size(m)
}
func (m *QueryBalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBalanceResponse proto.InternalMessageInfo

func (m *QueryBalanceResponse) GetBalance() *types.Coin {
	if m != nil {
		return m.Balance
	}
	return nil
}

// QueryBalanceRequest is the request type for the Query/AllBalances RPC method.
type QueryAllBalancesRequest struct {
	// address is the address to query balances for.
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// pagination defines an optional pagination for the request.
	Pagination           *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *QueryAllBalancesRequest) Reset()         { *m = QueryAllBalancesRequest{} }
func (m *QueryAllBalancesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllBalancesRequest) ProtoMessage()    {}
func (*QueryAllBalancesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c6fc1939682df13, []int{2}
}

func (m *QueryAllBalancesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryAllBalancesRequest.Unmarshal(m, b)
}
func (m *QueryAllBalancesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryAllBalancesRequest.Marshal(b, m, deterministic)
}
func (m *QueryAllBalancesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllBalancesRequest.Merge(m, src)
}
func (m *QueryAllBalancesRequest) XXX_Size() int {
	return xxx_messageInfo_QueryAllBalancesRequest.Size(m)
}
func (m *QueryAllBalancesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllBalancesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllBalancesRequest proto.InternalMessageInfo

func (m *QueryAllBalancesRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *QueryAllBalancesRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryAllBalancesResponse is the response type for the Query/AllBalances RPC
// method.
type QueryAllBalancesResponse struct {
	// balances is the balances of all the coins.
	Balances []*types.Coin `protobuf:"bytes,1,rep,name=balances,proto3" json:"balances,omitempty"`
	// pagination defines the pagination in the response.
	Pagination           *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *QueryAllBalancesResponse) Reset()         { *m = QueryAllBalancesResponse{} }
func (m *QueryAllBalancesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllBalancesResponse) ProtoMessage()    {}
func (*QueryAllBalancesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c6fc1939682df13, []int{3}
}

func (m *QueryAllBalancesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryAllBalancesResponse.Unmarshal(m, b)
}
func (m *QueryAllBalancesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryAllBalancesResponse.Marshal(b, m, deterministic)
}
func (m *QueryAllBalancesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllBalancesResponse.Merge(m, src)
}
func (m *QueryAllBalancesResponse) XXX_Size() int {
	return xxx_messageInfo_QueryAllBalancesResponse.Size(m)
}
func (m *QueryAllBalancesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllBalancesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllBalancesResponse proto.InternalMessageInfo

func (m *QueryAllBalancesResponse) GetBalances() []*types.Coin {
	if m != nil {
		return m.Balances
	}
	return nil
}

func (m *QueryAllBalancesResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryTotalSupplyRequest is the request type for the Query/TotalSupply RPC
// method.
type QueryTotalSupplyRequest struct {
	// pagination defines an optional pagination for the request.
	//
	// Since: cosmos-sdk 0.43
	Pagination           *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *QueryTotalSupplyRequest) Reset()         { *m = QueryTotalSupplyRequest{} }
func (m *QueryTotalSupplyRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTotalSupplyRequest) ProtoMessage()    {}
func (*QueryTotalSupplyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c6fc1939682df13, []int{4}
}

func (m *QueryTotalSupplyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryTotalSupplyRequest.Unmarshal(m, b)
}
func (m *QueryTotalSupplyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryTotalSupplyRequest.Marshal(b, m, deterministic)
}
func (m *QueryTotalSupplyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTotalSupplyRequest.Merge(m, src)
}
func (m *QueryTotalSupplyRequest) XXX_Size() int {
	return xxx_messageInfo_QueryTotalSupplyRequest.Size(m)
}
func (m *QueryTotalSupplyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTotalSupplyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTotalSupplyRequest proto.InternalMessageInfo

func (m *QueryTotalSupplyRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryTotalSupplyResponse is the response type for the Query/TotalSupply RPC
// method
type QueryTotalSupplyResponse struct {
	// supply is the supply of the coins
	Supply []*types.Coin `protobuf:"bytes,1,rep,name=supply,proto3" json:"supply,omitempty"`
	// pagination defines the pagination in the response.
	//
	// Since: cosmos-sdk 0.43
	Pagination           *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *QueryTotalSupplyResponse) Reset()         { *m = QueryTotalSupplyResponse{} }
func (m *QueryTotalSupplyResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTotalSupplyResponse) ProtoMessage()    {}
func (*QueryTotalSupplyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c6fc1939682df13, []int{5}
}

func (m *QueryTotalSupplyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryTotalSupplyResponse.Unmarshal(m, b)
}
func (m *QueryTotalSupplyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryTotalSupplyResponse.Marshal(b, m, deterministic)
}
func (m *QueryTotalSupplyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTotalSupplyResponse.Merge(m, src)
}
func (m *QueryTotalSupplyResponse) XXX_Size() int {
	return xxx_messageInfo_QueryTotalSupplyResponse.Size(m)
}
func (m *QueryTotalSupplyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTotalSupplyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTotalSupplyResponse proto.InternalMessageInfo

func (m *QueryTotalSupplyResponse) GetSupply() []*types.Coin {
	if m != nil {
		return m.Supply
	}
	return nil
}

func (m *QueryTotalSupplyResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QuerySupplyOfRequest is the request type for the Query/SupplyOf RPC method.
type QuerySupplyOfRequest struct {
	// denom is the coin denom to query balances for.
	Denom                string   `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuerySupplyOfRequest) Reset()         { *m = QuerySupplyOfRequest{} }
func (m *QuerySupplyOfRequest) String() string { return proto.CompactTextString(m) }
func (*QuerySupplyOfRequest) ProtoMessage()    {}
func (*QuerySupplyOfRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c6fc1939682df13, []int{6}
}

func (m *QuerySupplyOfRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuerySupplyOfRequest.Unmarshal(m, b)
}
func (m *QuerySupplyOfRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuerySupplyOfRequest.Marshal(b, m, deterministic)
}
func (m *QuerySupplyOfRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySupplyOfRequest.Merge(m, src)
}
func (m *QuerySupplyOfRequest) XXX_Size() int {
	return xxx_messageInfo_QuerySupplyOfRequest.Size(m)
}
func (m *QuerySupplyOfRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySupplyOfRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySupplyOfRequest proto.InternalMessageInfo

func (m *QuerySupplyOfRequest) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

// QuerySupplyOfResponse is the response type for the Query/SupplyOf RPC method.
type QuerySupplyOfResponse struct {
	// amount is the supply of the coin.
	Amount               *types.Coin `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *QuerySupplyOfResponse) Reset()         { *m = QuerySupplyOfResponse{} }
func (m *QuerySupplyOfResponse) String() string { return proto.CompactTextString(m) }
func (*QuerySupplyOfResponse) ProtoMessage()    {}
func (*QuerySupplyOfResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c6fc1939682df13, []int{7}
}

func (m *QuerySupplyOfResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuerySupplyOfResponse.Unmarshal(m, b)
}
func (m *QuerySupplyOfResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuerySupplyOfResponse.Marshal(b, m, deterministic)
}
func (m *QuerySupplyOfResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySupplyOfResponse.Merge(m, src)
}
func (m *QuerySupplyOfResponse) XXX_Size() int {
	return xxx_messageInfo_QuerySupplyOfResponse.Size(m)
}
func (m *QuerySupplyOfResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySupplyOfResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySupplyOfResponse proto.InternalMessageInfo

func (m *QuerySupplyOfResponse) GetAmount() *types.Coin {
	if m != nil {
		return m.Amount
	}
	return nil
}

// QueryParamsRequest defines the request type for querying x/bank parameters.
type QueryParamsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c6fc1939682df13, []int{8}
}

func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryParamsRequest.Unmarshal(m, b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return xxx_messageInfo_QueryParamsRequest.Size(m)
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse defines the response type for querying x/bank parameters.
type QueryParamsResponse struct {
	Params               *Params  `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c6fc1939682df13, []int{9}
}

func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryParamsResponse.Unmarshal(m, b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return xxx_messageInfo_QueryParamsResponse.Size(m)
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() *Params {
	if m != nil {
		return m.Params
	}
	return nil
}

// QueryDenomsMetadataRequest is the request type for the Query/DenomsMetadata RPC method.
type QueryDenomsMetadataRequest struct {
	// pagination defines an optional pagination for the request.
	Pagination           *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *QueryDenomsMetadataRequest) Reset()         { *m = QueryDenomsMetadataRequest{} }
func (m *QueryDenomsMetadataRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDenomsMetadataRequest) ProtoMessage()    {}
func (*QueryDenomsMetadataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c6fc1939682df13, []int{10}
}

func (m *QueryDenomsMetadataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryDenomsMetadataRequest.Unmarshal(m, b)
}
func (m *QueryDenomsMetadataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryDenomsMetadataRequest.Marshal(b, m, deterministic)
}
func (m *QueryDenomsMetadataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDenomsMetadataRequest.Merge(m, src)
}
func (m *QueryDenomsMetadataRequest) XXX_Size() int {
	return xxx_messageInfo_QueryDenomsMetadataRequest.Size(m)
}
func (m *QueryDenomsMetadataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDenomsMetadataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDenomsMetadataRequest proto.InternalMessageInfo

func (m *QueryDenomsMetadataRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryDenomsMetadataResponse is the response type for the Query/DenomsMetadata RPC
// method.
type QueryDenomsMetadataResponse struct {
	// metadata provides the client information for all the registered tokens.
	Metadatas []*Metadata `protobuf:"bytes,1,rep,name=metadatas,proto3" json:"metadatas,omitempty"`
	// pagination defines the pagination in the response.
	Pagination           *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *QueryDenomsMetadataResponse) Reset()         { *m = QueryDenomsMetadataResponse{} }
func (m *QueryDenomsMetadataResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDenomsMetadataResponse) ProtoMessage()    {}
func (*QueryDenomsMetadataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c6fc1939682df13, []int{11}
}

func (m *QueryDenomsMetadataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryDenomsMetadataResponse.Unmarshal(m, b)
}
func (m *QueryDenomsMetadataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryDenomsMetadataResponse.Marshal(b, m, deterministic)
}
func (m *QueryDenomsMetadataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDenomsMetadataResponse.Merge(m, src)
}
func (m *QueryDenomsMetadataResponse) XXX_Size() int {
	return xxx_messageInfo_QueryDenomsMetadataResponse.Size(m)
}
func (m *QueryDenomsMetadataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDenomsMetadataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDenomsMetadataResponse proto.InternalMessageInfo

func (m *QueryDenomsMetadataResponse) GetMetadatas() []*Metadata {
	if m != nil {
		return m.Metadatas
	}
	return nil
}

func (m *QueryDenomsMetadataResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryDenomMetadataRequest is the request type for the Query/DenomMetadata RPC method.
type QueryDenomMetadataRequest struct {
	// denom is the coin denom to query the metadata for.
	Denom                string   `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryDenomMetadataRequest) Reset()         { *m = QueryDenomMetadataRequest{} }
func (m *QueryDenomMetadataRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDenomMetadataRequest) ProtoMessage()    {}
func (*QueryDenomMetadataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c6fc1939682df13, []int{12}
}

func (m *QueryDenomMetadataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryDenomMetadataRequest.Unmarshal(m, b)
}
func (m *QueryDenomMetadataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryDenomMetadataRequest.Marshal(b, m, deterministic)
}
func (m *QueryDenomMetadataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDenomMetadataRequest.Merge(m, src)
}
func (m *QueryDenomMetadataRequest) XXX_Size() int {
	return xxx_messageInfo_QueryDenomMetadataRequest.Size(m)
}
func (m *QueryDenomMetadataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDenomMetadataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDenomMetadataRequest proto.InternalMessageInfo

func (m *QueryDenomMetadataRequest) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

// QueryDenomMetadataResponse is the response type for the Query/DenomMetadata RPC
// method.
type QueryDenomMetadataResponse struct {
	// metadata describes and provides all the client information for the requested token.
	Metadata             *Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *QueryDenomMetadataResponse) Reset()         { *m = QueryDenomMetadataResponse{} }
func (m *QueryDenomMetadataResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDenomMetadataResponse) ProtoMessage()    {}
func (*QueryDenomMetadataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c6fc1939682df13, []int{13}
}

func (m *QueryDenomMetadataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryDenomMetadataResponse.Unmarshal(m, b)
}
func (m *QueryDenomMetadataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryDenomMetadataResponse.Marshal(b, m, deterministic)
}
func (m *QueryDenomMetadataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDenomMetadataResponse.Merge(m, src)
}
func (m *QueryDenomMetadataResponse) XXX_Size() int {
	return xxx_messageInfo_QueryDenomMetadataResponse.Size(m)
}
func (m *QueryDenomMetadataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDenomMetadataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDenomMetadataResponse proto.InternalMessageInfo

func (m *QueryDenomMetadataResponse) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryBalanceRequest)(nil), "cosmos.bank.v1beta1.QueryBalanceRequest")
	proto.RegisterType((*QueryBalanceResponse)(nil), "cosmos.bank.v1beta1.QueryBalanceResponse")
	proto.RegisterType((*QueryAllBalancesRequest)(nil), "cosmos.bank.v1beta1.QueryAllBalancesRequest")
	proto.RegisterType((*QueryAllBalancesResponse)(nil), "cosmos.bank.v1beta1.QueryAllBalancesResponse")
	proto.RegisterType((*QueryTotalSupplyRequest)(nil), "cosmos.bank.v1beta1.QueryTotalSupplyRequest")
	proto.RegisterType((*QueryTotalSupplyResponse)(nil), "cosmos.bank.v1beta1.QueryTotalSupplyResponse")
	proto.RegisterType((*QuerySupplyOfRequest)(nil), "cosmos.bank.v1beta1.QuerySupplyOfRequest")
	proto.RegisterType((*QuerySupplyOfResponse)(nil), "cosmos.bank.v1beta1.QuerySupplyOfResponse")
	proto.RegisterType((*QueryParamsRequest)(nil), "cosmos.bank.v1beta1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "cosmos.bank.v1beta1.QueryParamsResponse")
	proto.RegisterType((*QueryDenomsMetadataRequest)(nil), "cosmos.bank.v1beta1.QueryDenomsMetadataRequest")
	proto.RegisterType((*QueryDenomsMetadataResponse)(nil), "cosmos.bank.v1beta1.QueryDenomsMetadataResponse")
	proto.RegisterType((*QueryDenomMetadataRequest)(nil), "cosmos.bank.v1beta1.QueryDenomMetadataRequest")
	proto.RegisterType((*QueryDenomMetadataResponse)(nil), "cosmos.bank.v1beta1.QueryDenomMetadataResponse")
}

func init() { proto.RegisterFile("cosmos/bank/v1beta1/query.proto", fileDescriptor_9c6fc1939682df13) }

var fileDescriptor_9c6fc1939682df13 = []byte{
	// 800 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x3d, 0x6f, 0xd3, 0x5a,
	0x18, 0xee, 0xe9, 0xbd, 0x4d, 0xd3, 0x37, 0xba, 0x77, 0x38, 0x0d, 0x22, 0x75, 0x29, 0x41, 0x2e,
	0xb4, 0x69, 0x9b, 0xfa, 0xb4, 0x29, 0x12, 0x1f, 0x0b, 0x6a, 0x40, 0x30, 0x20, 0xd4, 0x10, 0x98,
	0x90, 0x50, 0x75, 0x92, 0x18, 0x13, 0x35, 0xf1, 0x71, 0x73, 0x1c, 0x44, 0x54, 0x55, 0x42, 0x48,
	0x48, 0x4c, 0x30, 0xb0, 0x20, 0xb1, 0x94, 0x05, 0x09, 0x56, 0xfe, 0x44, 0x07, 0x36, 0x76, 0x58,
	0x18, 0xf8, 0x19, 0x28, 0xe7, 0x23, 0xb5, 0x13, 0x37, 0xf1, 0x10, 0xa6, 0xd8, 0xaf, 0xdf, 0x8f,
	0xe7, 0x79, 0x8e, 0xdf, 0xc7, 0x81, 0x6c, 0x95, 0xf1, 0x26, 0xe3, 0xa4, 0x42, 0xdd, 0x3d, 0xf2,
	0x6c, 0xb3, 0x62, 0xfb, 0x74, 0x93, 0xec, 0xb7, 0xed, 0x56, 0xc7, 0xf2, 0x5a, 0xcc, 0x67, 0x78,
	0x56, 0x26, 0x58, 0xdd, 0x04, 0x4b, 0x25, 0x18, 0xab, 0xbd, 0x2a, 0x6e, 0xcb, 0xec, 0x5e, 0xad,
	0x47, 0x9d, 0xba, 0x4b, 0xfd, 0x3a, 0x73, 0x65, 0x03, 0x23, 0xed, 0x30, 0x87, 0x89, 0x4b, 0xd2,
	0xbd, 0x52, 0xd1, 0x73, 0x0e, 0x63, 0x4e, 0xc3, 0x26, 0xd4, 0xab, 0x13, 0xea, 0xba, 0xcc, 0x17,
	0x25, 0x5c, 0x3d, 0x3d, 0x1f, 0xec, 0xaf, 0x3b, 0x57, 0x59, 0xdd, 0x1d, 0x78, 0x1e, 0x40, 0x2d,
	0x10, 0x8a, 0xe7, 0xe6, 0x0e, 0xcc, 0xde, 0xef, 0xa2, 0x2a, 0xd2, 0x06, 0x75, 0xab, 0x76, 0xd9,
	0xde, 0x6f, 0xdb, 0xdc, 0xc7, 0x19, 0x98, 0xa6, 0xb5, 0x5a, 0xcb, 0xe6, 0x3c, 0x83, 0x2e, 0xa0,
	0xdc, 0x4c, 0x59, 0xdf, 0xe2, 0x34, 0x4c, 0xd5, 0x6c, 0x97, 0x35, 0x33, 0x93, 0x22, 0x2e, 0x6f,
	0xae, 0x27, 0x5f, 0x1f, 0x65, 0x27, 0x7e, 0x1f, 0x65, 0x27, 0xcc, 0xbb, 0x90, 0x0e, 0x37, 0xe4,
	0x1e, 0x73, 0xb9, 0x8d, 0xb7, 0x60, 0xba, 0x22, 0x43, 0xa2, 0x63, 0xaa, 0x30, 0x67, 0xf5, 0xf4,
	0xe2, 0xb6, 0xd6, 0xcb, 0xba, 0xc9, 0xea, 0x6e, 0x59, 0x67, 0x9a, 0xaf, 0x10, 0x9c, 0x15, 0xdd,
	0xb6, 0x1b, 0x0d, 0xd5, 0x90, 0x8f, 0x86, 0x78, 0x1b, 0xe0, 0x44, 0x5b, 0x81, 0x33, 0x55, 0x58,
	0x0a, 0x4d, 0x93, 0xc7, 0xa6, 0x67, 0x96, 0xa8, 0xa3, 0x89, 0x97, 0x03, 0x95, 0x01, 0x52, 0xdf,
	0x10, 0x64, 0x06, 0x71, 0x28, 0x66, 0x0e, 0x24, 0x15, 0xde, 0x2e, 0x92, 0x7f, 0x86, 0x52, 0x2b,
	0x6e, 0x1c, 0xff, 0xc8, 0x4e, 0x7c, 0xf9, 0x99, 0xcd, 0x39, 0x75, 0xff, 0x69, 0xbb, 0x62, 0x55,
	0x59, 0x93, 0xa8, 0x23, 0x92, 0x3f, 0xeb, 0xbc, 0xb6, 0x47, 0xfc, 0x8e, 0x67, 0x73, 0x51, 0xc0,
	0xcb, 0xbd, 0xe6, 0xf8, 0x4e, 0x04, 0xaf, 0xe5, 0x91, 0xbc, 0x24, 0xca, 0x20, 0x31, 0x73, 0x4f,
	0xa9, 0xfa, 0x90, 0xf9, 0xb4, 0xf1, 0xa0, 0xed, 0x79, 0x8d, 0x8e, 0x56, 0x35, 0xac, 0x1d, 0x1a,
	0x83, 0x76, 0xc7, 0x5a, 0xbb, 0xd0, 0x34, 0xa5, 0x5d, 0x15, 0x12, 0x5c, 0x44, 0xfe, 0x86, 0x72,
	0xaa, 0xf5, 0xf8, 0x74, 0xcb, 0xab, 0x77, 0x5b, 0x92, 0xd8, 0x79, 0xa2, 0x45, 0xeb, 0xed, 0x04,
	0x0a, 0xec, 0x84, 0x59, 0x82, 0x33, 0x7d, 0xd9, 0x8a, 0xf4, 0x15, 0x48, 0xd0, 0x26, 0x6b, 0xbb,
	0xfe, 0xc8, 0x4d, 0x28, 0xfe, 0xdb, 0x25, 0x5d, 0x56, 0xe9, 0x66, 0x1a, 0xb0, 0xe8, 0x58, 0xa2,
	0x2d, 0xda, 0xd4, 0x8b, 0x60, 0x96, 0xd4, 0x0a, 0xeb, 0xa8, 0x9a, 0x72, 0x0d, 0x12, 0x9e, 0x88,
	0xa8, 0x29, 0xf3, 0x56, 0x84, 0x3f, 0x59, 0xb2, 0x48, 0xcf, 0x91, 0x05, 0x66, 0x0d, 0x0c, 0xd1,
	0xf1, 0x56, 0x97, 0x07, 0xbf, 0x67, 0xfb, 0xb4, 0x46, 0x7d, 0x3a, 0xe6, 0x57, 0xc4, 0xfc, 0x8c,
	0x60, 0x3e, 0x72, 0x8c, 0x22, 0xb0, 0x0d, 0x33, 0x4d, 0x15, 0xd3, 0x8b, 0xb5, 0x10, 0xc9, 0x41,
	0x57, 0x2a, 0x16, 0x27, 0x55, 0xe3, 0x3b, 0xf9, 0x4d, 0x98, 0x3b, 0x81, 0xda, 0x2f, 0x48, 0xf4,
	0xf1, 0x3f, 0x0e, 0x8a, 0x38, 0x40, 0xee, 0x06, 0x24, 0x35, 0x4c, 0x25, 0x61, 0x2c, 0x6e, 0xbd,
	0xa2, 0xc2, 0xd7, 0x24, 0x4c, 0x89, 0xfe, 0xf8, 0x3d, 0x82, 0x69, 0x65, 0x4a, 0x38, 0x17, 0xd9,
	0x24, 0xc2, 0xe1, 0x8d, 0x95, 0x18, 0x99, 0x12, 0xab, 0x79, 0xf5, 0xe5, 0xf7, 0x5f, 0xef, 0x26,
	0x0b, 0x78, 0x83, 0x44, 0x7f, 0x4c, 0xa4, 0x3d, 0x91, 0x03, 0xe5, 0xbf, 0x87, 0xa4, 0xd2, 0xd9,
	0x15, 0x1a, 0xe0, 0x0f, 0x08, 0x52, 0x01, 0xcb, 0xc4, 0xf9, 0xd3, 0x87, 0x0e, 0x3a, 0xbc, 0xb1,
	0x1e, 0x33, 0x5b, 0xc1, 0x24, 0x02, 0xe6, 0x0a, 0x5e, 0x8e, 0x09, 0x13, 0xbf, 0x45, 0x90, 0x0a,
	0x98, 0xd2, 0x30, 0x74, 0x83, 0x4e, 0x39, 0x0c, 0x5d, 0x84, 0xd3, 0x99, 0x8b, 0x02, 0xdd, 0x02,
	0x9e, 0x8f, 0x44, 0xa7, 0x9c, 0xea, 0x0d, 0x82, 0xa4, 0xb6, 0x0b, 0x3c, 0xe4, 0x84, 0xfa, 0x0c,
	0xc8, 0x58, 0x8d, 0x93, 0xaa, 0x80, 0xac, 0x09, 0x20, 0x97, 0xf0, 0xe2, 0x10, 0x20, 0xe4, 0x40,
	0x9c, 0xdf, 0x21, 0x7e, 0x81, 0x20, 0x21, 0x2d, 0x02, 0x2f, 0x9f, 0x3e, 0x23, 0xe4, 0x47, 0x46,
	0x6e, 0x74, 0x62, 0x2c, 0x4d, 0xa4, 0x19, 0xe1, 0x4f, 0x08, 0xfe, 0x0b, 0xed, 0x10, 0xb6, 0x4e,
	0x1f, 0x10, 0xb5, 0x9f, 0x06, 0x89, 0x9d, 0xaf, 0x70, 0x5d, 0x16, 0xb8, 0x2c, 0x9c, 0x8f, 0xc4,
	0x25, 0xa4, 0xe1, 0xbb, 0x7a, 0x13, 0x7b, 0x5a, 0x7d, 0x44, 0xf0, 0x7f, 0xd8, 0xca, 0xf0, 0xa8,
	0xc9, 0xfd, 0xde, 0x6a, 0x6c, 0xc4, 0x2f, 0x50, 0x58, 0xf3, 0x02, 0xeb, 0x12, 0xbe, 0x18, 0x07,
	0x6b, 0x71, 0xed, 0xd1, 0xca, 0xd0, 0xcf, 0xe7, 0x73, 0x59, 0x2e, 0xbe, 0xa2, 0x95, 0x84, 0xf8,
	0x8b, 0xb8, 0xf5, 0x27, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x07, 0xdf, 0x75, 0xfa, 0x0a, 0x00, 0x00,
}
