// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cosmos/bank/v1beta1/tx.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// MsgSend represents a message to send coins from one account to another.
type MsgSend struct {
	FromAddress          string        `protobuf:"bytes,1,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	ToAddress            string        `protobuf:"bytes,2,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	Amount               []*types.Coin `protobuf:"bytes,3,rep,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *MsgSend) Reset()         { *m = MsgSend{} }
func (m *MsgSend) String() string { return proto.CompactTextString(m) }
func (*MsgSend) ProtoMessage()    {}
func (*MsgSend) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d8cb1613481f5b7, []int{0}
}

func (m *MsgSend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgSend.Unmarshal(m, b)
}
func (m *MsgSend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgSend.Marshal(b, m, deterministic)
}
func (m *MsgSend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSend.Merge(m, src)
}
func (m *MsgSend) XXX_Size() int {
	return xxx_messageInfo_MsgSend.Size(m)
}
func (m *MsgSend) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSend.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSend proto.InternalMessageInfo

func (m *MsgSend) GetFromAddress() string {
	if m != nil {
		return m.FromAddress
	}
	return ""
}

func (m *MsgSend) GetToAddress() string {
	if m != nil {
		return m.ToAddress
	}
	return ""
}

func (m *MsgSend) GetAmount() []*types.Coin {
	if m != nil {
		return m.Amount
	}
	return nil
}

// MsgSendResponse defines the Msg/Send response type.
type MsgSendResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgSendResponse) Reset()         { *m = MsgSendResponse{} }
func (m *MsgSendResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSendResponse) ProtoMessage()    {}
func (*MsgSendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d8cb1613481f5b7, []int{1}
}

func (m *MsgSendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgSendResponse.Unmarshal(m, b)
}
func (m *MsgSendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgSendResponse.Marshal(b, m, deterministic)
}
func (m *MsgSendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSendResponse.Merge(m, src)
}
func (m *MsgSendResponse) XXX_Size() int {
	return xxx_messageInfo_MsgSendResponse.Size(m)
}
func (m *MsgSendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSendResponse proto.InternalMessageInfo

// MsgMultiSend represents an arbitrary multi-in, multi-out send message.
type MsgMultiSend struct {
	Inputs               []*Input  `protobuf:"bytes,1,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs              []*Output `protobuf:"bytes,2,rep,name=outputs,proto3" json:"outputs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MsgMultiSend) Reset()         { *m = MsgMultiSend{} }
func (m *MsgMultiSend) String() string { return proto.CompactTextString(m) }
func (*MsgMultiSend) ProtoMessage()    {}
func (*MsgMultiSend) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d8cb1613481f5b7, []int{2}
}

func (m *MsgMultiSend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgMultiSend.Unmarshal(m, b)
}
func (m *MsgMultiSend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgMultiSend.Marshal(b, m, deterministic)
}
func (m *MsgMultiSend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMultiSend.Merge(m, src)
}
func (m *MsgMultiSend) XXX_Size() int {
	return xxx_messageInfo_MsgMultiSend.Size(m)
}
func (m *MsgMultiSend) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMultiSend.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMultiSend proto.InternalMessageInfo

func (m *MsgMultiSend) GetInputs() []*Input {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *MsgMultiSend) GetOutputs() []*Output {
	if m != nil {
		return m.Outputs
	}
	return nil
}

// MsgMultiSendResponse defines the Msg/MultiSend response type.
type MsgMultiSendResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgMultiSendResponse) Reset()         { *m = MsgMultiSendResponse{} }
func (m *MsgMultiSendResponse) String() string { return proto.CompactTextString(m) }
func (*MsgMultiSendResponse) ProtoMessage()    {}
func (*MsgMultiSendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d8cb1613481f5b7, []int{3}
}

func (m *MsgMultiSendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgMultiSendResponse.Unmarshal(m, b)
}
func (m *MsgMultiSendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgMultiSendResponse.Marshal(b, m, deterministic)
}
func (m *MsgMultiSendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMultiSendResponse.Merge(m, src)
}
func (m *MsgMultiSendResponse) XXX_Size() int {
	return xxx_messageInfo_MsgMultiSendResponse.Size(m)
}
func (m *MsgMultiSendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMultiSendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMultiSendResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgSend)(nil), "cosmos.bank.v1beta1.MsgSend")
	proto.RegisterType((*MsgSendResponse)(nil), "cosmos.bank.v1beta1.MsgSendResponse")
	proto.RegisterType((*MsgMultiSend)(nil), "cosmos.bank.v1beta1.MsgMultiSend")
	proto.RegisterType((*MsgMultiSendResponse)(nil), "cosmos.bank.v1beta1.MsgMultiSendResponse")
}

func init() { proto.RegisterFile("cosmos/bank/v1beta1/tx.proto", fileDescriptor_1d8cb1613481f5b7) }

var fileDescriptor_1d8cb1613481f5b7 = []byte{
	// 411 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcd, 0x4e, 0xea, 0x40,
	0x1c, 0xc5, 0x29, 0x10, 0xb8, 0x0c, 0x24, 0x37, 0x14, 0xee, 0xbd, 0xdc, 0x4a, 0x2c, 0x36, 0x2e,
	0x20, 0xc6, 0xa9, 0xa0, 0x0b, 0x53, 0x57, 0xd6, 0x95, 0x26, 0x8d, 0x49, 0x5d, 0xe9, 0xc6, 0xf4,
	0x63, 0xac, 0x0d, 0xb4, 0xd3, 0x30, 0x53, 0x03, 0x6f, 0x60, 0xe2, 0x4b, 0xb0, 0x36, 0x3e, 0x88,
	0x4f, 0x81, 0x5b, 0xe3, 0x92, 0x27, 0x30, 0x9d, 0x7e, 0x40, 0x22, 0xe2, 0xaa, 0x9d, 0x9c, 0xff,
	0xef, 0xf4, 0x9c, 0xfe, 0x07, 0xb4, 0x2d, 0x4c, 0x3c, 0x4c, 0x64, 0xd3, 0xf0, 0x87, 0xf2, 0x43,
	0xdf, 0x44, 0xd4, 0xe8, 0xcb, 0x74, 0x02, 0x83, 0x31, 0xa6, 0x98, 0x6f, 0xc4, 0x2a, 0x8c, 0x54,
	0x98, 0xa8, 0x42, 0xd3, 0xc1, 0x0e, 0x66, 0xba, 0x1c, 0xbd, 0xc5, 0xa3, 0xc2, 0x76, 0x66, 0x44,
	0x50, 0x66, 0x64, 0x61, 0xd7, 0xff, 0xa2, 0xaf, 0x7c, 0x88, 0xf9, 0x32, 0x5d, 0xfa, 0xe0, 0x40,
	0x59, 0x23, 0xce, 0x15, 0xf2, 0x6d, 0x5e, 0x01, 0xb5, 0xbb, 0x31, 0xf6, 0x6e, 0x0d, 0xdb, 0x1e,
	0x23, 0x42, 0x5a, 0x5c, 0x87, 0xeb, 0x56, 0xd4, 0x7f, 0x8b, 0xb9, 0xd8, 0x98, 0x1a, 0xde, 0x48,
	0x91, 0x56, 0x55, 0x49, 0xaf, 0x46, 0xc7, 0xd3, 0xf8, 0xc4, 0x1f, 0x01, 0x40, 0x71, 0x46, 0xe6,
	0x19, 0xf9, 0x67, 0x31, 0x17, 0xeb, 0x31, 0xb9, 0xd4, 0x24, 0xbd, 0x42, 0x71, 0x4a, 0x59, 0xa0,
	0x64, 0x78, 0x38, 0xf4, 0x69, 0xab, 0xd0, 0x29, 0x74, 0xab, 0x83, 0xff, 0x30, 0x6b, 0x4e, 0x50,
	0xda, 0x1c, 0x9e, 0x61, 0xd7, 0x57, 0x0f, 0x5e, 0xe7, 0x62, 0xee, 0xf9, 0x4d, 0xec, 0x3a, 0x2e,
	0xbd, 0x0f, 0x4d, 0x68, 0x61, 0x4f, 0x4e, 0xba, 0xc5, 0x8f, 0x7d, 0x62, 0x0f, 0x65, 0x3a, 0x0d,
	0x10, 0x61, 0x00, 0xd1, 0x13, 0x6b, 0xe5, 0xd7, 0xe3, 0x4c, 0xcc, 0xbd, 0xcf, 0xc4, 0x9c, 0x54,
	0x07, 0xbf, 0x93, 0xae, 0x3a, 0x22, 0x01, 0xf6, 0x09, 0x92, 0x9e, 0x38, 0x50, 0xd3, 0x88, 0xa3,
	0x85, 0x23, 0xea, 0xb2, 0x9f, 0x70, 0x0c, 0x4a, 0xae, 0x1f, 0x84, 0x34, 0xaa, 0x1f, 0x45, 0x12,
	0xe0, 0x9a, 0x65, 0xc0, 0xf3, 0x68, 0x44, 0x2d, 0x46, 0x99, 0xf4, 0x64, 0x9e, 0x3f, 0x01, 0x65,
	0x1c, 0x52, 0x86, 0xe6, 0x19, 0xba, 0xb5, 0x16, 0xbd, 0x64, 0x33, 0x09, 0x9b, 0x12, 0x4a, 0x91,
	0x05, 0xfc, 0x0b, 0x9a, 0xab, 0x61, 0xd2, 0x94, 0x83, 0x17, 0x0e, 0x14, 0x34, 0xe2, 0xf0, 0x17,
	0xa0, 0xc8, 0x42, 0xb6, 0xd7, 0x3a, 0x27, 0xdd, 0x84, 0xdd, 0x4d, 0x6a, 0xea, 0xc9, 0x5f, 0x83,
	0xca, 0xb2, 0xf5, 0xce, 0x77, 0x48, 0x36, 0x22, 0xf4, 0x7e, 0x1c, 0x49, 0xad, 0xd5, 0xbd, 0x9b,
	0xde, 0xc6, 0x2d, 0x4d, 0xe2, 0xeb, 0xc8, 0x96, 0x65, 0x96, 0xd8, 0x45, 0x3c, 0xfc, 0x0c, 0x00,
	0x00, 0xff, 0xff, 0x3c, 0x40, 0x86, 0xc7, 0x13, 0x03, 0x00, 0x00,
}
